### ISSUE TITLE
ionic serve --lab only loads iOS

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-cli#1674] opened 2016-11-14 15:50 UTC
_From @ix-xerri on November 11, 2016 6:32_

When running ionic serve --lab on a new project with the latest update on ionic, node and npm it only loads the normal site so --lab is being ignored. In platform json I only see iOS. This is a new project with no changes off the tabs template. Running on Mac OS Sierra, Ionic 2.

_Copied from original issue: driftyco/ionic#9120_

**Comment by jthoms1** [comment] 2016-11-14 16:32
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.

**Comment by ix-xerri** [comment] 2016-11-14 16:45
Your system information:

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.7
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 0.0.42
ios-deploy version: 1.9.0 
ios-sim version: 5.0.11 
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.1 Build version 8B62

**Comment by matheusdavidson** [comment] 2016-11-14 18:07
same problem here:
Your system information:

Cordova CLI: 6.4.0
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 0.0.39
OS:
Node Version: v5.4.0

**Comment by jthoms1** [comment] 2016-11-15 02:04
This problem will be resolved with the release of @ionic/app-scripts 0.0.43.  I expect this to be released tomorrow.  A quick fix for you know would be to upgrade your CLI to `2.1.8` and when lab loads change the url path to: `/__ion-dev-server/ionic-lab.html`

Thanks!

**Comment by matheusdavidson** [comment] 2016-11-15 02:07
i solved it changing package.json scripts to:
```        "build": "ionic-app-scripts build",
        "watch": "ionic-app-scripts watch",
        "serve:before": "watch",
        "emulate:before": "build",
        "deploy:before": "build",
        "build:before": "build",
        "run:before": "build"```

**Comment by ix-xerri** [comment] 2016-11-15 15:23
Still not fixed. Running v0.0.43

Your system information:

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.7
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 0.0.43
ios-deploy version: 1.9.0 
ios-sim version: 5.0.11 
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.1 Build version 8B62

**Comment by jthoms1** [comment] 2016-11-15 17:06
@ix-xerri I appologize, you are correct.  It is slated for 0.0.44 release. I had assumed it was in an earlier release.   

I will keep this thread up to date on when it is slated for release.  Thank you for your patience.

**Comment by jthoms1** [comment] 2016-11-15 17:17
Ok, so 0.0.44 is out.  I just verified and it does include the update for lab. Please update app-scripts to 0.0.44 and the issue is resolved. Thanks!

**Closed by jthoms1** 2016-11-15 17:17 UTC

**Comment by ix-xerri** [comment] 2016-11-15 17:46
It does not work. Any cache or other update getting in the way? Running ionic serve --lab and loading in Chrome Incognito

Your system information:

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.7
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 0.0.44
ios-deploy version: 1.9.0 
ios-sim version: 5.0.11 
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.1 Build version 8B62

**Comment by ix-xerri** [comment] 2016-11-16 18:29
updated the whole ionic and it worked. thanks
