### ISSUE TITLE
v3-rc1 not work upload

### ISSUE THREAD

**Issue by javico2609** [driftyco/ionic-cli#2204] opened 2017-05-03 00:05 UTC
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/driftyco/ionic-app-scripts

Please ensure that you are on the latest version of the CLI.
`npm view ionic@latest version`

#### What version of the CLI are you using? Output of `ionic --version`

ionic --version
3.0.0-rc.1

#### What behavior are you expecting?

**Steps to reproduce:**
upload my app to ionic view

```
λ ionic upload
Running app-scripts build:

[20:44:45]  build dev started ...
[20:44:45]  clean started ...
[20:44:45]  clean finished in 10 ms
[20:44:45]  copy started ...
[20:44:45]  transpile started ...
[20:44:49]  transpile finished in 3.17 s
[20:44:49]  preprocess started ...
[20:44:49]  deeplinks started ...
[20:44:49]  deeplinks finished in 121 ms
[20:44:49]  preprocess finished in 124 ms
[20:44:49]  webpack started ...
[20:44:49]  copy finished in 3.46 s
[20:45:00]  webpack finished in 11.03 s
[20:45:00]  sass started ...
[20:45:01]  sass finished in 976 ms
[20:45:01]  postprocess started ...
[20:45:01]  postprocess finished in 5 ms
[20:45:01]  lint started ...
[20:45:01]  build dev finished in 15.59 s
✔ Requesting snapshot upload - done!
/ Uploading snapshot
```

**Post the output of `ionic info` below please**
```
global packages:

    @ionic/cli-utils : 1.0.0-rc.1
    Cordova CLI      : 6.5.0
    Ionic CLI        : 3.0.0-rc.1

local packages:

    @ionic/app-scripts              : 1.3.6
    @ionic/cli-plugin-cordova       : 1.0.0-rc.1
    @ionic/cli-plugin-ionic-angular : 1.0.0-rc.1
    Ionic Framework                 : ionic-angular 3.1.1

System:

    Node       : v7.7.3
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
```
**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by piotrowski** [comment] 2017-05-03 07:03
Could you retry multiple times and see if you get a different result or maybe an error message?
(I have similar problems on my Windows 10 machine but sometimes get a strange error, too)

**Comment by dwieeb** [comment] 2017-05-03 18:56
Thanks, duplicate of https://github.com/driftyco/ionic-cli/issues/2189

Upload is having strange behavior on Windows 10.

**Closed by dwieeb** 2017-05-03 18:56 UTC
