### ISSUE TITLE
bug: TypeError: Request path contains unescaped char

### ISSUE THREAD

**Issue by perrygovier** [driftyco/ionic-cli#321] opened 2015-03-20 20:15 UTC
_From @Kyozatch on March 19, 2015 8:43_

**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi,

I just downloaded ionic. I created the project without any problem but, when i tried "ionic platform add android" i got an error :
"npm http GET https://registry.npmjs.org/cordova-android/3.7.1
TypeError: Request path contains unescaped characters."

I was looking for a solution on google, it seems to be a proxy problem. However, I already set my proxy config and it works..

ionic : 1.3.16 cordova : 4.3.0 node : 0.12.0

Thanks</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#3355_

**Comment by jbavari** [comment] 2015-03-25 17:53
@kyozatch - does this keep happening every time you run it?

What did you set your proxy settings to?

**Comment by Kyozatch** [comment] 2015-03-26 09:35
Yes everytime. I tried on an other free BOX and it works. But with my corporate proxy, it seems pretty complicated.

My .npmrc file  : 
proxy=http://myproxy:myport/
registry=http://registry.npmjs.org/
https-proxy=http://myproxy:myport/
strict-ssl=false

I did set my environment variables in Windows too.

This config has already been tested and works. Did i miss something else ?...

**Comment by phearme** [comment] 2015-03-27 10:21
++
same problem on my side. I don't want to downgrade node. seems to be a problem with Cordova rather than ionic because the following command produces also the error :

cordova platform add android

**Comment by geisi93** [comment] 2015-04-09 14:47
Did anybody come up with some solution to this problem without downgrading node? it is not a matter of proxy or environment variable - there is some problem with cordova.

**Comment by jonmikelm** [comment] 2015-04-20 07:25
Same problem here, solved the issue downgrading node to 0.10.29

**Comment by pulsee** [comment] 2015-04-20 12:21
Same problem tried following : 
npm config set proxy http://proxydomain:port/
npm config set registry http://registry.npmjs.org/

Tried following versions with error :
Cordova 4.3.0
Cordova 4.0.0

**Comment by geisi93** [comment] 2015-04-20 13:59
I didn't want to downgrade node, so I found another solution somewhere in the Web:

Replace the content of C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\node_modules\tunnel-agent 

with the content of this zip:

https://github.com/mikeal/tunnel-agent

**Comment by arlyxiao** [comment] 2015-05-04 10:03
Same problem here

**Comment by Cooker-Monster** [comment] 2015-05-06 08:19
Hi, 
same problem on Windows with :
- cordova : 5.0
- npm : 2.7.4
- node: v0.12.2

**Comment by generic-user** [comment] 2015-05-07 14:44
@geisi93 That works, thanks!

**Comment by geisi93** [comment] 2015-05-13 13:54
for those who still have problems -
propably you have to replace the contents of 

C:\Users\{USERNAME}\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\request\node_modules\tunnel-agent

with the contents of with the content of this zip:

https://github.com/mikeal/tunnel-agent

too.

**Comment by s0th** [comment] 2015-05-13 16:52
@geisi93 you are a star! worked perfectly

**Comment by faizaghaazfaiz** [comment] 2015-05-18 07:09
Hi , 
i am facing request path contains unescaped characters even after setting proxy and registry , and even changed the contents of tunnel_agent.

**Comment by faizaghaazfaiz** [comment] 2015-05-18 08:10
I have installed node v0.12.3 , cordova 5.0.0 ,npm 2.9.1 
please guide me , what i am doing wrong...

**Comment by geisi93** [comment] 2015-05-18 09:49
look at the console, there you can see the path of the tunnel-agent where the problem occurs. make sure to replace the tunnel-agent exactly in the path, that is shown in the console!

**Comment by jason5149** [comment] 2015-05-19 09:33
Just try the new version of node v0.12.3, but unfortunately they haven't fixed this issue...

**Comment by DarrylD** [comment] 2015-05-19 18:25
Had same issue when trying to run crosswalk, dropped node version back down to 0.10.33, worked fine after that.

**Comment by Kyozatch** [comment] 2015-05-20 08:22
I tried @DarrylD's solution. Works perfectly for me. Have a good day.

**Comment by vishal2511** [comment] 2015-05-20 09:38
thanks geisi93, your solution worked like a charm...

**Comment by ygayl** [comment] 2015-05-21 00:56
Thanks @geisi93, works perfectly for me too :)

**Comment by jbavari** [comment] 2015-05-21 04:37
@geisi93 is this an issue with the cordova-lib then, you think? 

I see [here](https://github.com/apache/cordova-lib/blob/master/cordova-lib/package.json#L37) they are still using an older version of the `request` module.

If we can convince them to update it to 2.55.1 - that'd get that fix you all are using - correct?

**Comment by geisi93** [comment] 2015-05-21 07:42
@jbavari basically it works when you downgrade nodejs, so nodejs uses also an old version. but since changing the tunnel-agent in the cordova-lib solves the problem, an update to the newest version could possibly help, yes.

**Comment by phearme** [comment] 2015-05-21 10:29
how do you replace tunnel-agent on linux ?

**Comment by oneiljm** [comment] 2015-05-21 13:53
Can someone help me out and explain how to replace the tunnel-agent on windows 8.1. I have installed cordova and nodejs many times, but this latest version is killing me. Here is my output from my command prompt:cordova platform add wp8

npm http GET https://registry.npmjs.org/cordova-wp8/3.8.0 TypeError: Request path contains unescaped characters

    at new ClientRequest (_http_client.js:73:11)

    at TunnelingAgent.exports.request (http.js:49:10)

    at TunnelingAgent.createSocket (C:\Users\oneilj\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\npm\node_modules\req

uest\node_modules\tunnel-agent\index.js:117:25)

    at TunnelingAgent.createSecureSocket [as createSocket] (C:\Users\oneilj\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modu
les\npm\node_modules\request\node_modules\tunnel-agent\index.js:184:41)

    at TunnelingAgent.addRequest (C:\Users\oneilj\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\npm\node_modules\reque
st\node_modules\tunnel-agent\index.js:80:8)

    at new ClientRequest (_http_client.js:154:16)

    at Object.exports.request (http.js:49:10)

    at Object.exports.request (https.js:136:15)

    at Request.start (C:\Users\oneilj\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\npm\node_modules\request\index.js:
594:30)

    at Request.end (C:\Users\oneilj\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\npm\node_modules\request\index.js:11
86:28)

**Comment by geisi93** [comment] 2015-05-21 14:11
@oneiljm I have explained it above. Just download the current tunnel agent and replace the folder in the path the error message shows

**Comment by oneiljm** [comment] 2015-05-21 14:13
Thanks

**Comment by paulocesarpcfj** [comment] 2015-05-21 21:14
Solution from @geisi93 works like a charm :P ! Thank you.

**Comment by jonmikelm** [comment] 2015-05-22 07:47
Also worked @geisi93 's solution for me. It looks like the problem is the npm dependency of the last cordova-lib.

      cordova-lib 5.0.0 -> npm 1.3.4 -> request 2.21.0 -> tunnel-agent: 0.3.0

A newer npm version would resolve to a newer tunnel-agent version. 

      cordova-lib 5.0.0 -> ###npm 2.11.0 -> request 2.55.0 -> tunnel-agent 0.4.0###

**Comment by nhanh2301** [comment] 2015-06-10 02:45
This issues still with nodejs version 0.12.4

Need install request module? or request module build-in nodejs?

**Comment by samurai55** [comment] 2015-06-19 08:18
If this issue is not relevant?
https://github.com/mikeal/tunnel-agent/issues/10

**Comment by brianfoody** [comment] 2015-06-26 00:03
I had this issue and an update to the latest cordova solved it;

npm update -g cordova

**Comment by normanhh3** [comment] 2015-07-14 18:21
Updating the index.js file in the tunnel-agent folder worked for me with Mac OS X Yosemite 10.10.4 - sure seems like there should be a better way!  Sigh. :-(

**Comment by ngloom** [comment] 2015-07-19 12:19
same problem here with newest ionic with error message:

```
Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic-starter-tabs/archive/master.zip
[=============================]  100%  0.0s
Updated the hooks directory to have execute permissions
Update Config.xml
Initializing cordova project


Adding in iOS application by default
npm http GET https://registry.npmjs.org/cordova-ios
An uncaught exception occurred and has been reported to Ionic



Request path contains unescaped characters. (CLI v1.6.1)

Your system information:

Cordova CLI: 5.1.1
Ionic Version: 1.0.1
Ionic CLI Version: 1.6.1
Ionic App Lib Version: 0.3.3
ios-deploy version: Not installed
ios-sim version: 3.1.1
OS: Mac OS X Yosemite
Node Version: v0.12.7
Xcode version: Xcode 6.4 Build version 6E35b

```

after replace the `/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/node_modules/tunnel-agent` with newest tunnel-agent v0.41, it seems works, 

Thanks all, guys.

**Comment by sLatzko** [comment] 2015-07-20 07:55
Thank you very much @geisi93!

**Comment by blowsie** [comment] 2015-07-23 10:37
@samurai55 still relevant, I ran into this today

**Comment by compactdave** [comment] 2015-07-24 04:37
I have node 0.12.7 and had the problem.
Tried @geisi93's initial solution. Discovered I had installed 64 bit version of node and that there was no tunnel-agent in my install of node. Copied the contents of https://github.com/mikeal/tunnel-agent-master to C:\Program Files\nodejs\node_modules\npm\node_modules, renaming to tunnel-agent.
No good.
Used @geisi93's follow up solution. Found tunnel-agent at C:\Users\{USER}\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\request\node_modules. Replaced it with https://github.com/mikeal/tunnel-agent-master, renaming to tunnel-agent.
Perfect!
Many thanks, @geisi93.

**Comment by bhandaribhumin** [comment] 2015-08-04 07:22
when build cordova project in netbeans error :
ant -f C:\\Users\\EnDev2\\Documents\\NetBeansProjects\\test_application\\nbproject "-Dupdate.task.jar=C:\\Program Files\\NetBeans 8.0\\webcommon\\ant\\extra\\org-netbeans-modules-cordova-projectupdate.jar" -Dandroid.project.activity=test_application -Dsite.root=www -Dstart.file=index.html -Dandroid.sdk.home=C:\\android\\adt-bundle-windows-x86_64-20140702\\sdk -Dandroid.target.device.arg=run -Dcordova.version=5.1.1-0.0.0 -Denv.DISPLAY=:0.0 "-Dios.certificate.name=iPhone Developer" -Dandroid.build.target=android-20 -Dconfig=android_1 build-android
check-android-template:
check-cordova-version:
check-cordova-project:
upgrade-to-cordova-project:
create-android:
cordova.cmd -d platform add android
npm http GET https://registry.npmjs.org/cordova-androidNo version supplied. Retrieving version from config.xml...

TypeError: Request path contains unescaped characters.
    at new ClientRequest (_http_client.js:73:11)
    at TunnelingAgent.exports.request (http.js:49:10)
    at TunnelingAgent.createSocket (C:\Users\EnDev2\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:117:25)
    at TunnelingAgent.createSecureSocket [as createSocket] (C:\Users\EnDev2\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:184:41)
    at TunnelingAgent.addRequest (C:\Users\EnDev2\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:80:8)
    at new ClientRequest (_http_client.js:154:16)
    at Object.exports.request (http.js:49:10)
    at Object.exports.request (https.js:136:15)
    at Request.start (C:\Users\EnDev2\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\npm\node_modules\request\index.js:594:30)
    at Request.end (C:\Users\EnDev2\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\npm\node_modules\request\index.js:1186:28)
C:\Users\EnDev2\Documents\NetBeansProjects\test_application\nbproject\build.xml:150: exec returned: 1
BUILD FAILED (total time: 3 seconds)

**Comment by EricOFreitas** [comment] 2015-08-05 20:37
Hi!
I executed my cmd in administrator mode and executed again the command and work fine ;)

**Comment by willywongi** [comment] 2015-08-13 11:51
See this issue: https://github.com/npm/npm/issues/4569
It's all sorted out with cordova-cli 5.2.0, which is already tagged on github (https://github.com/apache/cordova-lib/releases/tag/5.2.0) but still not on npm.

I wanted to use the new cordova-cli, so this is what I did:
- Installed dev version of cordova-cli from github:
`sudo npm install -g git://git@github.com:apache/cordova-cli.git`
- Changed a file in *ionic-app-lib*, which is one of the number of packages under the "ionic" umbrella:
```
# /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/info.js
# Change line 59 to this:
  info.cordova = result.output.replace('\n', '').slice(0, 5);
```
This is needed so that ionic recognize cordova version and does not complain about version mismatching.

I tried a lot of things, so beware: this could not work for you; I hope cordova and ionic will update soon though.

Ciao

**Comment by ibhag** [comment] 2016-03-21 04:58
@geisi93 Thanks for the solution. It worked!!

**Comment by RupenAnjaria** [comment] 2016-03-29 16:40
I tried the solution provided by @geisi93, however, now I am getting below error:
The "RunMdaTargetsInstall" task was not given a value for the required parameter "NpmInstallDir".

**Comment by jthoms1** [comment] 2016-10-28 00:36
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.

**Closed by jthoms1** 2016-10-28 00:36 UTC
Labels: needs_reply

**Comment by PabloEzequiel** [comment] 2017-01-04 18:58
Thanks a lot +geisi93 !

That works for me, replace:
(x86)\nodejs\node_modules\npm\node_modules\request\node_modules\tunnel-agent

with the content of this zip:

https://github.com/mikeal/tunnel-agent
