### ISSUE TITLE
Ionic won't generate resources for windows platform

### ISSUE THREAD

**Issue by Zorgatone** [driftyco/ionic-cli#814] opened 2016-03-03 16:07 UTC
I was able to install the platform `wp8` and generate the icon and splash for that one and for `android` and `iOS` and they worked fine. But the `wp8` platform is deprecated/obsolete and I removed it in favor of the `windows` platform.

Now if I have only `windows` installed `ionic resources` says I don't have any platform installed. If I also have android it generates the icon and splash only for that one.

How can I generate and use the icon and splash for `windows` instead of `wp8`?

Thanks

**Comment by vintage** [comment] 2016-03-15 10:29
I have same problem and it seems that CLI doesn't support generating icons/splashscreens for Windows (10) platform yet.

**Comment by Zorgatone** [comment] 2016-04-12 10:05
Any update on this?

It sucks to have to make the platform-specific images manually :disappointed:

**Comment by jgw96** [comment] 2016-07-12 19:49
Hello all! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic-cli/issues/913. Thanks for using Ionic!

**Closed by jgw96** 2016-07-12 19:49 UTC
Labels: platform:android, platform:ios, platform:windows
