### ISSUE TITLE
[beta 32] Error Initializing app

### ISSUE THREAD

**Issue by manekinekko** [driftyco/ionic-cli#1114] opened 2016-06-26 21:07 UTC
The installation process in beta 32 seems to be broken.

`Error Initializing app: There was an error with the spawned command: npminstall`

![image](https://cloud.githubusercontent.com/assets/1699357/16364907/34386734-3bf2-11e6-8ff6-f6f0f99706be.png)

**Comment by sasharevzin** [comment] 2016-06-28 18:27
@manekinekko https://github.com/driftyco/ionic-cli/issues/1089

**Comment by jthoms1** [comment] 2016-07-06 20:49
Closing this as a duplicate of #1013.

**Closed by jthoms1** 2016-07-06 20:49 UTC
