### ISSUE TITLE
--v2 tutorial exception

### ISSUE THREAD

**Issue by pbhowmic** [driftyco/ionic-cli#1089] opened 2016-06-18 19:26 UTC
Throws the following & ends

> Installing npm packages...
> Error with start undefined
> Error Initializing app: There was an error with the spawned command: npminstall
> There was an error with the spawned command: npminstall
> Caught exception:
>  undefined

**Comment by jthoms1** [comment] 2016-06-21 14:18
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.

**Comment by gadld** [comment] 2016-06-22 19:13
I'm having the same error on 2.0.0-beta.31

This is my info: 
Your system information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic CLI Version: 2.0.0-beta.31
Ionic App Lib Version: 2.0.0-beta.17
ios-deploy version: Not installed
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v5.5.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by stirumala9662** [comment] 2016-06-23 21:05
revert back to npm install -g ionic@2.0.0-beta.22

Many people reporting this issue with 2.0.0-beta.25 or above

**Comment by 3dd13** [comment] 2016-06-26 10:52
there are few things you need to do to upgrade / update

1. upgrade nodejs

        brew upgrade node

2. upgrade npm

        npm install -g npm

3. set new registry

        npm set registry http://registry.npmjs.org

**Comment by jthoms1** [comment] 2016-07-06 20:49
Closing this as a duplicate of #1013.

**Closed by jthoms1** 2016-07-06 20:49 UTC
