### ISSUE TITLE
ionic run android not relfecting changes on device

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic-cli#840] opened 2016-03-13 02:21 UTC
_From @NathanVss on March 12, 2016 14:35_

Hello everyone, I'm using v1.7.14.

Sometimes after correctly running ionic build android, and ionic run android the application keep the old JS/Css (...) files. 
So when this happens, even if a build and run multiple times the only solutions is to remove the app on the device and let ionic run re install it.
The problem is the same even if I close the application to.

Any solutions ? Thanks.

_Copied from original issue: driftyco/ionic#5822_

**Comment by niczak** [comment] 2016-06-14 18:22
I am having this issue as well.

**Comment by jgw96** [comment] 2016-07-12 20:19
Hello all! Is this still an issue with the latest version of ionic? Thanks!

**Comment by jgw96** [comment] 2016-07-19 14:17
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-07-19 14:17 UTC
Labels: needs reply, platform:android

**Comment by ganeswararaosundarapu** [comment] 2016-09-12 12:41
I have that issue in my Lenova K4 note.  I am using ionic 2.0.0. Thanks.

**Comment by simonbrazell** [comment] 2017-04-20 23:45
Hello, 

I'm experiencing this issue currently, environment as follows:

Cordova CLI: 6.5.0
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v7.1.0
Xcode version: Not installed

No matter what I do the changes I make in one of my JS files is not included in the Android build, I jave confirmed this by inspecting the generated main.js to see the previous code still. 

It's very frustrating...
