### ISSUE TITLE
This is error while setting up new project with ionic start ....

### ISSUE THREAD

**Issue by codershubhamverma** [driftyco/ionic-cli#1566] opened 2016-10-20 07:54 UTC
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined

**Comment by StevenFewster** [comment] 2016-10-20 14:36
Duplicate of #1560

**Comment by jthoms1** [comment] 2016-10-26 21:25
We recently released a new version of the CLI that should allow us to gather more insight into NPM issues.  Could you please update your CLI to at least 2.1.4?

`npm install -g ionic@latest`

Thank you!

**Closed** 2016-10-28 00:58 UTC
