### ISSUE TITLE
feat: Ionic2 Enable sourcemaps by default?

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic-cli#744] opened 2016-02-11 15:37 UTC
_From @lordgreg on January 24, 2016 20:30_

**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Currently, when starting new Ionic2 Project, you will only see transpiled code in your browser, which means way difficult bug finding and all-in-all code reviewing. 

I suggest, enabling, by default source-maps in app with:

1. tsconfig.json: "sourceMap": true,
2. webpack.config.json: devtool: 'source-map',

If this is not possible, at least document this in v2 docs.</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#5169_

**Comment by adamdbradley** [comment] 2016-02-11 15:37
_From @thaDude on January 29, 2016 22:13_

+1

**Comment by adamdbradley** [comment] 2016-02-11 15:37
_From @MatanYed on February 11, 2016 9:33_

+1

**Comment by ciekawy** [comment] 2016-02-23 17:47
+1

**Comment by leonhardt** [comment] 2016-03-14 05:27
+1

**Comment by ceefour** [comment] 2016-03-23 19:35
:+1: for this, see confusion/request in https://forum.ionicframework.com/t/sourcemaps-in-new-project-structure/40812

**Comment by Sturgelose** [comment] 2016-03-31 20:56
Do we have any update on how to do so now that webpack has been removed and we only have gulp?
For some reason I can see the map files there but I can't find them in sources in Chrome!

(Ionic CLI 2.0.0-beta.23)

**Comment by tlancina** [comment] 2016-03-31 21:14
Hmm, they're working for me do you have them enabled in Chrome? Under Settings:

![image](https://cloud.githubusercontent.com/assets/804331/14191060/9154deec-f75b-11e5-8cdf-d1c61be7bb9f.png)

**Comment by Sturgelose** [comment] 2016-03-31 21:22
@tlancina Yes, I have this enabled. I can debug properly an older app, that came with the webpack. However, now I run a simple `ionic serve`, the app starts fine but no sources to find to debug:

![image](https://cloud.githubusercontent.com/assets/244191/14191267/458b5e00-f797-11e5-85f0-c6d460e5f63d.png)

**Comment by tlancina** [comment] 2016-03-31 22:14
Wow no sources at all! I'm not sure, what version of Chrome? Does an
incognito window work?

**Comment by Sturgelose** [comment] 2016-03-31 22:17
Version 49.0.2623.110 (64-bit) for MacOS on ElCapitan (latest update)

Well, randomly it works in the incognito mode! 
Will try to see if there is any extension (for some reason) disabling this :/

**Comment by tlancina** [comment] 2016-04-17 00:42
Going to close this, as it sounds like it may have been caused by an extension.  Let me know if that's not the case though and I can reopen, thanks!

**Closed by tlancina** 2016-04-17 00:42 UTC
Labels: build, feature, v2

**Comment by RoelRoel** [comment] 2017-02-16 13:29
webpack.config.json is nowhere to be found
Yesterday I could debug ts files and today it suddenly stopped working....

**Comment by nfantone** [comment] 2017-04-27 18:26
Not getting any source files on DevTools with `3.0.0-beta9`.
