### ISSUE TITLE
Something wrong with ionic2 enviroment base on win7

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-cli#1181] opened 2016-07-15 15:29 UTC
_From @meiyalei on July 15, 2016 4:3_

I have something wrong when i am used to  ionic2 module.
The enviroment as shown:
__________________________
1. windows 7
2. nodejs  6.3.0
3. npm 3.10.5
4. cordova 6.2.0
5. ionic 2.0.0-beta.32
_________________________

And now, i use cli comment [ionic start demos --v2] to create a new project, like this,
_______________________________________________________________________________________
E:\idea>ionic start demos --v2
Creating Ionic app in folder E:\idea\demos based on tabs project
Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic2-starter-tabs/archive/master.zip
[=============================]  100%  0.0s
Installing npm packages...
_______________________________________________________________________________________ 

But the process is sticking [Installing npm packages...] for long time,
then error messages are shown:
_____________________________________________________________
Error with start undefined
Error Initializing app: There was an error with the spawned command
There was an error with the spawned command: npminstall
Caught exception:
 undefined

Mind letting us know? https://github.com/driftyco/ionic-cli/issues
_____________________________________________________________

In view of the above problems, i have no idea.
So, Can you help me. 
Thanks a lot.

_Copied from original issue: driftyco/ionic#7326_

**Comment by bacgauden112** [comment] 2016-07-16 15:54
i also have this issue.

**Comment by meiyalei** [comment] 2016-07-17 00:49
how to solve this issue?

**Comment by jthoms1** [comment] 2016-07-25 20:54
This is a duplicate of #1013.

I am closing this issue. It has been kind of a catch all for npm install issues from ionic start. If you are having issues please try running with the verbose flag.

`sudo ionic start cutePuppyPics --v2 --verbose`

This should provide more insight into what is happening. In most cases it will report issues with network connectivity or permissions issues. If this is not the case please open an issue with your ionic info output.

**Closed by jthoms1** 2016-07-25 20:54 UTC
Labels: v2

**Comment by Hackcr** [comment] 2016-07-26 05:52
i also have this issue.

**Comment by DerekTso** [comment] 2017-04-14 13:05
@ jthoms1, could you advise how's the issue to be fixed? Thanks
