### ISSUE TITLE
ionic emulate ios --target=" doesn't work any more

### ISSUE THREAD

**Issue by KevinBeckers** [driftyco/ionic-cli#1788] opened 2016-12-19 10:47 UTC
When I run `ionic emulate ios --target="iPad-Retina"` The following error occurs:

`Device type "com.apple.CoreSimulator.SimDeviceType."iPad-Retina"" could not be found.`

It doesn't matter which device I chose in the target option
I also tested `cordova emulate ios --target="iPad-Retina"` and this works fine.

Cordova CLI: 6.4.0
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
ios-deploy version: 1.8.6
ios-sim version: 5.0.6
OS: macOS Sierra
Node Version: v5.6.0
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by KevinBeckers** [comment] 2016-12-19 10:53
After a Ionic downgrade it works fine again.
`sudo npm install -g  ionic@2.1.10`

**Comment by israeljrs** [comment] 2016-12-19 12:04
It did not work for me either. ionic emulate ios --target="IPhone-5s 10.2"

**Comment by KevinBeckers** [comment] 2016-12-19 12:06
Did downgrading work?

**Comment by israeljrs** [comment] 2016-12-19 12:07
not yet. I'm going to test and report here.

**Comment by jthoms1** [comment] 2016-12-21 14:37
Closing as a duplicate of #1756. Where resolution discussion is taking place.

**Closed by jthoms1** 2016-12-21 14:37 UTC
