### ISSUE TITLE
ionic upload modify index.html

### ISSUE THREAD

**Issue by thomas-tran** [driftyco/ionic-cli#452] opened 2015-06-02 06:27 UTC
I tried to upload project to ionic view for testing. The CLI modified my index and put extra characters &#xFEFF;<!DOCTYPE html> as a result my app was broken.

**Comment by jbavari** [comment] 2015-06-02 18:13
Can you post some before and after HTML?

Also, `ionic info` - and post that info here.

**Comment by thomas-tran** [comment] 2015-06-02 23:27
Hi jbavari,

Here are the before and after

Before

![before](https://cloud.githubusercontent.com/assets/5725085/7949589/b45bbfae-09d2-11e5-8139-a31d4dcc2073.PNG)

After upload

![after](https://cloud.githubusercontent.com/assets/5725085/7949590/b4e2e150-09d2-11e5-9b7d-2acadd0057a3.PNG)

ionic info

![info](https://cloud.githubusercontent.com/assets/5725085/7949595/ba5095ce-09d2-11e5-8419-a8d68bb349c4.PNG)

**Comment by simplesmiler** [comment] 2015-06-03 20:46
@thomas-tran it looks like BOM. What text editor do you use?

**Comment by thomas-tran** [comment] 2015-06-03 20:47
Visual studio 2013

**Comment by bradmartin** [comment] 2015-06-03 22:30
Had the same issue, I closed Visual Studio, opened the index.html file in Notepad ++ and changed the encoding to ' Encode in UTF without BOM', then run IONIC UPLOAD and all is fine. I know it's not a fix but it's a workaround until the issue is resolved. @thomas-tran @jbavari

**Comment by jbavari** [comment] 2015-06-05 17:03
@bradmartin @thomas-tran - Working on a fix now - going to just remove the BOM and save the file as is.

Would anyone be available to test it to make sure it doesnt cause any issues with Visual studio?

**Comment by bradmartin** [comment] 2015-06-05 17:55
I'll test it later today.

**Comment by squiso** [comment] 2015-06-06 08:03
@bradmartin - Thanks for the workaround! I haven't had any issues with Visual Studio.

**Comment by bradmartin** [comment] 2015-06-07 05:23
@jbavari no longer modifies the index.html file when VS is opened or closed. Thanks for the fix, saves me a minute or two when uploading.

**Comment by bradmartin** [comment] 2015-06-08 21:42
@jbavari This isn't working anymore.

**Comment by bradmartin** [comment] 2015-06-09 03:48
@jbavari - another issue with ionic upload.

![apos](https://cloud.githubusercontent.com/assets/6006148/8050294/6e7f55b0-0e30-11e5-8b83-02a7860f3bb3.JPG)

**Comment by bradmartin** [comment] 2015-06-09 03:48
This was after setting 'Encoding without BOM' via notepad ++ with VS closed. Since the work around you pushed a couple days ago quit working today.

**Comment by jbavari** [comment] 2015-06-30 23:29
@bradmartin In the screenshot you provided with `&apos;` - what was the original content?

I'll whip together a test to ensure that doesnt happen.

**Comment by bradmartin** [comment] 2015-07-01 00:12
@jbavari  - Not near the source code at the moment but it was either single quote or double quote, was just passing the state as a string. If that's what you're asking. If you need more details let me know.

**Comment by jbavari** [comment] 2015-07-01 00:24
@bradmartin It's all good. Looks to be a simple fix by adding `{ decodeEntities: false }` to the parser. Will have this patched in next version.

**Comment by jbavari** [comment] 2015-07-01 00:27
@bradmartin This should solve it - with test to verify :) 

https://github.com/driftyco/ionic-app-lib/commit/b757d3866176d531de7bb6806bbeb29882f6010a

**Comment by bradmartin** [comment] 2015-07-02 15:06
@jbavari - sorry for my ignorance. I'm using Ionic CLI 1.5.5, so will this fix be present or shipped with an update to the CLI? I just ran 'ionic upload' and all of my single quotes were modified to '&apos' .  Thanks for your help.

**Comment by jbavari** [comment] 2015-07-02 15:28
Yes, in the next release, this will be fixed.

@bradmartin Try out the beta version to see if that works: `npm install -g ionic@beta`

**Comment by nobosny** [comment] 2015-07-04 23:51
Hi, I just downloaded and updated my ionic-app-lib to the latest version, 0.3.2, I checked the code, and the "decodeEntities" fix is ok. But when I upload my ionic app to IonicView, it keeps changing my urls. I tried ionic@beta, and everything, but nothing seems to work.

**Comment by bradmartin** [comment] 2015-07-05 03:38
Yea I'm using beta and noticed there are still some odd issues.

The only fix I have is to open notepad ++ and change the encoding to 'UTF
without BOM' and save the file. Also, I close Visual Studio just to be
safe, it seems that when VS is open and I run 'ionic upload' it always
messes something up.

**Comment by nobosny** [comment] 2015-07-05 15:58
Thank you bradmartin, but I tried that too, and just when I try to upload, it changes my index.html, all my single quotes are changed to &apos;, and since I'm trying to embed a Google Map on my app, i'm using Content-Security-Policy and external google javascript files. I'm not able to test the app using IonicView.

**Comment by salbahra** [comment] 2015-12-09 10:13
I am still experiencing the same issue as @nobosny regarding the Content-Security-Policy issue. If there is anything I can provide to help please let me know.

Thank you!

System information:

```
Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.1.1
Ionic CLI Version: 1.7.11
Ionic App Lib Version: 0.6.5
ios-deploy version: 1.8.2 
ios-sim version: 4.1.1 
OS: Mac OS X El Capitan
Node Version: v0.12.7
Xcode version: Xcode 7.1.1 Build version 7B1005 
```

**Comment by mediastuttgart** [comment] 2015-12-28 08:47
hey,

still experiencing this issue with single quotes

````
 <a ng-click="foo('bar')">baz</a>
````
was changed to

````
 <a ng-click="foo(&apos;bar&apos;)">baz</a>
````

after running `ionic upload`

````
Your system information:

Editor: Sublime V3
Cordova CLI: 5.4.1
Gulp version:  CLI version 3.8.11
Gulp local:   Local version 3.9.0
Ionic Version: 1.2.1
Ionic CLI Version: 1.7.12
Ionic App Lib Version: 0.6.5
ios-deploy version: 1.8.3
ios-sim version: 5.0.4
OS: Mac OS X El Capitan
Node Version: v0.12.0
Xcode version: Xcode 7.1.1 Build version 7B1005
````

**Comment by deinerson1** [comment] 2016-04-04 02:11
I am experiencing the same issue as @nobosny regarding the Content-Security-Policy issue. If there is anything I can provide to help please let me know.

System information:
Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Version: 1.2.4-nightly-1917
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
OS: Distributor ID:	Ubuntu Description:	Ubuntu 15.10 
Node Version: v0.12.10

**Comment by qmarcos** [comment] 2016-06-09 16:45
@jbavari This issue is not solved... above is my ionic info, but I did some test and not only is not working with the spec/index.html file case, also with the[ Content-Security-Policy meta that is also referenced here](https://github.com/driftyco/ionic-cli/issues/562).

I've checked the upload.js code and it includes the fix, but the fix doesn't solve the problem.

With this bug seems that is not possible to use **ionic upload** to test apps with ionic view if you need a CSP or some special chars inside HTML attributes :_( 

Thanks in advance!

```
Cordova CLI: Not installed
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic Framework Version: 1.3.1
Ionic CLI Version: 1.7.15
Ionic App Lib Version: 0.7.2
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v0.12.6
Xcode version: Not installed
```

**Comment by mlynch** [comment] 2016-06-09 17:47
We are taking a look for new View updates. Thanks.

**Comment by qmarcos** [comment] 2016-06-09 17:50
Hi @mlynch it sounds fantastic to me 👍

**Comment by GeekG1rl** [comment] 2016-06-22 16:19
@mlynch Any updates on this? Getting pretty desperate here 😢

**Comment by tlancina** [comment] 2016-06-23 22:59
This should be fixed in the latest version of the CLI. Let us know if you're still having issues, thanks!

**Closed by tlancina** 2016-06-23 22:59 UTC

**Comment by qmarcos** [comment] 2016-06-27 07:06
I'll give it a try in the following days, keep you informed 👍
