### ISSUE TITLE
run `ionic start MyIonic2Project tutorial --v2` failure

### ISSUE THREAD

**Issue by h87kg** [driftyco/ionic-cli#1199] opened 2016-07-22 22:17 UTC
```
Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
Error with start Error: connect ECONNREFUSED 192.30.252.131:443
    at Object.exports._errnoException (util.js:1007:11)
    at exports._exceptionWithHostPort (util.js:1030:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
Error Initializing app: Error: connect ECONNREFUSED 192.30.252.131:443
 Error: connect ECONNREFUSED 192.30.252.131:443
    at Object.exports._errnoException (util.js:1007:11)
    at exports._exceptionWithHostPort (util.js:1030:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
Caught exception:
 Error: connect ECONNREFUSED 192.30.252.131:443
    at Object.exports._errnoException (util.js:1007:11)
    at exports._exceptionWithHostPort (util.js:1030:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
```

**Comment by raelbr** [comment] 2016-07-25 14:04
Same here, but with a different error message:

Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic2-starter-tabs/archive/master.zip
[=============================]  100%  0.0s
Installing npm packages...
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

---

I'm following this tutorial:
http://ionicframework.com/docs/v2/getting-started/installation/

Node version: 6.2.1

Any thoughts?

Thanks in advance.

**Comment by raelbr** [comment] 2016-07-25 17:29
**SOLVED** for me.... I found the answer in this link: https://github.com/angular/angular/issues/8483

The problem was in my git registry. To fix it, just run: `npm set registry http://registry.npmjs.org solved the problem.`

**Comment by jthoms1** [comment] 2016-07-25 20:52
This is a duplicate of #1013.

I am closing this issue. It has been kind of a catch all for npm install issues from ionic start. If you are having issues please try running with the verbose flag.

sudo ionic start cutePuppyPics --v2 --verbose

This should provide more insight into what is happening. In most cases it will report issues with network connectivity or permissions issues. If this is not the case please open an issue with your ionic info output.

**Closed by jthoms1** 2016-07-25 20:52 UTC

**Comment by Noble-Shiva** [comment] 2017-03-15 07:11
@raelbr ,

Same issue i have faced, ECONNRESET,
I didn't get a solution with that.

Do u have any other solutions
