### ISSUE TITLE
Error Initializing app: There was an error with the spawned command: npminstall

### ISSUE THREAD

**Issue by jeremysmartin399** [driftyco/ionic-cli#1476] opened 2016-10-05 19:21 UTC
When trying to start a blank project, I receive a "Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall" error. I've searched the forums, updated git, reinstalled git, and updated node.
```
E:\Projects\PCVApp\sandbox\map1>ionic start ionic-maps blank
Creating Ionic app in folder E:\Projects\PCVApp\sandbox\map1\ionic-maps based on
 blank project
Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic-starter-blank/archive/master.zip
[=============================]  100%  0.0s
Installing npm packages...
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

E:\Projects\PCVApp\sandbox\map1>ionic info

Your system information:

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS: Windows 7 SP1
Node Version: v4.5.0

```

**Comment by varunet** [comment] 2016-10-05 21:30
I have the same issue

**Ionic Info**
Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS: Windows 7 SP1
Node Version: v6.7.0

**Comment by Dinesh-Singh-Bhati** [comment] 2016-10-07 06:51
Same issue.

System Information:

Cordova CLI: 6.3.1
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS: Windows 7 SP1
Node Version: v6.7.0

**Comment by brunogayet** [comment] 2016-10-07 12:37
I have the same issue!

Cordova CLI: 6.3.1
Ionic CLI Version: 2.1.0-beta.3
Ionic App Lib Version: 2.1.0-beta.1
OS: Windows 7 SP1
Node Version: v5.8.0
Npm Version: 3.7.3

Already uninstalled, installed again, run the command "npm cache clear" and "clean cache", manually deleted the "npm-cache" directory and still got the same error.

Can someone help me?

**Comment by jgw96** [comment] 2016-10-12 01:36
Hello all! I am going to close this one as a duplicate of https://github.com/driftyco/ionic-cli/issues/1491.

**Closed by jgw96** 2016-10-12 01:36 UTC
