### ISSUE TITLE
ionic start not finishing build command when choosing sidemenu template

### ISSUE THREAD

**Issue by shotbyabel** [driftyco/ionic-cli#921] opened 2016-04-11 05:30 UTC
I just ran 3 test..by `ionic start` 3 different apps I determined that my issue only seems to pertain when I build with the `sidemenu` template. 

for example when I run this..

`ionic start myApp sidemenu --v2 --ts`

The process never finishes... 

```
Creating Ionic app in folder /Users/ahernandez/code/MOBILE_DEV/myApp based on sidemenu project
Downloading: https://github.com/driftyco/ionic2-app-base/archive/typescript.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic2-starter-sidemenu/archive/typescript.zip
[=============================]  100%  0.0s
```

I eventually Ctrl C out of the process and open up the app in my text editor but folders and dependencies are missing and I get such errors when I try to either...

`ionic genera page` and or `ionic serve`
```

WARN: ionic.config.js has been deprecated, you can remove it.
WARN: No node_modules directory found, do you need to run npm install?
WARN: ionic.config.js has been deprecated, you can remove it.

No ionic-angular package found, do you have Ionic installed? (CLI v2.0.0-beta.24)

Your system information:

Cordova CLI: 6.1.1
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
ios-deploy version: 1.8.5
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v5.10.1
Xcode version: Xcode 7.3 Build version 7D175

```

```
$ ionic serve
WARN: ionic.config.js has been deprecated, you can remove it.
WARN: No node_modules directory found, do you need to run npm install?
WARN: ionic.config.js has been deprecated, you can remove it.

Multiple addresses available.
Please select which address to use by entering its number from the list below:
 1) 192.168.0.2 (en1)
 2) localhost
Address Selection:  1
Selected address: 192.168.0.2
"www" directory cannot be found. Please make sure the working directory is an Ionic project.
There was an error serving your Ionic application: "www" directory cannot be found. Please make sure the working directory is an Ionic project.

```

**Any ideas why sidemenu is not well liked? :D **

Thank you All

**Comment by HuemanF** [comment] 2016-04-11 17:25
same for me

**Comment by ophedian** [comment] 2016-04-12 22:40
I have the same exact problem !!!

Additional noticed issues:
1:  The "app" folder is not created.  
2:  In the temporary folder app/pages/list  --> it is missing the list.ts file.

**Comment by michael-lins** [comment] 2016-04-23 05:08
@shotbyabel Try calling it with **sudo**... ionic start uses npminstall internally and when in Mac OS X you need it to be called by sudo. Worked for me but it has side effects: the project folder is created root owned, so you'll have to sudo others commands like ionic serve, etc.

**Comment by tlancina** [comment] 2016-04-25 16:30
Hey thanks for the issue, this should be fixed in beta.25, it was caused by an empty Sass file in sidemenu, which the unzip library we were using didn't like.

**Closed by tlancina** 2016-04-25 16:30 UTC
Labels: v2
