### ISSUE TITLE
There was an error with the spawned command: npminstall

### ISSUE THREAD

**Issue by rafaelcmrj** [driftyco/ionic-cli#1198] opened 2016-07-22 20:19 UTC
ionic start ProjectTest tabs
Creating Ionic app in folder /Library/WebServer/Documents/ionic-apps/ProjectTest based on tabs project
Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic-starter-tabs/archive/master.zip
[=============================]  100%  0.0s
Installing npm packages...
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined

**Comment by hebaothman** [comment] 2016-07-23 08:21
+1 here

**Comment by jthoms1** [comment] 2016-07-25 20:53
This is a duplicate of #1013.

I am closing this issue. It has been kind of a catch all for npm install issues from ionic start. If you are having issues please try running with the verbose flag.

sudo ionic start cutePuppyPics --v2 --verbose

This should provide more insight into what is happening. In most cases it will report issues with network connectivity or permissions issues. If this is not the case please open an issue with your ionic info output.

**Closed by jthoms1** 2016-07-25 20:53 UTC

**Comment by anil-ninja** [comment] 2016-09-20 10:06
Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
Error with start Error: getaddrinfo ENOTFOUND codeload.github.com
    at errnoException (dns.js:44:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:94:26)
Error Initializing app: Error: getaddrinfo ENOTFOUND codeload.github.com
 Error: getaddrinfo ENOTFOUND codeload.github.com
    at errnoException (dns.js:44:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:94:26)
Caught exception:
 Error: getaddrinfo ENOTFOUND codeload.github.com
    at errnoException (dns.js:44:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:94:26)

**Comment by anil-ninja** [comment] 2016-09-20 10:07
after running
sudo ionic start cutePuppyPics --v2 --verbose
