### ISSUE TITLE
ionic serve does not close properly

### ISSUE THREAD

**Issue by weslleih** [driftyco/ionic-cli#1452] opened 2016-10-02 09:37 UTC
"c" or "quit" is not ending the node process and when I try to start another serve, this causes problems.

The log of two processes at the same time
```
Running 'serve:before' npm script before serve
> ionic-hello-world@ watch D:\Documents\Projetos\facul\facul
> ionic-app-scripts watch
[05:24:50]  ionic-app-scripts 0.0.23
[05:24:50]  watch started ...
[05:24:50]  build dev started ...
[05:24:50]  clean started ...
[05:24:50]  clean finished in 33 ms
[05:24:50]  copy started ...
[05:24:50]  typescript compiler started ...
[05:24:50]  build dev failed:  Build failed

[05:24:50]

[05:24:50]  watch ready in 882 ms
[05:24:50]  lint started ...
Running live reload server: http://localhost:35729
Watching: www/**/*, !www/lib/**/*, !www/**/*.map
√ Running dev server:  http://localhost:8100
Ionic server commands, enter:
  restart or r to restart the client app from the root
  goto or g and a url to have the app navigate to the given url
  consolelogs or c to enable/disable console log output
  serverlogs or s to enable/disable server log output
  quit or q to shutdown the server and exit

ionic $ [05:24:52]  copy finished in 2.24 s
[05:24:56]  lint finished in 5.43 s
```

ionic info
```
Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS:
Node Version: v6.7.0
//OS is Windows 10
```

I tried to reinstall without success, but ctrl+c closes the processes properly.

**Comment by ahmedelgendy** [comment] 2016-10-09 17:15
+1

**Comment by jgw96** [comment] 2016-10-12 01:51
Hello all! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic-app-scripts/issues/74. Thanks!

**Closed by jgw96** 2016-10-12 01:51 UTC
