### ISSUE TITLE
Command start with sidemnu template does not work

### ISSUE THREAD

**Issue by altafit-git** [driftyco/ionic-cli#1225] opened 2016-08-01 10:56 UTC
installing npm packages...
Error with start undefined
Error initializing app: There was an error with spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined

Ionic installed by "npm install ionic@beta"

**Comment by brunoosilva** [comment] 2016-08-06 19:08
Problem resolved!

Run command: `sudo ionic start cutePuppyPics --v2`

See more: https://github.com/driftyco/ionic-cli/issues/1013

**Comment by jgw96** [comment] 2016-08-08 18:55
Hello! Thanks for opening an issue with us. I am going to be closing this issue as a duplicate of #1013. Thanks for using Ionic!

**Closed by jgw96** 2016-08-08 18:55 UTC
