### ISSUE TITLE
Unable to see any errors on terminal Cli 2.1.12

### ISSUE THREAD

**Issue by DhruvGupta5** [driftyco/ionic-cli#1695] opened 2016-11-20 08:45 UTC
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/driftyco/ionic-app-scripts

#### Short description of the problem:
updated the cli via ionic@latest install
since then all the console.log and syntax errors from the code have gone missing from terminal,
additionally on making changes to the .ts files the app wont load back on livereload.

#### What behavior are you expecting?
errors be displayed

**Steps to reproduce:**
1. update to latest ionic
2. ionic run android -l -c
3. use app and wont show any of the console.logs or code errors

```
insert any relevant code between the above and below backticks
```

**Post the output of `ionic info` below please**

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v6.9.1
Xcode version: Not installed

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by jigarsdev** [comment] 2016-11-21 04:41
+1

**Comment by danielabbatt** [comment] 2016-11-21 11:08
Yes this the main reason I'm not using this build is being unable to debug and no console messages either.

**Comment by biesbjerg** [comment] 2016-11-21 21:55
Also seeing (or not seeing:p) this. I guess app scripts swallows all output somehow?

**Comment by mburger81** [comment] 2016-11-30 14:19
:+1: We have the same problem, I don't know if the problem is app/scirpts or ionic framework. But with ionic cli 1.2.8 using last app/script the debug is working, the problem is with that version the live reload dosn't so developing is very very difficult for now.

**Comment by danielabbatt** [comment] 2016-12-01 11:41
@mburger81 - guessing you meant 2.1.8?

**Comment by mburger81** [comment] 2016-12-05 08:29
@danielabbatt yea sorry, naturally i meant 2.1.8 :+1: 
I tested new version 2.1.14 but problem is still there. Does someone know why that?

**Comment by riccardotreagles** [comment] 2016-12-06 15:18
+1

**Comment by jthoms1** [comment] 2016-12-07 04:37
Commit 68eb3e53f4b24775fe8957f1bb2f080cde88565c fixes the issue. This will be released this week.  If you would like the fix asap you can install `ionic@test` to get it now.

**Comment by mburger81** [comment] 2016-12-07 09:16
@jthoms1 I can not confirm that log is working now.
I installed versione **2.1.15** with **npm install ionic@test** and created a new project doing **ionic start ionic2-test  --v2**

After that I had to launch **ionic add platform android** which was removed in older versions and then I launch emulator doing **ionic emulate android -lc**. In versions before doing this added android platform automatic. So I think this could be an error.

The fact is doing all this emulater is started, live reload is working but there is no **console.log('my message')** on the shell where I launched the command.

So I think the problem is still here, or did I misunderstood something, and did it not in the correct way?

**Comment by tonirilix** [comment] 2016-12-07 17:23
Hi @jthoms1, I just made some tests in a clean project, I'm using RC.3 and used ionic@test (2.1.15). 
Live reload it's working well but logs are still not being shown.

**Comment by Mokto** [comment] 2016-12-08 16:14
Yes it prevents us from working on devices.

Thanks for your work.

**Comment by mburger81** [comment] 2016-12-09 06:44
I tested it on new release in test which is 2.1.16, but nothing changed, livereload works console.log doesn't

**Comment by mburger81** [comment] 2016-12-11 23:23
Version 2.1.17 is released, reading the changelog the bug should be closed. I'm out of office, can someone test if it works now?

https://github.com/driftyco/ionic-cli/blob/master/CHANGELOG.md

**Comment by jthoms1** [comment] 2016-12-12 15:14
@mburger81 that is correct the latest release has the fix for consolelogs.

`npm install -g ionic@latest`

**Comment by tonirilix** [comment] 2016-12-12 17:43
@mburger81 I think we both have the same problem so I'll review and let you know.

**Comment by tonirilix** [comment] 2016-12-13 03:08
These are the result and steps of the tests I made:

1. I updated ionic so when I run  `ionic --version` it throws `2.1.17`
2. I created a new app with `ionic start --v2 test2.1.17 tabs`
3. I executed `ionic run android -lc`
4. The log starts as follows:
```
The port  was taken on the host 192.168.1.84 - using port 8000 instead
The port  was taken on the host 192.168.1.84 - using port 8000 instead

> ionic-hello-world@ ionic:serve /Users/tonirilix/sandbox/ionic/test2.1.17
> ionic-app-scripts serve "--v2" "--runLivereload" "--isPlatformServe" "--consolelogs" "--livereload" "--address" "192.168.1.84" "--port" "8000" "--liveReloadPort" "8000" "--iscordovaserve" "--nobrowser"

[21:03:09]  ionic-app-scripts 0.0.45
[21:03:12]  watch started ...
[21:03:12]  build dev started ...

.
. After some time...
.

[21:03:40]  dev server running: http://192.168.1.84:8000/

.
. After more time...
.

[21:05:30]  console.log: Angular 2 is running in the development mode. Call enableProdMode() to enable the production
            mode.
[21:05:30]  console.warn: Native: tried calling StatusBar.styleDefault, but Cordova is not available. Make sure to
            include cordova.js or run in a device/simulator
[21:05:30]  console.warn: Native: tried calling Splashscreen.hide, but Cordova is not available. Make sure to include
            cordova.js or run in a device/simulator

```
5. As you can see it won't detect that's running inside a device.

_*Note: Livereload and consolelogs work fine but the cordova plugin won't be detected.*_

**Comment by hoodaajay99** [comment] 2016-12-14 10:43
>> Note: Livereload and consolelogs work fine but the cordova plugin won't be detected.

 --- for cordova plugin won't be detected

Solution here - https://github.com/driftyco/ionic-cli/issues/1701

Also Doesn't work for me.

**Comment by tonirilix** [comment] 2016-12-14 16:56
Thanks @hoodaajay99, I try it

**Comment by mburger81** [comment] 2016-12-15 08:20
Hi @tonirilix,
I tested it with `ionic@2.1.17` and I can confirm that the console.log is now working. But did you test it for the android emulator? In the native android emulator running `ionic emulate android -lc` or `ionic run android -lc` not having connect any device which is still run the emulator, the log DOESN'T work.

So now I'm a little bit confused, does the log never work in emulating version, or is the bug not closed. Can you test if it work for you in emulator or should it not work in your opinion?

**Closed** 2016-12-21 04:28 UTC

**Comment by mburger81** [comment] 2016-12-21 06:36
Hi @jthoms1 can I know why do you close this bug? Did you read my last post? I think there are still problems  or not?

**Comment by tonirilix** [comment] 2017-01-05 21:15
Hi @mburger81 
It's true. Console log will work on everything except for Android emulator. I tried with iOS emulator and it does work there.
