### ISSUE TITLE
ionic emulate android

### ISSUE THREAD

**Issue by zionnite** [driftyco/ionic-cli#804] opened 2016-03-02 09:43 UTC
please am very sorry if am recreating a topic or issue.

when i run my command line and type $ionic emulate android

it run and boot up my android emulator but yet generate an error about
 Expection in thread "main" Java.lang.RuntimeExpection......
 and so on 
and then display u might not have the required environment or OS

BUT I HAVE INSTALL THE TARGET 23...

Thank for ur time, i appreiate ur help

**Comment by zionnite** [comment] 2016-03-02 10:26
![picture](https://cloud.githubusercontent.com/assets/10984801/13457653/1a631bea-e01e-11e5-90cb-1c4d2aecdac0.png)

**Comment by tlancina** [comment] 2016-03-02 14:04
Not sure, do any of these help: http://stackoverflow.com/questions/32153915/ionic-build-android-error ? Sounds like the gradle zip file is possibly corrupted.

**Comment by flexzero** [comment] 2016-03-02 14:24
I faced similar issue before. actually it is the gradle error. it happens when the command "ionic emulate android" or "ionic run android" or "ionic build android". the problem is due to some error on internet connection the gradle zip downloaded by the the ionic-cli corrupts. and the corrupted zip is not the complete zip archive we are getting "java.util.zip.ZipException". The possible solution is manually delete the gradle zip and then re-run the "ionic emulate android".

**Comment by tlancina** [comment] 2016-04-04 22:28
Hey going to close this as it sounds like it's a gradle error, not an Ionic CLI one.

**Closed by tlancina** 2016-04-04 22:28 UTC
Labels: platform:android
