### ISSUE TITLE
Cordova@6.1.0 showing dependency warning

### ISSUE THREAD

**Issue by dylanvdmerwe** [driftyco/ionic-cli#874] opened 2016-03-29 08:10 UTC
I have just updated to the latest stable Cordova version (6.1.0) and am receiving the following:

> Your system information:
> 
> Cordova CLI: 6.1.0 (cordova-lib@undefined)
> Ionic Version: 2.0.0-beta.3
> Ionic CLI Version: 2.0.0-beta.22
> Ionic App Lib Version: 2.0.0-beta.12
> OS:
> Node Version: v5.7.0
> 
> 
> ******************************************************
>  Dependency warning - for the CLI to run correctly,
>  it is highly suggested to install/upgrade the following:
> 
>  Please install your Cordova CLI to version  >=4.2.0 `npm install -g cordova`
> 
> ******************************************************

**Comment by Artfloriani** [comment] 2016-03-30 15:30
Hey, this is a duplicate of https://github.com/driftyco/ionic-cli/issues/859. Take a look over there :)

**Comment by jgw96** [comment] 2016-05-02 19:02
As it seems this issue was fixed in cordova 6.1.1 i will be closing it. Thanks for using Ionic!

**Closed by jgw96** 2016-05-02 19:02 UTC
Labels: v2
