### ISSUE TITLE
Error with start undefined on node 5.2

### ISSUE THREAD

**Issue by Olgagr** [driftyco/ionic-cli#1073] opened 2016-06-14 09:21 UTC
When I try to create a new ionic 1 project on node 5.2.0 I get this error:

```
Installing npm packages...
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined 
```

When I switch to node 6.0.0 everything is working. I'm using ionic-cli in version 2.0.0-beta.29.

**Comment by jthoms1** [comment] 2016-06-14 21:34
I have verified and I can recreate this issue.  It appears that npm is failing silently.  Could you try running `npm install` within the new project directory after you see the failure?

**Comment by blackburnian** [comment] 2016-06-15 03:39
Here's what I get when I run npm install after the failed start:

```
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3
npm ERR! code E404

npm ERR! 404 no such package available : @angular/common
npm ERR! 404 
npm ERR! 404  '@angular/common' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jayuhasjr/Projects/cutePuppyPics/npm-debug.log
```

**Comment by blackburnian** [comment] 2016-06-15 03:42
npm-debu.log
[npm-debug.log.zip](https://github.com/driftyco/ionic-cli/files/315394/npm-debug.log.zip)

**Comment by Olgagr** [comment] 2016-06-15 06:04
@jthoms1 Hmm, when I do ```npm install``` within the new project directory after the failure, it just works.

**Comment by Olgagr** [comment] 2016-06-15 06:09
@blackburnian I had the same problem, not only with Ionic CLI but with installing Angular 2 packages. What helped me was updating npm version. However, I see that you are rather up-to-date. This is weird. Anyway, there was an issue on that in Angular 2 repo. Maybe, you should reopen it: https://github.com/angular/angular/issues/8464.

**Comment by 3dd13** [comment] 2016-06-26 10:52
there are few things you need to do to upgrade / update

1. upgrade nodejs

        brew upgrade node

2. upgrade npm

        npm install -g npm

3. set new registry

        npm set registry http://registry.npmjs.org

**Comment by jthoms1** [comment] 2016-07-06 20:47
Closing this as a duplicate of #1013.

**Closed by jthoms1** 2016-07-06 20:47 UTC
Labels: npm install

**Comment by omoaweonline** [comment] 2017-06-07 12:55
Can anyone help me with the below please.

$ ionic serve -l
[INFO] Starting server: --lab --l --port=8100 --p=8100 --livereload-port=35729 --r=35729 --address=0.0.0.0 - Ctrl+C to cancel
Error: Cannot find module '@ionic/app-scripts'
