### ISSUE TITLE
Non-whitespace before first tag.

### ISSUE THREAD

**Issue by yolofy** [driftyco/ionic-cli#1244] opened 2016-08-05 08:37 UTC
When I run the command: ionic run android
I get the following error:

```
Error: Non-whitespace before first tag.
Line: 0
Column: 1
Char:


Caught exception:
 undefined

Mind letting us know? https://github.com/driftyco/ionic-cli/issues
```
It would be nice if it told me which file to fix

**Comment by yolofy** [comment] 2016-08-05 08:46
Deleting and reinstalling all node_modules, plugins, and platforms solved the problem for me.

**Comment by jgw96** [comment] 2016-08-05 22:11
Hello all!  As this seems to have been an issue with your local setup and not the ionic cli I will be closing this issue for now. Thanks for using Ionic!

**Closed by jgw96** 2016-08-05 22:11 UTC

**Comment by agusdutra** [comment] 2017-12-05 19:37
I'm having this issue right now with the last version .
I deleted all node_modules, reinstaled it, but it keeps throwing that error.

I can run` ionic serve` and it works fine.
But if I run commands to build android or ios like : 
`ionic cordova platform add android `
`ionic cordova prepare android`
`ionic cordova run android`

I get this error: 

```
Error: Non-whitespace before first tag.
Line: 0
Column: 1
Char:
    at error (C:\Users\gecos\AppData\Roaming\npm\node_modules\ionic\node_modules\sax\lib\sax.js:666:10)
    at strictFail (C:\Users\gecos\AppData\Roaming\npm\node_modules\ionic\node_modules\sax\lib\sax.js:692:7)
    at beginWhiteSpace (C:\Users\gecos\AppData\Roaming\npm\node_modules\ionic\node_modules\sax\lib\sax.js:965:7)
    at SAXParser.write (C:\Users\gecos\AppData\Roaming\npm\node_modules\ionic\node_modules\sax\lib\sax.js:1006:11)
    at XMLParser.feed (C:\Users\gecos\AppData\Roaming\npm\node_modules\ionic\node_modules\elementtree\lib\parsers\sax.js:48:15)
    at ElementTree.parse (C:\Users\gecos\AppData\Roaming\npm\node_modules\ionic\node_modules\elementtree\lib\elementtree.js:271:10)
    at Object.parse (C:\Users\gecos\AppData\Roaming\npm\node_modules\ionic\node_modules\elementtree\lib\elementtree.js:584:8)
    at Function.<anonymous> (C:\Users\gecos\AppData\Roaming\npm\node_modules\ionic\node_modules\@ionic\cli-utils\lib\cordova\config.js:35:28)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\gecos\AppData\Roaming\npm\node_modules\ionic\node_modules\tslib\tslib.js:100:62)
```

**Comment by dwieeb** [comment] 2017-12-08 19:31
I'm guessing there's an xml syntax error in your `config.xml` file.

**Comment by agusdutra** [comment] 2017-12-11 14:21
This is my config.xml, 
I never touched this file. 
I created the project with the CLI and tried to run the commands I listed before.

```xml
<?xml version='1.0' encoding='utf-8'?>
<widget id="io.ionic.starter" version="0.0.1" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>proj</name>
    <description>An awesome Ionic/Cordova app.</description>
    <author email="hi@ionicframework" href="http://ionicframework.com/">Ionic Framework Team</author>
    <content src="index.html" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <preference name="ScrollEnabled" value="false" />
    <preference name="android-minSdkVersion" value="16" />
    <preference name="BackupWebStorage" value="none" />
    <preference name="SplashMaintainAspectRatio" value="true" />
    <preference name="FadeSplashScreenDuration" value="300" />
    <preference name="SplashShowOnlyFirstTime" value="false" />
    <preference name="SplashScreen" value="screen" />
    <preference name="SplashScreenDelay" value="3000" />
    <platform name="android">
        <allow-intent href="market:*" />
        <icon density="ldpi" src="resources/android/icon/drawable-ldpi-icon.png" />
        <icon density="mdpi" src="resources/android/icon/drawable-mdpi-icon.png" />
        <icon density="hdpi" src="resources/android/icon/drawable-hdpi-icon.png" />
        <icon density="xhdpi" src="resources/android/icon/drawable-xhdpi-icon.png" />
        <icon density="xxhdpi" src="resources/android/icon/drawable-xxhdpi-icon.png" />
        <icon density="xxxhdpi" src="resources/android/icon/drawable-xxxhdpi-icon.png" />
        <splash density="land-ldpi" src="resources/android/splash/drawable-land-ldpi-screen.png" />
        <splash density="land-mdpi" src="resources/android/splash/drawable-land-mdpi-screen.png" />
        <splash density="land-hdpi" src="resources/android/splash/drawable-land-hdpi-screen.png" />
        <splash density="land-xhdpi" src="resources/android/splash/drawable-land-xhdpi-screen.png" />
        <splash density="land-xxhdpi" src="resources/android/splash/drawable-land-xxhdpi-screen.png" />
        <splash density="land-xxxhdpi" src="resources/android/splash/drawable-land-xxxhdpi-screen.png" />
        <splash density="port-ldpi" src="resources/android/splash/drawable-port-ldpi-screen.png" />
        <splash density="port-mdpi" src="resources/android/splash/drawable-port-mdpi-screen.png" />
        <splash density="port-hdpi" src="resources/android/splash/drawable-port-hdpi-screen.png" />
        <splash density="port-xhdpi" src="resources/android/splash/drawable-port-xhdpi-screen.png" />
        <splash density="port-xxhdpi" src="resources/android/splash/drawable-port-xxhdpi-screen.png" />
        <splash density="port-xxxhdpi" src="resources/android/splash/drawable-port-xxxhdpi-screen.png" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
        <icon height="57" src="resources/ios/icon/icon.png" width="57" />
        <icon height="114" src="resources/ios/icon/icon@2x.png" width="114" />
        <icon height="40" src="resources/ios/icon/icon-40.png" width="40" />
        <icon height="80" src="resources/ios/icon/icon-40@2x.png" width="80" />
        <icon height="120" src="resources/ios/icon/icon-40@3x.png" width="120" />
        <icon height="50" src="resources/ios/icon/icon-50.png" width="50" />
        <icon height="100" src="resources/ios/icon/icon-50@2x.png" width="100" />
        <icon height="60" src="resources/ios/icon/icon-60.png" width="60" />
        <icon height="120" src="resources/ios/icon/icon-60@2x.png" width="120" />
        <icon height="180" src="resources/ios/icon/icon-60@3x.png" width="180" />
        <icon height="72" src="resources/ios/icon/icon-72.png" width="72" />
        <icon height="144" src="resources/ios/icon/icon-72@2x.png" width="144" />
        <icon height="76" src="resources/ios/icon/icon-76.png" width="76" />
        <icon height="152" src="resources/ios/icon/icon-76@2x.png" width="152" />
        <icon height="167" src="resources/ios/icon/icon-83.5@2x.png" width="167" />
        <icon height="29" src="resources/ios/icon/icon-small.png" width="29" />
        <icon height="58" src="resources/ios/icon/icon-small@2x.png" width="58" />
        <icon height="87" src="resources/ios/icon/icon-small@3x.png" width="87" />
        <icon height="1024" src="resources/ios/icon/icon-1024.png" width="1024" />
        <splash height="1136" src="resources/ios/splash/Default-568h@2x~iphone.png" width="640" />
        <splash height="1334" src="resources/ios/splash/Default-667h.png" width="750" />
        <splash height="2208" src="resources/ios/splash/Default-736h.png" width="1242" />
        <splash height="1242" src="resources/ios/splash/Default-Landscape-736h.png" width="2208" />
        <splash height="1536" src="resources/ios/splash/Default-Landscape@2x~ipad.png" width="2048" />
        <splash height="2048" src="resources/ios/splash/Default-Landscape@~ipadpro.png" width="2732" />
        <splash height="768" src="resources/ios/splash/Default-Landscape~ipad.png" width="1024" />
        <splash height="2048" src="resources/ios/splash/Default-Portrait@2x~ipad.png" width="1536" />
        <splash height="2732" src="resources/ios/splash/Default-Portrait@~ipadpro.png" width="2048" />
        <splash height="1024" src="resources/ios/splash/Default-Portrait~ipad.png" width="768" />
        <splash height="960" src="resources/ios/splash/Default@2x~iphone.png" width="640" />
        <splash height="480" src="resources/ios/splash/Default~iphone.png" width="320" />
        <splash height="2732" src="resources/ios/splash/Default@2x~universal~anyany.png" width="2732" />
    </platform>
    <engine name="browser" spec="5.0.1" />
    <plugin name="ionic-plugin-keyboard" spec="^2.2.1" />
    <plugin name="cordova-plugin-whitelist" spec="^1.3.1" />
    <plugin name="cordova-plugin-device" spec="^1.1.4" />
    <plugin name="cordova-plugin-splashscreen" spec="^4.0.3" />
    <plugin name="cordova-plugin-ionic-webview" spec="^1.1.11" />
</widget>
```

**Comment by Azadehkhojandi** [comment] 2017-12-25 00:51
I had same issue and fixed mine by running following commands 
ionic cordova platform rm android 
ionic cordova platform add android 
ionic cordova build android
ionic cordova emulate android

**Comment by degroundshaker** [comment] 2018-03-18 07:43
I faced this issue when my PC went off all of sudden due to power cut. 

At first, I kept trying _adding/removing platforms_ & _Node Modules._ 
Later I found out that my config.xml file has been corrupted, which was then causing the same error.

I **restored my config.xml** file and things were back on right track.

Cheers!

**Comment by jackeeeeeee** [comment] 2018-03-19 10:24
check your config.xml

**Comment by aBirds1** [comment] 2018-05-14 07:06
Can i get Instructions on how to fix the config.xml

**Comment by dwieeb** [comment] 2018-05-14 17:49
These XML errors all include the line number and column number at which the error occurred. Just look in `config.xml` at the line and column it says and you should see the error. Here's a primer on XML: https://www.tutorialspoint.com/xml/xml_syntax.htm

**Comment by cjnatan** [comment] 2018-05-30 08:31
@aBirds1 I had a similar issue and my main application code was intact(Using an external tool, I compared the folders:: src, resources and app root with my git repo.). 

As someone mentioned above, it happened when my VM crashed unexpectedly (brought to you by Microsoft's unexpected blue screens:)).

So, to resolve this, I deleted the following folders from my project(you could try deleting each folder at a time)::

**NOTE: if like me, you had to make quite a few changes in your android/ios gradle config to make certain native plugins work, I would suggest you take a backup of platforms folder before you delete it.**

1> node_modules
2> platforms
3> www
4> plugins

Then I executed::
1> npm install
2> ionic cordova platform add ios
3> ionic cordova platform add android
4> any additional steps you might need (potentially reinstalling specific plugins)
5> done.

Hope it helps someone.

**Comment by KiengKnot** [comment] 2018-06-11 06:54
My case, there is a white space of `ion-icon`. So, I removed the white space and the problem is solved<br>
`<ion-icon ios="ios -more" md="md -more"></ion-icon>`
However, the error is only occurred on ios device only.

I hope, this solution can give you a hint to your problem.

**Comment by pradeepdsmk** [comment] 2018-06-14 13:11
If using git, just checkout config.xml. Most editors offer 'Revert Modifications' under git options/menu

**Comment by Cperbony** [comment] 2018-11-19 00:56
For me, only need to check if any whitespace at begin or the end of the config.xml file.
removed and it works!
I hope it helps.

**Comment by mukund248** [comment] 2019-03-30 06:39
try
 ionic integrations enable cordova --add 
command

**Comment by Marktaylor399** [comment] 2019-08-03 10:46
yeah i am facing that issue too due to power cut

**Comment by GonzaloUNAB2018** [comment] 2019-08-18 16:19
i was an error in my config.xml... it was deleted for any reason... restore it and every thing is ok!
