### ISSUE TITLE
ionic apps do not run in 4.x android platforms

### ISSUE THREAD

**Issue by rsa408** [driftyco/ionic-cli#507] opened 2015-06-25 12:32 UTC
After upgrading Nodejs and all other modules I can not run Ionic build apps in 4.x version of androids

it shows that application successful lunched but there is no any app installation on emulator or attached device. the same thing is in cordova

ionic info:

Cordova CLI: 5.1.1 Ionic Version: 1.0.0 Ionic CLI Version: 1.5.5 Ionic App Lib Version: 0.2.2 OS: Windows 7 SP1 Node Version: v0.12.5

Npm version { menu: '1.0.0', npm: '2.11.2', http_parser: '2.3', modules: '14', node: '0.12.5', openssl: '1.0.1o', uv: '1.6.1', v8: '3.28.71.19', zlib: '1.2.8' }

These commands  run successfuly but the application is not run in any 4.x ver of android devices or emulators;

C:\>ionic start test sidemenu
Creating Ionic app in folder C:\test based on sidemenu project
Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
[=============================]  100%  0.0s
Updated the hooks directory to have execute permissions
Update Config.xml
Initializing cordova project

Your Ionic project is ready to go! Some quick tips:

 * cd into your project: $ cd test

 * Setup this project to use Sass: ionic setup sass

 * Develop in the browser with live reload: ionic serve

 * Add a platform (ios or Android): ionic platform add ios [android]
   Note: iOS development requires OS X currently
   See the Android Platform Guide for full Android installation instructions:
   https://cordova.apache.org/docs/en/edge/guide_platforms_android_index.md.html

 * Build your app: ionic build <PLATFORM>

 * Simulate your app: ionic emulate <PLATFORM>

 * Run your app on a device: ionic run <PLATFORM>

 * Package an app using Ionic package service: ionic package <MODE> <PLATFORM>

For more help use ionic --help or ionic docs

Visit the Ionic docs: http://ionicframework.com/docs

New! Add push notifications to your Ionic app with Ionic Push (alpha)!
https://apps.ionic.io/signup
+---------------------------------------------------------+
+ New Ionic Updates for June 2015
+
+ The View App just landed. Preview your apps on any device
+ http://view.ionic.io
+
+ Invite anyone to preview and test your app
+ ionic share EMAIL
+
+ Generate splash screens and icons with ionic resource
+ http://ionicframework.com/blog/automating-icons-and-splash-screens/
+
+---------------------------------------------------------+

=============================================================================

C:\test>ionic platform add android
Updated the hooks directory to have execute permissions
Downloading Default Ionic Resources
Downloading: https://github.com/driftyco/ionic-default-resources/archive/master.
zip
[=============================]  100%  0.0s
Done adding default Ionic resources
Adding icons for platform: android

npm http GET https://registry.npmjs.org/cordova-android 
npm http 304 https://registry.npmjs.org/cordova-android
npm http GET https://registry.npmjs.org/cordova-android
npm http 304 https://registry.npmjs.org/cordova-android

Adding android project...
Creating Cordova project for the Android platform:
        Path: platforms\android
        Package: com.ionicframework.test723387
        Name: test
        Activity: MainActivity
        Android target: android-22

Copying template files...

Android project created with cordova-android@4.0.2
Running command: "C:\Program Files\nodejs2\node.exe" C:\test\hooks\after_prepare
\010_add_platform_class.js C:\test
add to body class: platform-android
Installing "com.ionic.keyboard" for android
Installing "cordova-plugin-console" for android
Installing "cordova-plugin-device" for android
Installing "cordova-plugin-splashscreen" for android
Installing "cordova-plugin-whitelist" for android
Saving platform to package.json file

=============================================================================

C:\test>ionic build android
Running command: "C:\Program Files\nodejs2\node.exe" C:\test\hooks\after_prepare\010_add_platform_class.js C:\test
add to body class: platform-android
Running command: cmd "/s /c "C:\test\platforms\android\cordova\build.bat""
ANDROID_HOME=D:\adt-bundle-windows-x86-20130219\SDK
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_20
Running: C:\test\platforms\android\gradlew cdvBuildDebug -b C:\test\platforms\android\build.gradle -Dorg.gradle.daemon=true
:preBuild
:compileDebugNdk
:preDebugBuild
:checkDebugManifest
:CordovaLib:compileLint
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugProguardFiles
:CordovaLib:preBuild
:CordovaLib:preDebugBuild
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugAidl
:CordovaLib:compileDebugRenderscript
:CordovaLib:generateDebugBuildConfig
:CordovaLib:generateDebugAssets UP-TO-DATE
:CordovaLib:mergeDebugAssets
:CordovaLib:generateDebugResValues
:CordovaLib:generateDebugResources
:CordovaLib:packageDebugResources
:CordovaLib:processDebugManifest
:CordovaLib:processDebugResources
:CordovaLib:generateDebugSources
:CordovaLib:compileDebugJavaNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:packageDebugJar
:CordovaLib:compileDebugNdk
:CordovaLib:packageDebugJniLibs UP-TO-DATE
:CordovaLib:packageDebugLocalJar UP-TO-DATE
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:bundleDebug
:prepareAndroidCordovaLibUnspecifiedDebugLibrary
:prepareDebugDependencies
:compileDebugAidl
:compileDebugRenderscript
:generateDebugBuildConfig
:generateDebugAssets UP-TO-DATE
:mergeDebugAssets
:generateDebugResValues
:generateDebugResources
:mergeDebugResources
:processDebugManifest
:processDebugResources
:generateDebugSources
:compileDebugJavaNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:preDexDebug
:dexDebug
:processDebugJavaRes UP-TO-DATE
:validateDebugSigning
:packageDebug
:zipalignDebug
:assembleDebug
:cdvBuildDebug

BUILD SUCCESSFUL

Total time: 44.838 secs
Built the following apk(s):
    C:\test\platforms\android\build\outputs\apk\android-debug.apk

=============================================================================

emulate on mydev android 4.1.2

=============================================================================
Running command: "C:\Program Files\nodejs2\node.exe" C:\test\hooks\after_prepare\010_add_platform_class.js C:\test
add to body class: platform-android
Running command: cmd "/s /c "C:\test\platforms\android\cordova\run.bat --emulator""
ANDROID_HOME=D:\adt-bundle-windows-x86-20130219\SDK
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_20
Running: C:\test\platforms\android\gradlew cdvBuildDebug -b C:\test\platforms\android\build.gradle -PcdvBuildArch=arm -Dorg.gradle.daemon=true
:preBuild
:compileDebugNdk UP-TO-DATE
:preDebugBuild
:checkDebugManifest
:CordovaLib:compileLint
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugProguardFiles UP-TO-DATE
:CordovaLib:preBuild
:CordovaLib:preDebugBuild
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugAidl UP-TO-DATE
:CordovaLib:compileDebugRenderscript UP-TO-DATE
:CordovaLib:generateDebugBuildConfig UP-TO-DATE
:CordovaLib:generateDebugAssets UP-TO-DATE
:CordovaLib:mergeDebugAssets UP-TO-DATE
:CordovaLib:generateDebugResValues UP-TO-DATE
:CordovaLib:generateDebugResources UP-TO-DATE
:CordovaLib:packageDebugResources UP-TO-DATE
:CordovaLib:processDebugManifest UP-TO-DATE
:CordovaLib:processDebugResources UP-TO-DATE
:CordovaLib:generateDebugSources UP-TO-DATE
:CordovaLib:compileDebugJava UP-TO-DATE
:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:packageDebugJar UP-TO-DATE
:CordovaLib:compileDebugNdk UP-TO-DATE
:CordovaLib:packageDebugJniLibs UP-TO-DATE
:CordovaLib:packageDebugLocalJar UP-TO-DATE
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:bundleDebug UP-TO-DATE
:prepareAndroidCordovaLibUnspecifiedDebugLibrary UP-TO-DATE
:prepareDebugDependencies
:compileDebugAidl UP-TO-DATE
:compileDebugRenderscript UP-TO-DATE
:generateDebugBuildConfig UP-TO-DATE
:generateDebugAssets UP-TO-DATE
:mergeDebugAssets UP-TO-DATE
:generateDebugResValues UP-TO-DATE
:generateDebugResources UP-TO-DATE
:mergeDebugResources UP-TO-DATE
:processDebugManifest UP-TO-DATE
:processDebugResources UP-TO-DATE
:generateDebugSources UP-TO-DATE
:compileDebugJava UP-TO-DATE
:preDexDebug UP-TO-DATE
:dexDebug UP-TO-DATE
:processDebugJavaRes UP-TO-DATE
:validateDebugSigning
:packageDebug UP-TO-DATE
:zipalignDebug UP-TO-DATE
:assembleDebug UP-TO-DATE
:cdvBuildDebug UP-TO-DATE

BUILD SUCCESSFUL

Total time: 19.329 secs
Built the following apk(s):
    C:\test\platforms\android\build\outputs\apk\android-debug.apk
Installing app on emulator...
Using apk: C:\test\platforms\android\build\outputs\apk\android-debug.apk
Launching application...
LAUNCH SUCCESS

but there is no application installed or lunched

**Comment by nyrnzn** [comment] 2015-06-27 06:25
Facing same issue.

**Comment by jbavari** [comment] 2015-06-29 16:46
Closing. This is a duplicate of #441. It will be fixed in the next version of Cordova-android. 

Follow the official [cordova issue](https://issues.apache.org/jira/browse/CB-9080).

**Closed by jbavari** 2015-06-29 16:46 UTC
