### ISSUE TITLE
Error when starting new app with flag --ts

### ISSUE THREAD

**Issue by Siltor94** [driftyco/ionic-cli#1059] opened 2016-06-09 13:08 UTC
Hi, got this error : 

![error_ts](https://cloud.githubusercontent.com/assets/15343741/15930545/d921bef0-2e53-11e6-9f71-591883a012ee.png)
but it only happen when i use the --ts flag, it works really well otherwise.

There's my ionic config dunno if it can be useful.

![ionic_config](https://cloud.githubusercontent.com/assets/15343741/15930573/f48cd170-2e53-11e6-98ec-7398ab85b911.png)

**Comment by jthoms1** [comment] 2016-07-06 20:47
Closing this as a duplicate of #1013.

**Closed by jthoms1** 2016-07-06 20:47 UTC
Labels: npm install
