### ISSUE TITLE
ERR_UNKNOWN_URL_SCHEME on image src

### ISSUE THREAD

**Issue by loicfavory** [driftyco/ionic-cli#369] opened 2015-04-11 08:07 UTC
Since I added Crosswalk I can't access my pictures stored in Google Photos app.

Image path start with : content://com.google.android.apps.photos.content/0/

I added this line : 
`$compileProvider.imgSrcSanitizationWhitelist(/^\s*(https?|file|blob|cdvfile|content):|data:image\//);`

It was working fine with ionic, but since I added Crosswalk, I can't get it works anymore.

My Ionic info:
> ionic info

Your system information:

OS: Distributor ID:	Fedora Description:	Fedora release 21 (Twenty One) 
Node Version: v0.12.2
Cordova CLI: 4.3.0
Ionic CLI Version: 1.3.19

**Comment by jbavari** [comment] 2015-04-29 01:55
Please add the cordova whitelist plugin. That should solve this issue.

**Comment by agamemnus** [comment] 2015-06-10 01:23
I don't think this is related.

**Comment by agamemnus** [comment] 2015-06-11 22:36
I don't know if this might be a Crosswalk issue. But, some people got it to work, and one person got it to work after it not working -- but he didn't know how. The bug posting is here:

https://crosswalk-project.org/jira/browse/XWALK-4371

**Comment by agamemnus** [comment] 2015-06-12 08:25
I seem to be only having this problem with jpg files. Same with you, 
@loicfavory?

**Comment by loicfavory** [comment] 2015-06-12 13:42
@agamemnus 
No I didn't have this problem only with jpeg files (google fonts was breaking too for exemple)
But it's working now for me. 
First I used the fix of Cyptus : http://forum.ionicframework.com/t/crosswalk-integration-beta-in-ionic-cli-v1-3-2/15190/264
But now it's working without this fix. I don't know why...
I didn't install the whitelist plugin

**Comment by agamemnus** [comment] 2015-06-12 19:28
I found my particular issue (sort of).. the file was actually not present but giving the wrong error code. A less serious bug but still an issue.

**Comment by baleboy** [comment] 2015-08-19 10:58
I tried to reproduce this with the cordova crosswalk webview plugin, but couldn't. I followed the steps mentioned here: http://forum.ionicframework.com/t/crosswalk-integration-beta-in-ionic-cli-v1-3-2/15190/264 and did the following:

- ionic start my_app
- cd my_app/
- ionic platform add android
- ionic plugin add cordova-plugin-crosswalk-webview
- ionic run android

I selected the "Chat" tab and the avatar images are loaded fine. But is this enough to say that the problem is gone?

**Comment by jgw96** [comment] 2016-05-02 20:53
Hello all! Are you all still having this issue with the latest version of the ionic-cli? Thanks!

**Comment by agamemnus** [comment] 2016-05-02 21:36
This seems to be an issue with Cordova basically, and things like Android expansion files.. the default whitelist plugin does not like Android expansion files and a lot of other things, too.

**Comment by jgw96** [comment] 2016-05-03 14:55
@agamemnus ahh OK. Since this is more of an issue with the whitelist plugin and not the Ionic cli I will be closing this issue for now. Thanks for using Ionic!

**Closed by jgw96** 2016-05-03 14:55 UTC
Labels: needs_reply
