### ISSUE TITLE
Generate Resources for Windows / WP Platform

### ISSUE THREAD

**Issue by ghenry22** [driftyco/ionic-cli#628] opened 2015-10-23 00:49 UTC
It would be great to be able to generate Windows and Windows Phone resources from the command line when you have those platforms added.  These are the image sizes for icons and splash screen to go into the config.xml, visual studio 2015 with Tools for Apache Cordova sets these sizes up so Ionic should be able to do the same from the CLI.  I am happy to test generation if you can incorporate this.

Icons

    <platform name="windows">
    <icon src="res/icons/windows/Square150x150Logo.scale-100.png" width="150" height="150" />
    <icon src="res/icons/windows/Square150x150Logo.scale-240.png" width="360" height="360" />
    <icon src="res/icons/windows/Square30x30Logo.scale-100.png" width="30" height="30" />
    <icon src="res/icons/windows/Square310x310Logo.scale-100.png" width="310" height="310" />
    <icon src="res/icons/windows/Square44x44Logo.scale-240.png" width="106" height="106" />
    <icon src="res/icons/windows/Square70x70Logo.scale-100.png" width="70" height="70" />
    <icon src="res/icons/windows/Square71x71Logo.scale-240.png" width="170" height="170" />
    <icon src="res/icons/windows/StoreLogo.scale-100.png" width="50" height="50" />
    <icon src="res/icons/windows/StoreLogo.scale-240.png" width="120" height="120" />
    <icon src="res/icons/windows/Wide310x150Logo.scale-100.png" width="310" height="150" />
    <icon src="res/icons/windows/Wide310x150Logo.scale-240.png" width="744" height="360" />
    </platform>
    <platform name="wp8">
    <icon src="res/icons/wp8/ApplicationIcon.png" width="62" height="62" />
    <icon src="res/icons/wp8/Background.png" width="173" height="173" />
    </platform>

Splashscreens

    <platform name="windows">
    <splash src="res/screens/windows/SplashScreen.scale-100.png" width="620" height="300" />
    <splash src="res/screens/windows/SplashScreen.scale-240.png" width="1152" height="1920" />
    <splash src="res/screens/windows/SplashScreenPhone.scale-240.png" width="1152" height="1920" />
    </platform>
    <platform name="wp8">
    <splash src="res/screens/wp8/SplashScreenImage.jpg" width="480" height="800" />
    </platform>

**Comment by ArnaudSpanneut** [comment] 2015-10-30 14:25
+1

**Comment by svdoever** [comment] 2015-11-28 12:04
+1 as well... ionic is getting strong in the tooling arround cordova, even if not using the ionicframework for client side rendering. So please extend support for the additional things other that ionicframework to all other platform targets as described in https://cordova.apache.org/docs/en/5.4.0/guide/support/index.html. Eventually the money will be in ionicplatform not ionicframework....

**Comment by mvodas** [comment] 2016-04-14 19:07
+1

**Comment by lempere** [comment] 2016-04-29 07:44
+1
Meanwhile you can use https://blogs.windows.com/buildingapps/2016/02/15/uwp-tile-generator-extension-for-visual-studio/

**Comment by georgegoncalo** [comment] 2016-04-29 15:54
+1

**Comment by ahoehne** [comment] 2016-05-05 13:43
+1

**Comment by NiltonFelicio** [comment] 2016-05-31 03:23
+1

**Comment by Artfloriani** [comment] 2016-06-15 15:23
+1

**Comment by Daforest** [comment] 2016-06-17 07:40
+1

**Comment by Ponsen** [comment] 2016-07-08 15:13
+1

**Comment by jgw96** [comment] 2016-07-12 20:32
Hello all, i am going to be closing this issue as a duplicate of https://github.com/driftyco/ionic-cli/issues/913. Thanks for using Ionic!

**Closed by jgw96** 2016-07-12 20:32 UTC
Labels: P4: Nice to have

**Comment by ghenry22** [comment] 2016-07-13 02:15
actually given the order they were logged in #913 is a duplicate of this issue.  But regardless as the windows platform is officially supported as part of ionic2 required resources for the windows platform should be generated in the same manner as ios or android which are also supported platforms.
