### ISSUE TITLE
v3-beta7: `ionic cordova run android` without adding platform first fails

### ISSUE THREAD

**Issue by piotrowski** [driftyco/ionic-cli#2093] opened 2017-04-13 10:51 UTC
#### What version of the CLI are you using? Output of `ionic --version`

3.0.0-beta7

#### Short description of the problem:

Calling `ionic cordova run android` without adding platform first fails:

```
> ionic cordova run android
✔ Installing the platform: cordova platform add android - done!
\ Installing the project plugins: cordova plugin add --save <plugin> { Error
    at FatalException.Exception (C:\Users\Jan\Documents\cliBeta7\node_modules\@ionic\cli-utils\dist\lib\errors.js:8:23)
    at FatalException (C:\Users\Jan\Documents\cliBeta7\node_modules\@ionic\cli-utils\dist\lib\errors.js:17:9)
    at Shell.<anonymous> (C:\Users\Jan\Documents\cliBeta7\node_modules\@ionic\cli-utils\dist\lib\shell.js:37:27)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\Jan\Documents\cliBeta7\node_modules\@ionic\cli-utils\dist\lib\shell.js:5:65)
    at process._tickCallback (internal/process/next_tick.js:109:7) name: 'Exception', exitCode: 127 }
```

#### What behavior are you expecting?

Error message that I should add a platform first OR automatically adds platform, then runs project on platform.

**Steps to reproduce:**
1. Install the v3-beta7 CLI
2. Start project, go into directory
3. Execute `ionic cordova run android`

**Post the output of `ionic info` below please**

```
  Your system information:
    Cordova CLI: Not installed
    Ionic Framework Version: 3.0.1
    Ionic CLI Version: 3.0.0-beta7
    ios-deploy version: Not installed
    ios-sim version: Not installed
    OS: Windows 10
    Node Version: v7.9.0
    Xcode version: Not installed
```

**Comment by dwieeb** [comment] 2017-04-13 22:37
I am not able to reproduce this with the given steps. I see that it's erroring with a status code of 127, which generally means the command being executed doesn't exist. This is strange. Perhaps one of the plugins is running a command that doesn't exist on your computer?

**Comment by piotrowski** [comment] 2017-04-14 08:17
I'm on Windows 10.

I redid all the steps, fresh beta7 install and then:

1. `ionic start`
2. Go to created directory
3. `ionic cordova run android`

Here is the complete output:

```
PS C:\Users\Jan\Documents> ionic version
3.0.0-beta7
PS C:\Users\Jan\Documents> ionic start
? What would you like to name your project: cliBeta7_3
? What starter would you like to use: blank
✔ Creating directory C:\Users\Jan\Documents\cliBeta7_3 - done!
✔ Downloading 'blank' starter template - done!
✔ Updating project dependencies to add required plugins - done!
✔ Creating configuration file for the new project - done!
✔ Executing: npm install within the newly created project directory - done!

♬ ♫ ♬ ♫  Your Ionic app is ready to go! ♬ ♫ ♬ ♫

Run your app in the browser (great for initial development):
  ionic serve

Run on a device or simulator:
  ionic cordova:run ios

Test and share your app on a device with the Ionic View app:
  http://view.ionic.io

? Link this app to your Ionic Dashboard to use tools like Ionic View? No

Go to your newly created project: cd C:\Users\Jan\Documents\cliBeta7_3

PS C:\Users\Jan\Documents> cd .\cliBeta7_3\
PS C:\Users\Jan\Documents\cliBeta7_3> ionic cordova run android
✔ Installing the platform: cordova platform add android - done!
\ Installing the project plugins: cordova plugin add --save <plugin> { Error
    at FatalException.Exception (C:\Users\Jan\Documents\cliBeta7_3\node_modules\@ionic\cli-utils\dist\lib\errors.js:8:23)
    at FatalException (C:\Users\Jan\Documents\cliBeta7_3\node_modules\@ionic\cli-utils\dist\lib\errors.js:17:9)
    at Shell.<anonymous> (C:\Users\Jan\Documents\cliBeta7_3\node_modules\@ionic\cli-utils\dist\lib\shell.js:37:27)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\Jan\Documents\cliBeta7_3\node_modules\@ionic\cli-utils\dist\lib\shell.js:5:65)
    at process._tickCallback (internal/process/next_tick.js:109:7) name: 'Exception', exitCode: 127 }

PS C:\Users\Jan\Documents\cliBeta7_3> ionic info

  Your system information:

    Cordova CLI: Not installed
    Ionic Framework Version: 3.0.1
    Ionic CLI Version: 3.0.0-beta7
    ios-deploy version: Not installed
    ios-sim version: Not installed
    OS: Windows 10
    Node Version: v7.9.0
    Xcode version: Not installed
```

**Comment by piotrowski** [comment] 2017-04-14 08:36
Probably related to #2094

**Comment by piotrowski** [comment] 2017-04-14 16:26
Yes, #2094 was caused by me not having Cordova installed (because I got a new node install for testing the CLI beta). There the error was just a bit short - but this one here it is really not helping at all because it doesn't even say that "Cordova is not installed". So this should probably handle missing Cordova in a different way.

**Comment by dwieeb** [comment] 2017-04-14 16:39
@piotrowski Thank you. I will be working on improving the messaging here to make it more clear.

**Comment by dwieeb** [comment] 2017-04-14 16:46
Closed in favor of https://github.com/driftyco/ionic-cli/issues/2103

**Closed by dwieeb** 2017-04-14 16:46 UTC
Labels: bug, v3
