### ISSUE TITLE
Ionic 2 : CLI "ionic resources" doesn't generate icon and splashscreen

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic-cli#1166] opened 2016-07-11 19:32 UTC
_From @pom421 on July 11, 2016 15:12_

#### Short description of the problem:

When i use the CLI and the command :

```sh
$ ionic resources
```

this is the answer : 
```
(node:8537) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Ionic icon and splash screen resources generator
 uploading icon.png...
 uploading splash.png...
```

When i inspect the generated code, well, it seems that nothing is generated :  

- config.xml is not modified 
- resources/android/icon (for example) is not updated with the new icons
- platforms/android/res/drawable-hdpi (for example) is not updated too

Same thing for iOS for icon and splash. 

**Which Ionic Version?** 1.x or 2.x

I use ionic 2.0.0-beta.32 on OS X 10.11.4 (El Capitan).
I have generated a tutorial project with the CLI like that : 

```sh
$ ionic start biblio tutorial --v2
```

_Copied from original issue: driftyco/ionic#7269_

**Comment by hugomosh** [comment] 2016-07-12 19:53
+1

**Comment by kabus202** [comment] 2016-07-13 05:20
+1

**Comment by mnasyrov** [comment] 2016-07-13 08:12
Is there any workaround to force generation of icon and splash resources?

**Comment by kabus202** [comment] 2016-07-13 09:16
U can try it with ionic1 cli

**Comment by hugomosh** [comment] 2016-07-13 18:12
For me it worked doing it with individually, i.e.
 ionic resources --icon

*Hugo Cardoza*

2016-07-13 4:16 GMT-05:00 kabbi <notifications@github.com>:

**Comment by kabus202** [comment] 2016-07-14 05:50
I found a workaround:

generate the splashscreen with ionic 1 CLI, then copy the resource folder to ionic2 project folder, and add this to config.xml


`<platform name="android">
        <splash density="land-ldpi" src="resources/android/splash/drawable-land-ldpi-screen.png" />
        <splash density="land-mdpi" src="resources/android/splash/drawable-land-mdpi-screen.png" />
        <splash density="land-hdpi" src="resources/android/splash/drawable-land-hdpi-screen.png" />
        <splash density="land-xhdpi" src="resources/android/splash/drawable-land-xhdpi-screen.png" />
        <splash density="land-xxhdpi" src="resources/android/splash/drawable-land-xxhdpi-screen.png" />
        <splash density="land-xxxhdpi" src="resources/android/splash/drawable-land-xxxhdpi-screen.png" />
        <splash density="port-ldpi" src="resources/android/splash/drawable-port-ldpi-screen.png" />
        <splash density="port-mdpi" src="resources/android/splash/drawable-port-mdpi-screen.png" />
        <splash density="port-hdpi" src="resources/android/splash/drawable-port-hdpi-screen.png" />
        <splash density="port-xhdpi" src="resources/android/splash/drawable-port-xhdpi-screen.png" />
        <splash density="port-xxhdpi" src="resources/android/splash/drawable-port-xxhdpi-screen.png" />
        <splash density="port-xxxhdpi" src="resources/android/splash/drawable-port-xxxhdpi-screen.png" />
        <icon density="ldpi" src="resources/android/icon/drawable-ldpi-icon.png" />
        <icon density="mdpi" src="resources/android/icon/drawable-mdpi-icon.png" />
        <icon density="hdpi" src="resources/android/icon/drawable-hdpi-icon.png" />
        <icon density="xhdpi" src="resources/android/icon/drawable-xhdpi-icon.png" />
        <icon density="xxhdpi" src="resources/android/icon/drawable-xxhdpi-icon.png" />
        <icon density="xxxhdpi" src="resources/android/icon/drawable-xxxhdpi-icon.png" />
    </platform>
    <platform name="ios">
        <splash height="1136" src="resources/ios/splash/Default-568h@2x~iphone.png" width="640" />
        <splash height="1334" src="resources/ios/splash/Default-667h.png" width="750" />
        <splash height="2208" src="resources/ios/splash/Default-736h.png" width="1242" />
        <splash height="1242" src="resources/ios/splash/Default-Landscape-736h.png" width="2208" />
        <splash height="1536" src="resources/ios/splash/Default-Landscape@2x~ipad.png" width="2048" />
        <splash height="768" src="resources/ios/splash/Default-Landscape~ipad.png" width="1024" />
        <splash height="2048" src="resources/ios/splash/Default-Portrait@2x~ipad.png" width="1536" />
        <splash height="1024" src="resources/ios/splash/Default-Portrait~ipad.png" width="768" />
        <splash height="960" src="resources/ios/splash/Default@2x~iphone.png" width="640" />
        <splash height="480" src="resources/ios/splash/Default~iphone.png" width="320" />
        <icon height="57" src="resources/ios/icon/icon.png" width="57" />
        <icon height="114" src="resources/ios/icon/icon@2x.png" width="114" />
        <icon height="40" src="resources/ios/icon/icon-40.png" width="40" />
        <icon height="80" src="resources/ios/icon/icon-40@2x.png" width="80" />
        <icon height="50" src="resources/ios/icon/icon-50.png" width="50" />
        <icon height="100" src="resources/ios/icon/icon-50@2x.png" width="100" />
        <icon height="60" src="resources/ios/icon/icon-60.png" width="60" />
        <icon height="120" src="resources/ios/icon/icon-60@2x.png" width="120" />
        <icon height="180" src="resources/ios/icon/icon-60@3x.png" width="180" />
        <icon height="72" src="resources/ios/icon/icon-72.png" width="72" />
        <icon height="144" src="resources/ios/icon/icon-72@2x.png" width="144" />
        <icon height="76" src="resources/ios/icon/icon-76.png" width="76" />
        <icon height="152" src="resources/ios/icon/icon-76@2x.png" width="152" />
        <icon height="29" src="resources/ios/icon/icon-small.png" width="29" />
        <icon height="58" src="resources/ios/icon/icon-small@2x.png" width="58" />
        <icon height="87" src="resources/ios/icon/icon-small@3x.png" width="87" />
    </platform>`

**Comment by tisron** [comment] 2016-07-18 17:50
For the --splash generating I could only use an image as big as ~2400px. Resized down from ~2900px. Not sure what the limit is on file size, but it is confusing as I had been following [this tutorial](http://blog.ionic.io/automating-icons-and-splash-screens/) which suggests a minimum 2208x2208 for the splash image.

**Comment by chriseckman** [comment] 2016-07-20 03:38
The supplied splash [template](http://code.ionicframework.com/resources/splash.psd) is too large (2732x2732). When the size of the splash screen file is reduced to 2208x2208 it runs without a hitch.

**Comment by gigocabrera** [comment] 2016-07-24 14:26
+1

**Comment by bmwertman** [comment] 2016-07-25 03:55
I have my template at 2208 X 2208 with an image size of 1200 X 360. It finally generated an image but it is way too large and goes off the edge of the my Android devices screen.

**Comment by ntrp** [comment] 2016-07-26 08:11
I have the same problem, I tried with ionic client v1 and v2 beta. If the image is too big it doesn't complete the resources task  for neither icon or splash. Reducing to 2200px as suggested by some users worked, also selecting only icon generation worked. 

Actually the images are uploaded to the server and generated also using a 2732px image, and you can find the resulting images in your temp folder (with a different name) but they are not copied to the resources folder.

Also consider modifying the code that generates the images to use a local imagemagick instance if available and fallback to the server if there is none, I don't understand the need to upload 2mb images and to download ~10mb if it could be done locally.

**Comment by mnasyrov** [comment] 2016-07-26 08:40
+1 for using a local imagemagick if it is available.

**Comment by schankam** [comment] 2016-07-29 01:56
Followed what @chriseckman said, and it worked (had the issue only on iOS with nothing being generated).... The given PSD in the documentation is too large... Doesn't make sens, at least it would be good to update the documentation about that.

**Comment by pom421** [comment] 2016-08-04 09:27
I've just given ionic resources another try and i've been happy to notice this issue is fixed with the v2.0.0-beta35. 
Files are generated in resources/android and resources ios.

**Comment by jtushar53** [comment] 2016-08-04 14:20
it started working again one week ago and now getting same issue , not working for me
``` uploading icon.png...
 uploading splash.png...```

i'm on v2.0.0-beta35

**Comment by MrBokeh** [comment] 2016-08-06 00:44
![screenshot 2016-08-06 08 38 22](https://cloud.githubusercontent.com/assets/7272108/17453651/e1b5e498-5bb1-11e6-96a9-db8f58e89537.png)

@brandyscarney Is that possible to generate icons for Apple Watch as well? with the resouces command, Xcode is giving us warnings. Please see the attached screen grab.

**Comment by MrBokeh** [comment] 2016-08-06 06:19
![screenshot 2016-08-06 14 16 47](https://cloud.githubusercontent.com/assets/7272108/17455112/98f8f5e0-5be0-11e6-8241-1da1d9d9e27c.png)
![screenshot 2016-08-06 14 16 52](https://cloud.githubusercontent.com/assets/7272108/17455113/9903e3ce-5be0-11e6-8c39-7913d509a5cd.png)

@brandyscarney There are also missing splash screen sizes too for Xcode, is that possible to update the resource generator for both watch icons and missing splash screen sizes please?

**Comment by ihadeed** [comment] 2016-08-15 19:53
Did the following to get it to work:
- Uninstall Ionic 2 CLI
- Install Ionic 1 CLI (1.7.0)
- Run `ionic resources --icon` and `ionic resources -splash` individually

**Comment by tisron** [comment] 2016-08-15 21:28
For Mac/Unix, try running the resources command as superuser. I tested 1 file with and without sudo and it only worked for the latter. I don't know if this is the issue because there was no "read/write permission" error when it didn't work.

**Comment by jtushar53** [comment] 2016-08-16 10:57
hi, 
after some logging in resources.js(ionic-app-lib) from line 463 to 491, the issue was related to firewall page displaying in response after uploading resource.

response code was 200 btw. anyway used other internet to make it work

**Comment by chsakell** [comment] 2016-08-20 21:52
+1 using _v2.0.0-beta35_ on Windows machine

**Comment by chsakell** [comment] 2016-08-21 07:04
OK I finally managed to generate the resources!
The problem was on the file format of my custom **icon.png** and **splash.png** images. I had them created using powerpoint (save as picture..) with a .png format but they weren't valid. Here are the steps I took and from now on it always works. 

1. First of all confirm that when you use the default icon.png and splash.png images the i**onic resources** command works as intended.
2. Compare on [this](http://www.comparemyfiles.com/) site your custom .png files with the defaults respectively. Here is where I got a .png extension for the default files but **unknown** for my custom ones _(some weird characters actually)_.
3. In case your custom .png found invalid _(unknown extension)_ convert them [here](http://image.online-convert.com/convert-to-png). 
4. Use the new files and test. 

It make sense if ionic's image service validates the .png files before generate the resources. 
Here's my ionic info.
```
Cordova CLI: 6.3.0                                                                                                              
Gulp version:  CLI version 3.9.0                                                                                                
Gulp local:   Local version 3.9.1                                                                                               
Ionic Framework Version: 2.0.0-beta.11                                                                                          
Ionic CLI Version: 2.0.0-beta.35                                                                                                
Ionic App Lib Version: 2.0.0-beta.19                                                                                            
OS:                                                                                                                             
Node Version: v6.2.1 
```

**Comment by candidodmv** [comment] 2016-08-25 12:31
There is some news for this problem?

**Comment by mncvnn** [comment] 2016-08-25 13:24
Thanks @chsakell,

For future reference, mine facing the same issue this afternoon.
And somehow my *.PNG file not correct (I created them using Preview on Mac)
After following @chsakell convert PNG file, command work fine again.

Some info:
icon.png: 1024x1024
plash.png: 2208x2208
Ionic CLI: 2.0

Cheers!

**Comment by osirisr** [comment] 2016-08-26 10:03
I also have this issue.

Tried it on Mac in Sudo. Terminal results look successful, but when you go into the folder the old splashscreen images are still there.

**Comment by descadmx** [comment] 2016-08-27 08:10
I solved it in a not very handy way: 
1. Delete android/ios/<platform> folders inside resources/
2. Be sure your splash image is less than, say, 2500x2500, and compress the image so the filesize is as small as possible. Icon treatment is just the usual.
3. Run " ionic resources --icon --force " and " ionic resources --splash --force " TWICE each of them

**Comment by avoidwork** [comment] 2016-08-30 19:20
Hi,

I'm having this issue as well, but it's gotten a little weird for me lately. I generated my assets with support for an iPad Pro at 2732 x 2732 using temp assets; when I was given new assets of the correct dimensions but i couldn't generate the new resources until I resized the splash to 2500x2500.

**Comment by Kobzol** [comment] 2016-09-06 17:24
Try downgrading to Cordova 6.2.0.

**Comment by uloco** [comment] 2016-09-08 16:03
Looks like this issue is resolved on ionic@2.0.0

**Comment by tryadelion** [comment] 2016-09-12 15:29
heya this should be a critical bug any news?

**Comment by vdab-lnd** [comment] 2016-09-14 14:58
I had the same problem until I found out that I needed PROXY as environment variable instead of HTTP_PROXY...
A bit strange that when ionic cannot connect to the server to generate the icons it fails silently. I would at least have expected a warning or something.

**Comment by tryadelion** [comment] 2016-09-15 06:32
i was able to generate them by resizing my splash from 2200x2200 to 2000x2000. someone should fix this leaky pot.

**Comment by David-Prieto** [comment] 2016-09-15 15:52
Issue from Jul 11, still no fix.

**Comment by pvdyck** [comment] 2016-09-16 12:49
ionic resources --icon _works_
ionic resources -splash _does not_
Sequence looks weird, first it extracts files from the cache, then it uploads the .ai file...

**Comment by evandrojr** [comment] 2016-09-19 13:03
Give us access to the code so we can fix it!

**Comment by pvdyck** [comment] 2016-09-19 13:23
My icons are copyrighted ... could anybody else with the same problem provide their .ai or .psd files (icon/splash) ? @David-Prieto @tryadelion ?

**Comment by CookieCookson** [comment] 2016-09-21 21:51
This is a big issue for me too! If the image is too big, it generates the assets in the log and then doesn't copy them into the required places in the `resources` folder or into `config.xml` so it must be erroring silently. It would be great to know if any progress is being made on this!

**Comment by tryadelion** [comment] 2016-09-27 08:50
i can't provide icons or splashes, everything copyrighted here.

**Comment by tryadelion** [comment] 2016-09-27 09:08
so basically  i think i got splash working by making a full square 2208x2008, which looks weird. different sized (W-H) .psd's  don't seem to work, and it didn't even generate the tablet ones.

**Comment by pavei** [comment] 2016-09-30 22:25
+1

**Comment by feda8891** [comment] 2016-10-05 16:03
Any update?

**Comment by RaffaeleT** [comment] 2016-10-07 15:26
`ionic resources --splash` is working for me when I feed it with a 2500x2500 png.
I am using CLI 2.0.0

**Comment by engehabahmed** [comment] 2016-10-10 20:47
2800*2800 32 bit 10.3 Mega worked fine with me ! :)

**Comment by seiyria** [comment] 2016-10-15 18:30
2800x2800 is not working for me, it still fails to generate splash resources.

**Comment by carlosbutler** [comment] 2016-10-26 16:09
Everyone, I would highly recommend removing any metadata that is with the image, and then ensuring it has NOT been converted to sRGB or any other different profiles are applied to the image.

**Comment by jthoms1** [comment] 2016-10-28 00:10
We recently released a new version of the CLI that should resolve the resources issues.  Could you please update your CLI to at least 2.1.4?

`npm install -g ionic@latest`

Thank you!

**Closed** 2016-10-29 11:40 UTC
Labels: platform:android, platform:ios, resources gen, v2

**Comment by xujingbao** [comment] 2016-11-06 03:56
➜  ionic-quickstarter git:(master) ✗ ionic resources --icon
Ionic icon resources generator
 uploading icon.png...
icon.png (1024x1024) upload complete
 generating icon ios icon-small@3x.png (87x87)...
 generating icon ios icon-small@2x.png (58x58)...
 generating icon ios icon-small.png (29x29)...
icon ios icon-small@2x.png (58x58) generated
 generating icon ios icon-83.5@2x.png (167x167)...
icon ios icon-small.png (29x29) generated
 generating icon ios icon-76@2x.png (152x152)...
icon ios icon-small@3x.png (87x87) generated
 generating icon ios icon-76.png (76x76)...
icon ios icon-76@2x.png (152x152) generated
 generating icon ios icon-72@2x.png (144x144)...
icon ios icon-76.png (76x76) generated
 generating icon ios icon-72.png (72x72)...
icon ios icon-83.5@2x.png (167x167) generated
 generating icon ios icon-60@3x.png (180x180)...
icon ios icon-72.png (72x72) generated
 generating icon ios icon-60@2x.png (120x120)...
icon ios icon-60@3x.png (180x180) generated
 generating icon ios icon-60.png (60x60)...
icon ios icon-60@2x.png (120x120) generated
 generating icon ios icon-50@2x.png (100x100)...
icon ios icon-60.png (60x60) generated
 generating icon ios icon-50.png (50x50)...
icon ios icon-50@2x.png (100x100) generated
icon ios icon-40@3x.png (120x120) generated
 generating icon ios icon-40@2x.png (80x80)...
icon ios icon-40@2x.png (80x80) generated
 generating icon ios icon-40.png (40x40)...
icon ios icon-50.png (50x50) generated
 generating icon ios icon@2x.png (114x114)...
icon ios icon-40.png (40x40) generated
 generating icon ios icon.png (57x57)...
icon ios icon.png (57x57) generated

。。。
。。。。

wait for long time  nothing gen

**Comment by iammeat** [comment] 2016-11-07 19:17
I'm having the same problem on Mac OS X El Capitan, even with the ionic@latest update.

**Comment by avoidwork** [comment] 2016-11-08 11:45
@jthoms1 why close this bug before validating it's working for everyone?

**Comment by masumonline** [comment] 2016-11-09 11:38
Not working yet

**Comment by punksta** [comment] 2016-11-10 13:57
not working on 2.1.4

**Comment by xujingbao** [comment] 2016-11-10 14:20
use ionic cli 2.0.0

**Comment by sameera207** [comment] 2016-11-10 23:01
I'm using `2.1.7` and as @iammeat mentioned, its not working for `android`. However I can see the images are generated in the resources/android folder and I can see references in the config file too. 

<img width="752" alt="screen shot 2016-11-11 at 9 59 58 am" src="https://cloud.githubusercontent.com/assets/98407/20197856/b07a5c20-a7f5-11e6-8312-07feec90a3d6.png">

and this works fine with `ios`

**Comment by victorcarvalhosp** [comment] 2016-11-12 14:16
Same problem than @sameera207 the resources are generated, but don't work for android...

**Comment by geocine** [comment] 2016-11-12 14:30
I am experiencing the same issue, resources are generated but I cannot see them on android.

For the **icon** to work I did this:
```
ionic platform rm android
ionic platform add https://github.com/apache/cordova-android.git#master
```

but still the **splash** is not showing

**Comment by evandrojr** [comment] 2016-11-12 18:00
There is a cordova plugin for icon and another for splash. They do work
fine.

Em 12/11/2016 11:30, "Aivan Monceller" <notifications@github.com> escreveu:

**Comment by geocine** [comment] 2016-11-12 18:06
I have gone through debugging the android code and I saw my image is loaded by *SplashScreen* (clicked View Bitmap) but nothing is showing on my android device.
```
splashDialog.setContentView(splashImageView);
splashDialog.setCancelable(false);
splashDialog.show();
```

**Comment by geocine** [comment] 2016-11-12 18:14
For anyone experiencing the same issue - **Splash screen not showing**.  You need to know that to be able to show your splash screen you need to un-satisfy this condition
```java
if (drawableId == 0 || (splashscreenTime <= 0 && hideAfterDelay)) {
    return;
}
```

So in this case you need to put this on your config.xml
```
<preference name="AutoHideSplashScreen" value="false"/>
<preference name="SplashScreenDelay" value="0"/>
```

**Comment by hiddenkirby** [comment] 2016-11-14 04:32
ionic platform rm android
ionic platform add https://github.com/apache/cordova-android.git#master
ionic resources --icon
ionic resources --splash

.. this fixed my woes...

**Comment by PEZO19** [comment] 2016-11-15 15:23
**Unbelievable working solution here!**
More than 2 hours from my life. How long are you trying to solve this?

I'm on mac, ionic info below.

First, I had similar problems as **sameera207** 5 days ago: 
after
> ionic resources
the generation happened, and I had the proper(...? uhm...) changes in config.xml

I also noticed as somebody above, that there is also **res** folder (I dont know what is creating it and when, and why...)

Now, I managed to work with icons, but I have no idea why it is working.

As noted above there is a "plugin" for icons. I followed the top anwser from here:
[http://stackoverflow.com/questions/23830467/generating-ios-and-android-icons-in-cordova-phonegap]
which drives you there:
[https://github.com/AlexDisler/cordova-icon]
This is a command line tool, and after I followed the steps it successfully created the sized icons, BUT(!) I dont know where! The output is pretty neat and it is telling you, its done. BUT after that, I had the icons in **res** and also in **resources**!!! But after an android build it really works, and after apk install, I have the icon correctly on my phone.

The amazing thing is: if I delete/rename the resources (in webstorm) folder, it stops working! I mean, if i retry with cordova-icon, the generation still works, but after that, android build fails: it cant find **resources** folder; which has my OLD (random?) files, not the just created with cordova-icon. But the app has the icons from cordova-icon.

I've just done it twice, so I feel it's can't be totally random. Please add any comment, I'm really really confused.

+1 note: caching is disabled for be in /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/resources.js, but i dont know if it is needed.

`ionic info` 
gives me:

Your system information:

Cordova CLI: 6.4.0
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v6.9.1
Xcode version: Xcode 8.1 Build version 8B62


******************************************************
 Dependency warning - for the CLI to run correctly,
 it is highly recommended to install/upgrade the following:

 Install ios-sim to deploy iOS applications.`npm install -g ios-sim` (may require sudo)
 Install ios-deploy to deploy iOS applications to devices.  `npm install -g ios-deploy` (may require sudo)

******************************************************

**Comment by xke** [comment] 2016-11-15 22:33
Hi!

I was able to get "ionic resources --icon" to work on the latest Ionic CLI version 2.1.8 and Ionic Framework Version: 2.0.0-rc.2.

However, still could not see the updated icon on the Emulator or the Device -- until after I figured out why. 

My solution was to replace the icon.png files in the <code>platforms/android/res/mipmap-*</code> folder with the new images. I used makeappicon.com to generate icon files (which I then renamed to icon.png).

Seems like this is an issue in either Ionic or Cordova. I will file a new issue as relevant.

**Comment by xke** [comment] 2016-11-15 22:37
Filed issue at https://github.com/driftyco/ionic-cli/issues/1683

**Comment by periyasamy17** [comment] 2016-11-17 10:44
I am Using 
Cordova CLI: 6.4.0 
Ionic CLI Version: 2.1.8
Ionic App Lib Version: 2.1.4
OS: Linux 4.4
Node Version: v4.2.6
 not working ionic icon and splash screen.

**Comment by Lestt** [comment] 2016-11-18 13:27
ionic platform rm android
ionic platform add https://github.com/apache/cordova-android.git#master
ionic resources --icon
ionic resources --splash

Fixed my issues too, i don't understand why ionic add platform android doesn't support icon and splashcreen now...
I'm using:
Cordova CLI: 6.4.0
Ionic CLI Version: 1.3.1
Ionic App Lib Version: 2.1.4
OS: Windows 10
Node Version: v6.9.1

**Comment by danielsawan** [comment] 2016-11-22 12:16
@PEZO19 got the answer to your /res generated folder here > https://github.com/driftyco/ionic/issues/9270#issuecomment-262110031

Hope they will fix this bug soon.

**Comment by pcrombach** [comment] 2016-11-26 14:36
Finally I got it simple working with this small script in hooks/after_build:
#!/usr/bin/env node

```
'use strict';

var ncp = require('ncp');

ncp('./res', './platforms/android/res', function(e){
	if(e) {
		return console.log('res copy error', e);
	} else {
		return console.log('res copied');
	}
});


```

**Comment by joergjung** [comment] 2016-11-27 23:51
Only works for me on Android when I replace the default icon.png and screen.png in the 
platforms/android/res folder with my own files (ionic resources command worked, splash.png was 2208x2208px, icon.png was 1024x1024px).
Also had to create xxhdpi and xxxhdpi folders.

Would be great to see that bug fixed :)

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: 1.9.0
ios-sim version: 5.0.8
OS: macOS Sierra
Node Version: v6.7.0
Xcode version: Xcode 8.1 Build version 8B62

**Comment by MtheCastro** [comment] 2016-11-30 17:10
+1

**Comment by xke** [comment] 2016-11-30 17:12
See latest at https://github.com/driftyco/ionic-cli/issues/1683

**Comment by evandrojr** [comment] 2016-12-02 16:38
Dont use that. Use the cordova plugin that does the same way bettter

Em 30/11/2016 14:12, "xke" <notifications@github.com> escreveu:

**Comment by comfortme** [comment] 2016-12-04 19:56
same issue for me too

ionic platform rm android
ionic platform add https://github.com/apache/cordova-android.git#master
ionic resources --icon

saves the day

**Comment by jimiatworking** [comment] 2016-12-14 07:58
@evandrojr hi, I would like to know which cordova pluin you use to generate icon and splash? I have problem "Unable to generate images due to an error Invalid upload: image too large: 39002607"

**Comment by stchoukeu** [comment] 2016-12-15 15:43
If you are with IONIC2.1.13 like me, Put a splash size at 2732 x 2732 and  the icon size at 192 x192. update your android plateform  with `cordova platform update android@6.1.0` and execute the `ionic resources` .  I suddgest you to copie all the res folder generated from the plateform/android  and save it somewhere if in the future you face the same problem. In my case i had to come back with the command  `cordova platform update android@6.0.0` before to be able to build my project again and i'm now working with no issue.

**Comment by pcrombach** [comment] 2016-12-15 17:53
Hi, time ago I posted a small function for a hook in your app. That function copies all the resources to the right folders.

> Op 15 dec. 2016, om 16:43 heeft TCHOUKEU Simplice Aimé <notifications@github.com> het volgende geschreven:
> 
> If you are with IONIC2.1.13 like me, Put a splash size at 2732 x 2732 and the icon size at 192 x192. update your android plateform with cordova platform update android@6.1.0 and execute the ionic resources . I suddgest you to copie all the res folder generated from the plateform/android and save it somewhere if in the future you face the same problem. In my case i had to come back with the command  cordova platform update android@6.0.0 before to be able to build my project again and i'm now working with no issue.
> 
>

**Comment by evandrojr** [comment] 2016-12-18 21:00
Hi Jimi try https://github.com/AlexDisler/cordova-icon

Works well

Em 14/12/2016 04:58, "jimiatworking" <notifications@github.com> escreveu:

**Comment by wwwguy** [comment] 2016-12-30 23:59
Any news on this? Was able to get icon/splash working using Lestt post from 11/8 but still only working for Android not iOS... Any word on a full solution?

**Comment by balicekt** [comment] 2017-01-07 18:11
+1 icon and splash not copied to /platforms/android/res getting crazy of it!

**Comment by moaxaca** [comment] 2017-01-12 01:58
I got it to work, I just had to remove the old icons before generating. 

Its probably a file exists/copy error. Does anyone know in the code where this function is invoked? If so I will happily create a pull request fixing it.

**Comment by jimiatworking** [comment] 2017-01-12 02:04
@evandrojr Nice, thanks. I'll give it a try.

**Comment by 0x1ad2** [comment] 2017-01-18 20:01
Just tried it and it worked (used a new RC5 project).
Execute the following commands:

```
$ cordova platform update android@6.1.0
$ ionic resources android
```

```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.5
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0 
ios-sim version: 5.0.11 
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by michaelmafort** [comment] 2017-01-19 16:28
@0x1ad2 Works perfectly.

**Comment by aristofanio** [comment] 2017-01-31 15:07
+1 

> [@0x1ad2 Works perfectly]

**Comment by ruig6549** [comment] 2017-03-15 05:07
I found an answer  i have defined for work only in portrait so ionic resources dont make the landscape icons and splash. Thats it. Thanks

**Comment by 0x1ad2** [comment] 2017-03-16 15:48
@mhartington can't we bump the Cordova android to 6.1.0 (or higher) by default? Cause this still occurs when starting a new Ionic project (using CLI `$ionic start`).

**Comment by mhartington** [comment] 2017-03-16 17:27
It's not something we actually set. The cordova team pins a specific version of plugins/platforms to npm for version compatibility. If you want the latest/great stuff, you need to use `@latest` version flag.

**Comment by Brieg** [comment] 2017-04-10 12:56
Resolve issuse:

`npm install -g cordova`

It's fix in cordova 6.5.0

**Comment by 0x1ad2** [comment] 2017-04-19 09:48
@Brieg it was already solved in `6.1.0` as I mentioned.
Any chance you could close this issue @mhartington?

**Comment by pcrombach** [comment] 2017-04-19 09:50
I agree. is solved, so can be closed.

**Comment by geocine** [comment] 2017-04-20 06:13
what are you saying guys? This issue was closed last October 2016
