### ISSUE TITLE
changelog is not updated to the last version

### ISSUE THREAD

**Issue by pfrancois** [driftyco/ionic-cli#717] opened 2016-01-11 21:58 UTC
currently we have the version 1.7.7 in the changelog.md or the last version in npm is 1.7.12.
so we don't have the last version in the changelog.

**Comment by johnmcase** [comment] 2016-01-21 18:17
+1

This is a duplicate of #679

**Comment by jgw96** [comment] 2016-05-02 20:16
Hello! As this is a duplicate of #679 i will be closing this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-05-02 20:16 UTC
