### ISSUE TITLE
Ionic v2 serve doesn't livereload

### ISSUE THREAD

**Issue by ahmedbaracat** [driftyco/ionic-cli#765] opened 2016-02-12 18:35 UTC
I am starting a project using `ionic start tmp tutorial --v2` and starting the serve with `ionic serve`.
The problem is that when I change the files in the app folder, the server doesn't detect the changes and the web page is not refreshed.

**Things I have tried**
- Uninstalled ionic and reinstalled it.
- Tried creating projects from scratch
- Tried using Chrome and Safari

**Versions**
ionic 2.0.0-beta.17
Cordova 6.0.0
npm 2.14.12
node v4.3
OS X 10.11.3

**Comment by mhartington** [comment] 2016-02-12 21:07
Legit. Did a screen share with him and wasn't able to resolve. @tlancina any ideas?

**Comment by tlancina** [comment] 2016-02-12 21:30
Hmm, if you `npm install -g webpack` (you may need to `sudo npm install -g webpack`) and then run `webpack -w` does it detect changes?

**Comment by ahmedbaracat** [comment] 2016-02-13 07:01
Thank you :):) That fixed it. So the problem was about having webpack installed globally?

**Comment by tlancina** [comment] 2016-02-15 15:42
@ahmedbaracat I'm not sure what to tell you, unfortunately.  I asked about installing webpack to see if it was detecting changes for `webpack -w` but not `ionic serve`, which would indicate it's an ionic issue, but it sounds like there may be some issues with fsevents on your system.

Very strange that it works sometimes, but not others.  What does your webpack.config.js look like, and what are the paths to the projects? We've had some very hard to track down issues that ended up being caused by webpack regexes matching paths they weren't supposed to be.

**Comment by ahmedbaracat** [comment] 2016-02-15 16:24
@tlancina Thank you It is definitely a path issue. I was having problems with my path for sometimes now because of a folder that had spaces and parentheses. I changed it now and tested several ionic projects and live reload worked just fine.

Thank you :):)

**Comment by tlancina** [comment] 2016-02-16 16:42
@ahmedbaracat awesome! Glad it's working now. I'm going to close this, but please feel free to comment if you're still having issue.

**Closed by tlancina** 2016-02-16 16:42 UTC
Labels: v2

**Comment by kentongray** [comment] 2016-03-06 15:25
I think this is still a "bug" in that it doesn't work if you have paths with spaces. Seems like an escaping issue. Will dig around a bit and see if I see any easy fixes

**Comment by kentongray** [comment] 2016-03-06 15:31
I can confirm ye old trick of symbol linking the path does resolve the problem

**Comment by kentongray** [comment] 2016-03-06 15:36
Strangely symbol linking doesn't seem to fix the problem. I actually had to move the directory out of the dir with the space

**Comment by tlancina** [comment] 2016-03-06 19:45
@kentongray thanks for taking a look, what's the output of `ionic info` for you? I just tested out a new project with a space in the path quickly and livereload was working for me.  If there is a simple way to reproduce this I'll re-open the issue.

**Comment by gsabater** [comment] 2016-03-08 16:11
Looks like i'm also having the same issue with livereload. My project path have a folder called "0. Dropbox", and though i have not tested to move it outside because `webpack -w` did the trick for me, it might also confirm the bug with whitespaces or symbols in path.

**Comment by kentongray** [comment] 2016-03-13 05:45
@tlancina sorry I missed your message
```> ionic info

Your system information:

Cordova CLI: 5.0.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 2.0.0-alpha.57
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
ios-deploy version: 1.7.0 
ios-sim version: 3.1.1 
OS: Mac OS X El Capitan
Node Version: v5.2.0
Xcode version: Xcode 7.2.1 Build version 7C1002 
```

@gsabater interestingly enough mine is a dropbox folder don't think that should break it but you never know..

**Comment by kentongray** [comment] 2016-03-13 05:48
i'd actually love to dig into the root issue but i can't find where the webpack related code actually is.... is it on this repo?

**Comment by kentongray** [comment] 2016-03-13 05:57
also since i see that there are different branches i am using the typescript ionic2
