### ISSUE TITLE
(/platforms as own git repository) `ionic state save` adds .git as platform

### ISSUE THREAD

**Issue by piotrowski** [driftyco/ionic-cli#641] opened 2015-11-07 13:43 UTC
Just did `ionic state save` on my local project where I have `/platforms` ignored in my main git repository, but a seperate repository only for this folder so I can track changes that happen in there. Strangely the `.git` folder got added as a platform to `package.json`:

       {
         "platform": ".git",
         "version": "",
         "locator": ".git"
       }

**Comment by jbavari** [comment] 2015-11-07 23:42
Duplicate of the other issue you posted. These are caused by the same thing. Closing.

**Closed by jbavari** 2015-11-07 23:42 UTC
