### ISSUE TITLE
Error Initializing app: There was an error with the spawned command: npminstall

### ISSUE THREAD

**Issue by meiyalei** [driftyco/ionic-cli#1186] opened 2016-07-17 08:32 UTC
Your system information:

Cordova CLI: 6.2.0
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v5.10.1
Xcode version: Xcode 7.3.1 Build version 7D1014 

fangyideMacBook-Pro:Workspace fangyi$ sudo ionic start demo3i --v2
Password:
Creating Ionic app in folder /Users/fangyi/Workspace/demo3i based on tabs project
Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic2-starter-tabs/archive/master.zip
[=============================]  100%  0.0s
Installing npm packages...
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

**Comment by EPSON-LEE** [comment] 2016-07-21 23:23
+1

**Comment by jthoms1** [comment] 2016-07-25 20:54
This is a duplicate of #1013.

I am closing this issue. It has been kind of a catch all for npm install issues from ionic start. If you are having issues please try running with the verbose flag.

sudo ionic start cutePuppyPics --v2 --verbose

This should provide more insight into what is happening. In most cases it will report issues with network connectivity or permissions issues. If this is not the case please open an issue with your ionic info output.

**Closed by jthoms1** 2016-07-25 20:54 UTC

**Comment by anilthummar** [comment] 2017-04-18 09:36
@jthoms1 
Still i m getting error:

**Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
Downloading: https://github.com/driftyco/ionic2-starter-tabs/archive/master.zip
Installing npm packages (may take a minute or two)...
Running exec command: npminstall
Spawn command completed
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall**
