### ISSUE TITLE
Issue "ionic resources" not working

### ISSUE THREAD

**Issue by cinder92** [driftyco/ionic-cli#1061] opened 2016-06-10 16:55 UTC
When i'm trying to use this service icons and splash aren't generated and i don't getting any kind of error.

Please help! :)

![captura de pantalla 2016-06-10 a las 11 54 15 a m](https://cloud.githubusercontent.com/assets/4725556/15972093/1a44bd8e-2f02-11e6-8830-9fc455bfdf50.png)

**Comment by jthoms1** [comment] 2016-06-10 19:09
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.

**Comment by emaxedon** [comment] 2016-06-10 19:28
After using `$ ionic resources` I see the following output:

```
Ionic icon and splash screen resources generator
 uploading icon.png...
 uploading splash.png...
splash.png (2732x2732) upload complete
icon.png (2567x2333) upload complete
 generating icon ios icon-small@3x.png (87x87)...
 generating icon ios icon-small@2x.png (58x58)...
 generating icon ios icon-small.png (29x29)...
icon ios icon-small@2x.png (58x58) generated
 generating icon ios icon-83.5@2x.png (167x167)...
icon ios icon-small.png (29x29) generated
 generating icon ios icon-76@2x.png (152x152)...
icon ios icon-small@3x.png (87x87) generated
 generating icon ios icon-76.png (76x76)...
icon ios icon-76@2x.png (152x152) generated
 generating icon ios icon-72@2x.png (144x144)...
icon ios icon-83.5@2x.png (167x167) generated
 generating icon ios icon-72.png (72x72)...
icon ios icon-72@2x.png (144x144) generated
 generating icon ios icon-60@3x.png (180x180)...
icon ios icon-72.png (72x72) generated
 generating icon ios icon-60@2x.png (120x120)...
icon ios icon-76.png (76x76) generated
 generating icon ios icon-60.png (60x60)...
icon ios icon-60@2x.png (120x120) generated
 generating icon ios icon-50@2x.png (100x100)...
icon ios icon-60.png (60x60) generated
 generating icon ios icon-50.png (50x50)...
icon ios icon-50@2x.png (100x100) generated
icon ios icon-40@3x.png (120x120) generated
 generating icon ios icon-40@2x.png (80x80)...
icon ios icon-50.png (50x50) generated
 generating icon ios icon-40.png (40x40)...
icon ios icon-60@3x.png (180x180) generated
 generating icon ios icon@2x.png (114x114)...
icon ios icon@2x.png (114x114) generated
 generating icon ios icon.png (57x57)...
icon ios icon-40.png (40x40) generated
 generating icon android drawable-xxxhdpi-icon.png (192x192)...
icon ios icon-40@2x.png (80x80) generated
icon android drawable-xxhdpi-icon.png (144x144) generated
 generating icon android drawable-xhdpi-icon.png (96x96)...
icon android drawable-xxxhdpi-icon.png (192x192) generated
icon android drawable-hdpi-icon.png (72x72) generated
 generating icon android drawable-mdpi-icon.png (48x48)...
icon ios icon.png (57x57) generated
 generating icon android drawable-ldpi-icon.png (36x36)...
icon android drawable-xhdpi-icon.png (96x96) generated
 generating splash android drawable-port-xxxhdpi-screen.png (1280x1920)...
icon android drawable-mdpi-icon.png (48x48) generated
 generating splash android drawable-port-xxhdpi-screen.png (960x1600)...
icon android drawable-ldpi-icon.png (36x36) generated
 generating splash android drawable-port-xhdpi-screen.png (720x1280)...
splash android drawable-port-xxxhdpi-screen.png (1280x1920) generated
 generating splash android drawable-port-hdpi-screen.png (480x800)...
splash android drawable-port-xxhdpi-screen.png (960x1600) generated
 generating splash android drawable-port-mdpi-screen.png (320x480)...
splash android drawable-port-xhdpi-screen.png (720x1280) generated
 generating splash android drawable-port-ldpi-screen.png (240x320)...
splash android drawable-port-hdpi-screen.png (480x800) generated
 generating splash android drawable-land-xxxhdpi-screen.png (1920x1280)...
splash android drawable-port-mdpi-screen.png (320x480) generated
 generating splash android drawable-land-xxhdpi-screen.png (1600x960)...
splash android drawable-port-ldpi-screen.png (240x320) generated
 generating splash android drawable-land-xhdpi-screen.png (1280x720)...
splash android drawable-land-xxhdpi-screen.png (1600x960) generated
 generating splash android drawable-land-hdpi-screen.png (800x480)...
splash android drawable-land-xxxhdpi-screen.png (1920x1280) generated
 generating splash android drawable-land-mdpi-screen.png (480x320)...
splash android drawable-land-xhdpi-screen.png (1280x720) generated
 generating splash android drawable-land-ldpi-screen.png (320x240)...
splash android drawable-land-hdpi-screen.png (800x480) generated
splash ios Default~iphone.png (320x480) generated
 generating splash ios Default@2x~iphone.png (640x960)...
splash android drawable-land-ldpi-screen.png (320x240) generated
 generating splash ios Default-Portrait~ipad.png (768x1024)...
splash android drawable-land-mdpi-screen.png (480x320) generated
 generating splash ios Default-Portrait@~ipadpro.png (2048x2732)...
splash ios Default@2x~iphone.png (640x960) generated
 generating splash ios Default-Portrait@2x~ipad.png (1536x2048)...
splash ios Default-Portrait~ipad.png (768x1024) generated
 generating splash ios Default-Landscape~ipad.png (1024x768)...
splash ios Default-Landscape~ipad.png (1024x768) generated
 generating splash ios Default-Landscape@~ipadpro.png (2732x2048)...
splash ios Default-Portrait@2x~ipad.png (1536x2048) generated
 generating splash ios Default-Landscape@2x~ipad.png (2048x1536)...
splash ios Default-Landscape@2x~ipad.png (2048x1536) generated
 generating splash ios Default-Landscape-736h.png (2208x1242)...
splash ios Default-Landscape-736h.png (2208x1242) generated
 generating splash ios Default-736h.png (1242x2208)...
splash ios Default-736h.png (1242x2208) generated
 generating splash ios Default-667h.png (750x1334)...
splash ios Default-667h.png (750x1334) generated
 generating splash ios Default-568h@2x~iphone.png (640x1136)...
splash ios Default-568h@2x~iphone.png (640x1136) generated
```

**_However_**, all the directories where the icons and splash screens should be placed are in fact **empty**...

**Comment by emaxedon** [comment] 2016-06-10 19:45
I was able to fix my issue by resizing my splash.png file to be 1200x1200 and running `$ ionic resources` again.

I think an error message **should** display if the uploaded splash is larger than 1200x1200 since this seems to be breaking `ionic resources` for me.

**Comment by simonefalcini** [comment] 2016-06-14 14:39
I have the same problem but if I resize the splash.png smaller than 2048 i get an error for some files:

```
ionic resources
Ionic icon and splash screen resources generator
 uploading icon.png...
 uploading splash.png...
splash.png (1200x1200) upload complete
icon.png (500x500) upload complete
splash android drawable-port-xxxhdpi-screen.png (1280x1920) skipped, source image splash.png (1200x1200) too small
splash android drawable-port-xxhdpi-screen.png (960x1600) skipped, source image splash.png (1200x1200) too small
splash android drawable-port-xhdpi-screen.png (720x1280) skipped, source image splash.png (1200x1200) too small
 generating splash android drawable-port-hdpi-screen.png (480x800)...
 generating splash android drawable-port-mdpi-screen.png (320x480)...
 generating splash android drawable-port-ldpi-screen.png (240x320)...
splash android drawable-port-ldpi-screen.png (240x320) generated
splash android drawable-land-xxxhdpi-screen.png (1920x1280) skipped, source image splash.png (1200x1200) too small
splash android drawable-land-xxhdpi-screen.png (1600x960) skipped, source image splash.png (1200x1200) too small
splash android drawable-land-xhdpi-screen.png (1280x720) skipped, source image splash.png (1200x1200) too small
 generating splash android drawable-land-hdpi-screen.png (800x480)...
splash android drawable-port-mdpi-screen.png (320x480) generated
 generating splash android drawable-land-mdpi-screen.png (480x320)...
splash android drawable-port-hdpi-screen.png (480x800) generated
 generating splash android drawable-land-ldpi-screen.png (320x240)...
splash android drawable-land-ldpi-screen.png (320x240) generated
splash ios Default~iphone.png (320x480) generated
 generating splash ios Default@2x~iphone.png (640x960)...
splash android drawable-land-mdpi-screen.png (480x320) generated
 generating splash ios Default-Portrait~ipad.png (768x1024)...
splash android drawable-land-hdpi-screen.png (800x480) generated
splash ios Default-Portrait@~ipadpro.png (2048x2732) skipped, source image splash.png (1200x1200) too small
splash ios Default-Portrait@2x~ipad.png (1536x2048) skipped, source image splash.png (1200x1200) too small
 generating splash ios Default-Landscape~ipad.png (1024x768)...
splash ios Default-Portrait~ipad.png (768x1024) generated
splash ios Default-Landscape@~ipadpro.png (2732x2048) skipped, source image splash.png (1200x1200) too small
splash ios Default-Landscape@2x~ipad.png (2048x1536) skipped, source image splash.png (1200x1200) too small
splash ios Default-Landscape-736h.png (2208x1242) skipped, source image splash.png (1200x1200) too small
splash ios Default-736h.png (1242x2208) skipped, source image splash.png (1200x1200) too small
splash ios Default-667h.png (750x1334) skipped, source image splash.png (1200x1200) too small
 generating splash ios Default-568h@2x~iphone.png (640x1136)...
splash ios Default@2x~iphone.png (640x960) generated
 generating icon android drawable-xxxhdpi-icon.png (192x192)...
splash ios Default-Landscape~ipad.png (1024x768) generated
 generating icon android drawable-xxhdpi-icon.png (144x144)...
splash ios Default-568h@2x~iphone.png (640x1136) generated
 generating icon android drawable-xhdpi-icon.png (96x96)...
icon android drawable-xhdpi-icon.png (96x96) generated
 generating icon android drawable-hdpi-icon.png (72x72)...
icon android drawable-xxxhdpi-icon.png (192x192) generated
 generating icon android drawable-mdpi-icon.png (48x48)...
icon android drawable-mdpi-icon.png (48x48) generated
 generating icon android drawable-ldpi-icon.png (36x36)...
icon android drawable-hdpi-icon.png (72x72) generated
 generating icon ios icon-small@3x.png (87x87)...
icon android drawable-ldpi-icon.png (36x36) generated
 generating icon ios icon-small@2x.png (58x58)...
icon android drawable-xxhdpi-icon.png (144x144) generated
 generating icon ios icon-small.png (29x29)...
icon ios icon-small@3x.png (87x87) generated
 generating icon ios icon-83.5@2x.png (167x167)...
icon ios icon-small@2x.png (58x58) generated
 generating icon ios icon-76@2x.png (152x152)...
icon ios icon-small.png (29x29) generated
 generating icon ios icon-76.png (76x76)...
icon ios icon-83.5@2x.png (167x167) generated
icon ios icon-72@2x.png (144x144) generated
icon ios icon-72.png (72x72) generated
 generating icon ios icon-60@3x.png (180x180)...
icon ios icon-76.png (76x76) generated
 generating icon ios icon-60@2x.png (120x120)...
icon ios icon-76@2x.png (152x152) generated
 generating icon ios icon-60.png (60x60)...
icon ios icon-60@3x.png (180x180) generated
 generating icon ios icon-50@2x.png (100x100)...
icon ios icon-60.png (60x60) generated
 generating icon ios icon-50.png (50x50)...
icon ios icon-50@2x.png (100x100) generated
icon ios icon-40@3x.png (120x120) generated
 generating icon ios icon-40@2x.png (80x80)...
icon ios icon-60@2x.png (120x120) generated
 generating icon ios icon-40.png (40x40)...
icon ios icon-50.png (50x50) generated
 generating icon ios icon@2x.png (114x114)...
icon ios icon-40.png (40x40) generated
 generating icon ios icon.png (57x57)...
icon ios icon-40@2x.png (80x80) generated
icon ios icon@2x.png (114x114) generated
icon ios icon.png (57x57) generated
```

**Comment by mattblancarte** [comment] 2016-06-18 22:44
I'm having the exact same issue as @emaxedon 

I've tried each image format, scaling it down to 2208x2208, running ionic resources, ionic resources --force, ionic resources --splash, ionic resources --force --splash, removed the caching from the resources.js script.

I was randomly able to generate icons today after it not working at all for a few days with ionic resources and ionic resources --icon

Is this a server side issue? I can see the images being written into the /var/local/ temp files dir.

**Comment by mattblancarte** [comment] 2016-06-18 22:55
I was able to generate splash images by slowing increasing the size of the image up to 2400px from 1200px and continually re-running the ionic resources --splash command.

So, maybe start at 1200, then go to 1600, then 2000, then 2400.

I confirmed that it is broken by clearing those folders and then trying to generate icons and splash images from the default 2732x2732 psd. Trying to feed that image size breaks both the icon generator and the splash generator.

**Comment by rlambertsen** [comment] 2016-06-23 18:36
It stopped for me at 2000x20000. FYI. @emaxedon was the first to call it!!!

**Comment by asiddeen** [comment] 2016-07-04 10:01
@cinder92 i was having same issue, then i use VPN now its working... i think it's not **ionic** error rather **network**.

**Comment by jgw96** [comment] 2016-07-12 19:48
Hello all, i will be closing this issue as a duplicate of https://github.com/driftyco/ionic-cli/issues/1166. Thanks for using Ionic!

**Closed by jgw96** 2016-07-12 19:48 UTC
Labels: resources gen

**Comment by Allan-Nava** [comment] 2017-10-10 12:41
I have the same issue
![cattura](https://user-images.githubusercontent.com/22498435/31386961-f90ebc2c-adc8-11e7-9582-d43d83f672be.PNG)
