### ISSUE TITLE
bug: `ionic run android` does not install the application on the device/emulator

### ISSUE THREAD

**Issue by perrygovier** [driftyco/ionic-cli#441] opened 2015-05-22 19:49 UTC
_From @keval5531 on May 22, 2015 10:41_

**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>2.x</span>  <span ionic-webview>webview</span>

<span ionic-description>I recently updated my CLI and it seems like the `ionic run android` command won't install the apk on my device. The build is successful, the CLI even tells that the apk was installed and launch was Successful, which is untrue; there is no apk installed. 
It requires me to install it manually using `adb install`. On my other machine I have `v1.3.16` of Ionic and there it turns out to be absolutely fine. I tested this on Android 2.3.3 phone as well as emulator with 4.3.

So is it to be done differently with the update? Or there's an issue with it?</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#3813_

**Comment by jbavari** [comment] 2015-05-22 21:01
Just to clarify - are you saying that the apk isnt installed automatically on Android 2.3? Or all emulators?

Also can you please supply `ionic info` information here?

**Comment by JesusMurF** [comment] 2015-05-23 09:03
I have the same problem here with an Android 4.1.2, I have to pass the compiled project to Android Studio and run the app there.

**Comment by keval5531** [comment] 2015-05-23 14:00
@jbavari, on both emulator and devices, so I do not think it is something with Android 2.3.
And here's the output for `ionic info`:
	Your system information:

	Cordova CLI: 5.0.0
	Ionic CLI Version: 1.4.4
	Ionic App Lib Version: 0.0.20
	OS: Windows 7
	Node Version: v0.10.36

**Comment by jbavari** [comment] 2015-05-26 14:14
Yep I am having the same issue with Android 4.1.x.

What happens when you run `cordova run android`? Does it install then? If it does - its an ionic cli issue. If it does not - it is a cordova cli issue.

**Comment by keval5531** [comment] 2015-05-26 14:27
Alright, this looks like Cordova CLI's issue. I just created a sample to test and it's the same there.

**Comment by jorisw** [comment] 2015-05-26 17:10
Same here with Android 4.1.

I can confirm that `cordova run android` also fails to install and run the app. It opens my wall paper chooser instead. The following works just fine after building with cordova:

`adb -d install /path/to/file/generated/by/cordova.apk`

**Comment by jbavari** [comment] 2015-05-26 17:16
I found this link - what do you all think?

http://stackoverflow.com/questions/29956031/cordova-run-android-executes-fine-but-android-4-1-2-doesnt-start-the-app

**Comment by jorisw** [comment] 2015-05-26 17:25
Nice find. Works!

**Comment by keval5531** [comment] 2015-05-27 13:31
Yes, nice find. Thank you. 
Also, shall I report it to Cordova's devs or you've done it already?

**Comment by jbavari** [comment] 2015-05-27 13:58
@keval5531 I was asking some devs internally. Unfortunately, they use JIRA instead of Github. I will find the appropriate channel to report to.

**Comment by keval5531** [comment] 2015-05-27 14:06
Alright. So this can be marked as solved/closed I guess?

**Comment by jbavari** [comment] 2015-05-27 14:07
I'll let you close it if you wish. I'll post the link to the JIRA issue so we can cross reference issues.

**Comment by jbavari** [comment] 2015-05-27 16:21
@keval5531 The issue has been posted as [CB-9080](https://issues.apache.org/jira/browse/CB-9080).

**Comment by keval5531** [comment] 2015-05-28 06:34
Alright. 
And I guess I won't be able to close this, since I am not the initiator, for it was moved from other repo (my bad).I don't know how this works, so I will leave it upto you if this is to be marked as closed or not.

Thank you.

**Comment by julienbrument** [comment] 2015-05-30 01:23
Works !! Thanks

**Comment by dtruel** [comment] 2015-06-14 21:13
Fixed it for me, thank you

**Comment by ssharmass** [comment] 2015-10-16 06:32
Hi,
  Is it possible to install on android 3.0/3.1/3.2 ? I am trying to install but it once open up popup at bottom then , do nothing on all 3.1/3.2.

Regards
Shivam

**Comment by pushpendra996** [comment] 2016-01-11 12:32
my apk file is not running on device with i'm using with network

**Comment by rpayanm** [comment] 2016-04-04 19:50
I has the same issue.
Steps to reproduce:
1. `$ sudo npm install -g ionic@beta`
2. `$ ionic start cutePuppyPics --v2 --ts`
3. `$ ionic serve     # everything good`
4. `$ ionic platform add android`
5. `$ ionic run android`
LAUNCH SUCCESS
In the phone only I can see a white screen.

```
$ ionic info
Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
OS: Distributor ID:     Debian Description:     Debian GNU/Linux 8.3 (jessie) 
Node Version: v4.4.1
```

Phone: Samsung Galaxy S2 T-Mobile - Android 4.1.2

**Closed** 2016-04-04 20:48 UTC

**Comment by jin03192** [comment] 2017-06-19 13:09
a

**Comment by kenjoegolo** [comment] 2019-03-27 11:59
Hi All, I'm still facing this issue, this is my ionic info:

`Ionic:

   ionic (Ionic CLI)             : 4.12.0
   Ionic Framework               : @ionic/angular 4.1.1
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.3

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.1.0, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 12 other plugins)

System:

   Android SDK Tools : 26.1.1 
   NodeJS            : v8.11.3
   npm               : 5.6.0
   OS                : macOS High Sierra`

**Comment by dwieeb** [comment] 2019-03-27 16:18
@kenjoegolo This issue is almost 4 years old. Would you mind opening a new issue and filling out the template?
