### ISSUE TITLE
Not able to start a new project

### ISSUE THREAD

**Issue by Prafulvats2012** [driftyco/ionic-cli#1478] opened 2016-10-06 06:15 UTC
I updated Ionic2 version to V2.1.0 but still I am getting errors while running "npm install --v2 myApp". I am enclosing a screenshot of the procedure which I am following.
![ionic2issue](https://cloud.githubusercontent.com/assets/21354940/19142338/4cd458f8-8bba-11e6-9814-293a5d576b6f.JPG)

**Comment by jgw96** [comment] 2016-10-12 01:35
Hello, thanks for opening an issue with us! I am going to close this one as a duplicate of https://github.com/driftyco/ionic-cli/issues/1491.

**Closed by jgw96** 2016-10-12 01:35 UTC

**Comment by Prafulvats2012** [comment] 2016-10-12 09:55
@jgw96  thanks for helping but its working fine now without making any changes.
