### ISSUE TITLE
There was an error with the spawned command: npminstall

### ISSUE THREAD

**Issue by aweifly** [driftyco/ionic-cli#1145] opened 2016-07-04 07:57 UTC
Downloading: https://github.com/driftyco/ionic-starter-blank/archive/master.zip
[=============================]  100%  0.0s
Installing npm packages...
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined

**Comment by jthoms1** [comment] 2016-07-06 20:48
Closing this as a duplicate of #1013.

**Closed by jthoms1** 2016-07-06 20:48 UTC
