### ISSUE TITLE
Error with start undefined

### ISSUE THREAD

**Issue by raphitz** [driftyco/ionic-cli#1214] opened 2016-07-28 19:41 UTC
Command:
ionic start projectIonic2 blank --v2 --ts

Creating Ionic app in folder C:\dev2\Biblioteca\projectIonic2 based on blank project
Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic2-starter-blank/archive/master.zip
[=============================]  100%  0.0s
Installing npm packages...
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

**Comment by rafatzbr** [comment] 2016-07-29 02:49
Same here

**Comment by rafatzbr** [comment] 2016-07-29 03:00
In order to fix it, 

cd projectIonic2
npm install

all is ok :)

**Comment by jgw96** [comment] 2016-08-08 18:56
Hello! Thanks for opening an issue with us! I will be closing this issue as a duplicate of #1013 . Thanks for using Ionic!

**Closed by jgw96** 2016-08-08 18:56 UTC
