### ISSUE TITLE
could not creeate example project

### ISSUE THREAD

**Issue by thomaskarlrichter** [driftyco/ionic-cli#1188] opened 2016-07-18 13:41 UTC
Creating Ionic app in folder /home/nitrous/myionicappmenu based on sidemenu project
Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic2-starter-sidemenu/archive/master.zip
[=============================]  100%  0.0s
Installing npm packages...
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined
Mind letting us know? https://github.com/driftyco/ionic-cli/issues
nitrous@orange-ghost-167986:~$ ionic --version
2.0.0-beta.32

**Comment by n00b42** [comment] 2016-07-19 23:06
Probably related / duplicate of #1177

**Comment by EPSON-LEE** [comment] 2016-07-21 23:26
+1

**Comment by jthoms1** [comment] 2016-07-25 20:53
This is a duplicate of #1013.

I am closing this issue. It has been kind of a catch all for npm install issues from ionic start. If you are having issues please try running with the verbose flag.

sudo ionic start cutePuppyPics --v2 --verbose

This should provide more insight into what is happening. In most cases it will report issues with network connectivity or permissions issues. If this is not the case please open an issue with your ionic info output.

**Closed by jthoms1** 2016-07-25 20:53 UTC
