### ISSUE TITLE
Windows: `ionic resources` creates invalid paths (for Mac) in config.xml (slash vs. backslash)

### ISSUE THREAD

**Issue by piotrowski** [driftyco/ionic-cli#625] opened 2015-10-22 14:39 UTC
When calling `ionic resources` on Windows from a terminal prompt all the images are correctly generated and config.xml is updated with the new image paths. But as soon as you want to build this on Mac, you get `cp` errors as Mac can't find these paths. Ultimately your app may be built with old images as splash and icon.

Reason for this is that when generating on Windows you get `\` in the paths, on Mac you get `/`. As `/` seems to work on both platforms, `ionic resources` should probably replace `\` by `/` on Windows.

**Comment by philonor** [comment] 2015-12-31 15:11
+1

When using Ionic in combination with PhoneGap Build on Windows, PGB will fail silently to load icons and splashscreens.

**Comment by jakub-g** [comment] 2016-02-11 10:58
+1

Side effect of this is that when you have two developers, one on Windows, one on Linux, every time one of them runs `ionic resources`, there's a big diff in `config.xml` like below due to slashes-to-backslashes conversion or the other way around

    -    <icon src="resources/android/icon/drawable-ldpi-icon.png" density="ldpi"/>
    -    <icon src="resources/android/icon/drawable-mdpi-icon.png" density="mdpi"/>
    -    <icon src="resources/android/icon/drawable-hdpi-icon.png" density="hdpi"/>
    -    <icon src="resources/android/icon/drawable-xhdpi-icon.png" density="xhdpi"/>
    -    <icon src="resources/android/icon/drawable-xxhdpi-icon.png" density="xxhdpi"/>
    -    <icon src="resources/android/icon/drawable-xxxhdpi-icon.png" density="xxxhdpi"/>
    -    <splash src="resources/android/splash/drawable-port-ldpi-screen.png" density="port-ldpi"/>
    -    <splash src="resources/android/splash/drawable-port-mdpi-screen.png" density="port-mdpi"/>
    -    <splash src="resources/android/splash/drawable-port-hdpi-screen.png" density="port-hdpi"/>
    -    <splash src="resources/android/splash/drawable-port-xhdpi-screen.png" density="port-xhdpi"/>
    -    <splash src="resources/android/splash/drawable-port-xxhdpi-screen.png" density="port-xxhdpi"/>
    -    <splash src="resources/android/splash/drawable-port-xxxhdpi-screen.png" density="port-xxxhdpi"/>
    +    <icon src="resources\android\icon\drawable-ldpi-icon.png" density="ldpi"/>
    +    <icon src="resources\android\icon\drawable-mdpi-icon.png" density="mdpi"/>
    +    <icon src="resources\android\icon\drawable-hdpi-icon.png" density="hdpi"/>
    +    <icon src="resources\android\icon\drawable-xhdpi-icon.png" density="xhdpi"/>
    +    <icon src="resources\android\icon\drawable-xxhdpi-icon.png" density="xxhdpi"/>
    +    <icon src="resources\android\icon\drawable-xxxhdpi-icon.png" density="xxxhdpi"/>
    +    <splash src="resources\android\splash\drawable-port-ldpi-screen.png" density="port-ldpi"/>
    +    <splash src="resources\android\splash\drawable-port-mdpi-screen.png" density="port-mdpi"/>
    +    <splash src="resources\android\splash\drawable-port-hdpi-screen.png" density="port-hdpi"/>
    +    <splash src="resources\android\splash\drawable-port-xhdpi-screen.png" density="port-xhdpi"/>
    +    <splash src="resources\android\splash\drawable-port-xxhdpi-screen.png" density="port-xxhdpi"/>
    +    <splash src="resources\android\splash\drawable-port-xxxhdpi-screen.png" density="port-xxxhdpi"/>

so either we have constant noise in the diffs or one of use has to do `git reset --hard` after the build :)

**Comment by youurayy** [comment] 2016-04-28 01:48
Hi, any ETA on this? The offered PR should work.

**Comment by jgw96** [comment] 2016-07-12 19:52
Hello all! I will be closing this issue as a duplicate of https://github.com/driftyco/ionic-cli/issues/913. Thanks for using Ionic!

**Closed by jgw96** 2016-07-12 19:52 UTC
Labels: P3: important, Windows

**Comment by jrobichaud** [comment] 2016-09-01 13:12
@jgw96 I do not believe it is a duplicate of #913. This issue is about the resources being created but with a wrong path ('\' instead of '/').

**Comment by loban** [comment] 2016-11-01 18:23
@jrobichaud is right. This is absolutely NOT a duplicate of #913. In fact, with the backslash, if you run "ionic state restore", it breaks _even on windows_.
