### ISSUE TITLE
RangeError: invalid array length

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-cli#2289] opened 2017-05-15 19:32 UTC
_From @seiyria on March 10, 2017 19:10_

#### Short description of the problem:
Whenever I use `ionic upload`, it fails with this error (during the "uploading snapshot" step):

```
C:\Users\Kyle Kemp\AppData\Roaming\npm\node_modules\ionic\node_modules\@ionic\cli-utils\dist\index.js:23463
  complete = Array(completeLength + 1).join(this.chars.complete);
             ^

RangeError: Invalid array length
    at ProgressBar.render (C:\Users\Kyle Kemp\AppData\Roaming\npm\node_modules\ionic\node_modules\@ionic\cli-utils\dist\index.js:23463:14)
    at ProgressBar.tick (C:\Users\Kyle Kemp\AppData\Roaming\npm\node_modules\ionic\node_modules\@ionic\cli-utils\dist\index.js:23418:8)
    at Task.progress (C:\Users\Kyle Kemp\AppData\Roaming\npm\node_modules\ionic\node_modules\@ionic\cli-utils\dist\index.js:21613:30)
    at uploadSnapshot (C:\Users\Kyle Kemp\AppData\Roaming\npm\node_modules\ionic\dist\ionic.js:8089:28)
    at Request.superagent.post.field.field.on (C:\Users\Kyle Kemp\AppData\Roaming\npm\node_modules\ionic\dist\ionic.js:8065:21)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Transform.progress._transform (C:\Users\Kyle Kemp\AppData\Roaming\npm\node_modules\ionic\node_modules\superagent\lib\node\index.js:860:16)
    at Transform._read (_stream_transform.js:167:10)
    at Transform._write (_stream_transform.js:155:12)
```

#### What behavior are you expecting?
To be able to upload my app.

**Steps to reproduce:**
1. `ionic upload`

**Which @ionic/app-scripts version are you using?**
```
  "devDependencies": {
    "@ionic/app-scripts": "^1.1.0",
    "@ionic/cli-build-ionic-angular": "0.0.3",
    "@ionic/cli-plugin-cordova": "0.0.9",
    "@ionic/cli-utils": "0.0.1-alpha.12e4141f",
    "typescript": "^2.2.1"
  },
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

  Your system information:

    Ionic Framework Version: 2.2.0
    Ionic CLI Version: 3.0.0-beta.4
    ios-deploy version: Not installed
    ios-sim version: Not installed
    OS: Windows 10
    Node Version: v7.3.0
    Xcode version: Not installed

_Copied from original issue: driftyco/ionic-app-scripts#810_

**Comment by jgw96** [comment] 2017-05-15 19:32
_From @brane53 on March 14, 2017 21:20_

I'm having this same issue and I have no idea how to fix it. Same system information except running node v6.9.2

**Comment by jgw96** [comment] 2017-05-15 19:32
_From @seiyria on March 14, 2017 21:20_

I solved this by downgrading, unfortunately.

**Comment by dwieeb** [comment] 2017-05-15 20:31
Hi, the CLI version you were using was ancient. 

Also, duplicate of https://github.com/driftyco/ionic-cli/issues/1984

**Closed by dwieeb** 2017-05-15 20:31 UTC
