### ISSUE TITLE
CLI copy config

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic-cli#745] opened 2016-02-11 15:38 UTC
_From @tlancina on January 22, 2016 19:45_

Right now we provide specific paths for html and fonts, but really there just needs to be a way to copy from a source to a destination.  

_Copied from original issue: driftyco/ionic#5153_

**Comment by Perroquiet** [comment] 2016-02-22 06:57
Also have this issue, but in my case, When I try to install my bower components I put them to `PROJECT_DIR/app/vendor`. If I do: 

>bower install [fontawesome](https://fortawesome.github.io/Font-Awesome/)

Then I'll have my font assets located in `PROJECT_DIR/app/vendor/fontawesome/fonts`
The problem is, these fonts won't be copied to `www/build/fonts` and will display a 404 error when referencing these fonts.

![ionic2fontissue](https://cloud.githubusercontent.com/assets/704556/13211530/f44f6c70-d973-11e5-9169-3a2f0d85b773.PNG)

I also tried copy pasting the fonts to `PROJECT_DIR/app/fonts/` but no luck.

**Comment by Perroquiet** [comment] 2016-02-22 07:09
Finally got it working by just manually copying all my font assets to `www/build/fonts/`. Although, these should be copied automatically in conjunction to using a package manager like bower.

**Comment by jthoms1** [comment] 2016-10-28 01:46
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.

**Closed by jthoms1** 2016-10-28 01:46 UTC
Labels: build, v2
