### ISSUE TITLE
gulp watch doesn't quit (or get killed) when ionic serve is "quit", but does with Ctrl-C

### ISSUE THREAD

**Issue by sbull** [driftyco/ionic-cli#186] opened 2015-01-15 20:24 UTC
I am using gulp.watch in my project, and running with "ionic serve". When I run "ionic serve", and eventually quit using the command "q", the gulp process that ionic kicked off never stops. However, when I quit by pressing Ctrl-C, the gulp process gets killed apparently immediately.

My ionic.project contains:
```
  "gulpStartupTasks": [
    "watch"
  ],
```

and gulpfile.js contains the defaults:
```
gulp.task('sass', function(done) {
  gulp.src('./scss/ionic.app.scss')
    .pipe(sass())
    .pipe(gulp.dest('./www/css/'))
    .pipe(minifyCss({
      keepSpecialComments: 0
    }))
    .pipe(rename({ extname: '.min.css' }))
    .pipe(gulp.dest('./www/css/'))
    .on('end', done);
});

gulp.task('watch', function() {
  gulp.watch(paths.sass, ['sass']);
});
```

I don't think the problem occurs if the "quit" command is used before the "Finished 'watch'" log message is reported.

I had expected that using "quit" would do more cleanup than using Ctrl-C, but it seems that "quit" leaves an abandoned gulp process running, whereas Ctrl-C kills it.

"ionic info":

Your system information:

OS: Distributor ID:     Ubuntu Description:     Ubuntu 12.04.3 LTS
Node Version: v0.10.33
Cordova CLI: 4.1.2
Ionic Version: 1.0.0-beta.13
Ionic CLI Version: 1.3.1

**Comment by jbavari** [comment] 2015-01-16 21:45
I'll be looking into this today.

**Comment by jbavari** [comment] 2015-01-19 21:40
@sbull thanks for reporting. I've committed a fix that should close the process for `gulp` when `quit` is typed in the prompt. Thanks again!

**Closed** 2015-01-19 21:39 UTC

**Comment by flcoder** [comment] 2015-03-07 20:49
Is this published?  I definitely need this fix.  I installed 1.3.2 but fix not in sources.

**Comment by Keyj1n** [comment] 2015-03-29 11:33
OS: Distributor ID:     Ubuntu Description:     Ubuntu 14.04.1 LTS 
Node Version: v0.10.35
Cordova CLI: 4.3.0
Ionic Version: 1.0.0-rc.1
Ionic CLI Version: 1.3.18

i need that fix too!

**Comment by mikehaas763** [comment] 2015-04-20 16:49
:+1:

**Comment by hcentelles** [comment] 2015-04-28 19:24
I'm suffering this issue too, but in my case the gulp task keep running even if I kill `ionic serve`with Cmd+C. My CLI version is 1.3.20

**Comment by jbavari** [comment] 2015-04-28 19:54
The fix is still in place. Could you please supply more information for your use environments? `ionic info`.

**Comment by jbavari** [comment] 2015-04-28 20:07
Woops - I was wrong.The fix is back in place, should be out in the next release.

**Comment by abailey-et** [comment] 2015-05-31 10:06
I'm still having an issue with this. I have Ionic CLI 1.3.19. The issue is after I have it running for sometime (few hours) while I'm editing files. It's weird because I'll use 'q' to quit but if I edit one of the files it was watching and save the file, I see the output of watch task in my console.

It never quits, I have to close terminal window.

**Comment by clmntfrndz** [comment] 2015-11-06 09:35
It looks like it's not corrected yet.

**Comment by ericgopak** [comment] 2016-02-12 18:52
Still happens for me. `ionic info` outputs:

```
Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.1.0
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
OS: Windows 8.1
Node Version: v5.6.0
```

**Comment by Typhox-** [comment] 2016-02-17 02:04
Bug is still there -.- just lost spent 4 hours finding that out...

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
OS: Windows 7 SP1
Node Version: v4.2.4
