### ISSUE TITLE
Error Initializing app: There was an error with the spawned command: npminstall

### ISSUE THREAD

**Issue by nathanbirch** [driftyco/ionic-cli#1491] opened 2016-10-07 19:08 UTC
I am trying to start a new ionic project following [this ](https://scotch.io/tutorials/create-your-first-mobile-app-with-angularjs-and-ionic) tutorial.  When I executed the command, ionic start scotch-todo blank, after several minutes I got the following:

Downloading: https://github.com/driftyco/ionic-app-base/archive/ma
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic-starter-blank/archi
[=============================]  100%  0.0s
Installing npm packages...
Error with start undefined
Error Initializing app: There was an error with the spawned comman
There was an error with the spawned command: npminstall
Caught exception:
 undefined

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

Anyone know why?

In case it helps:
npm -v          - 2.15.9
ionic -v          - 2.1.0
cordova -v     - 6.3.1

**Comment by blackkaiken** [comment] 2016-10-07 22:30
![adsiz11](https://cloud.githubusercontent.com/assets/20086535/19207119/ab2f8fac-8cf6-11e6-94be-de1a9b73008d.png)

Same problem here... Does anyone help us?

**Comment by NealBeat** [comment] 2016-10-08 04:10
i got the same situation!!please help us~

**Comment by perdjurner** [comment] 2016-10-08 12:15
Try installing Git, that fixed it for me:
https://git-scm.com/download

**Comment by nathanbirch** [comment] 2016-10-08 13:00
Hey perdjurner, thanks for your input.  I had already had GIT on my machine, but willing to try anything I installed it again and still got the same error.  Any other ideas?

**Comment by perdjurner** [comment] 2016-10-08 13:05
Unfortunately not.

Seems like a lot of people are having this problem though, so hopefully someone from the Ionic team will have a closer look at it soon.

**Comment by buynowcoupons** [comment] 2016-10-08 15:40
I could create ionic v2 project with this command ionic start app blank --version2 --ts.Please try

Open command prompt as admin and try the command

**Comment by blackkaiken** [comment] 2016-10-08 16:06
@nathanbirch @NealBeat  hi mates, i am workin my back to native-script and android studio. For 10 days i cant solve the problem are you kidding me? also ionic team is irrelavant... they only care about ionicCreator(which means money)

**Comment by nathanbirch** [comment] 2016-10-08 18:25
Still haven't gotten it completely fixed, but I ran the command:

ionic start app_name --v2 --verbose 

and it turned out to be a proxy issue. I removed the proxy using the following commands:

npm config rm proxy
npm config rm https-proxy

and the project at least was created as an ionic project but with the errors:
ERR! git clone
Host key verification failed.
fatal: Could not read from remote repository
Please make sure you have the correct access rights

**Comment by blackkaiken** [comment] 2016-10-08 20:16
i am workin my way back to android studio... Ionic team is an Useless stuff.

**Comment by cianx** [comment] 2016-10-08 21:44
Same issue here:
C:\Users\Cian\Workspaces\ionic>npm -v
2.15.9

C:\Users\Cian\Workspaces\ionic>cordova -v
6.3.1

C:\Users\Cian\Workspaces\ionic>ionic -v
2.1.0

Many errors link this follow:

Running exec command: npminstall
npm

ERR!
 git clone C:\Users\Cian\AppData\Roaming\npm-cache\_git-remotes\git-github-com-driftyco-localforage-cordovasqlitedriver-git-6163d26a C:\Users\Cian\AppData\Local\Temp\npm-7732-f408d49a\git-cache-797f426fa293\9803562a61c2172a69f3475f97e98922c0b49ac0:
 Cloning into 'C:\Users\Cian\AppData\Local\Temp\npm-7732-f408d49a\git-cache-797f426fa293\9803562a61c2172a69f3475f97e98922c0b49ac0'...

**Comment by anjelo1989** [comment] 2016-10-08 22:01
ionic  v2 use npm v 3...update npm
 instal Git
& 
update npm type on cmd ====>>> npm install npm@latest -g

**Comment by SummerOrange** [comment] 2016-10-11 01:41
remount cordova ionic, first  picture is error, second picture is ok.
![we_10 c4xe g5mww dn lop](https://cloud.githubusercontent.com/assets/17867270/19256149/d5716392-8f96-11e6-84e0-214a9c3b7430.png)
![gsese52g zzeo i9_ns994](https://cloud.githubusercontent.com/assets/17867270/19256152/d9f838c8-8f96-11e6-98df-487e5f5cea2a.png)

**Comment by blackkaiken** [comment] 2016-10-11 17:39
of course we use the latest npm also use -g  ..@latest. say sth different mates.

**Comment by jgw96** [comment] 2016-10-12 00:32
Hello all! Do you all have [git](https://git-scm.com/) installed?

**Comment by jgw96** [comment] 2016-10-12 01:53
Hello all! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic-cli/issues/1445. Thanks!

**Closed by jgw96** 2016-10-12 01:53 UTC
Labels: needs_reply

**Comment by XamrinIndian** [comment] 2019-06-19 12:41
hiii
