### ISSUE TITLE
Error with start undefined

### ISSUE THREAD

**Issue by arjancupi** [driftyco/ionic-cli#1496] opened 2016-10-08 14:59 UTC
C:\>ionic start cutePuppyPics --v2
Creating Ionic app in folder C:\cutePuppyPics based on tabs project
Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic2-starter-tabs/archive/master.zip
[=============================]  100%  0.0s
Installing npm packages...
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined

C:\>ionic info

Your system information:

Cordova CLI: 6.3.1
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS:
Node Version: v6.7.0

**Comment by marderary** [comment] 2016-10-09 01:11
same issue on windows 10

**Comment by sebbradol** [comment] 2016-10-09 16:37
same issue

![image](https://cloud.githubusercontent.com/assets/22729983/19222031/72c9c600-8e4f-11e6-90da-1810b94675ed.png)

**Comment by Prashant-Kan** [comment] 2016-10-09 19:37
I have faced the same issue in Windows 10.
I thought Nodejs is not the latestone. I Downloaded and install the latest nodejs and then follow the below link to configure

http://ionicframework.com/docs/v2/getting-started/installation/

But, I failed to install cordova / ionic. Getting the error as attached in the screenshot. Have tried 2-3 times. 

Please anyone with the solution for this. Kindly help.
![ionic_erro](https://cloud.githubusercontent.com/assets/17109022/19223148/ea134cd2-8e85-11e6-80a0-f13291f42118.png)

**Comment by HeathNaylor** [comment] 2016-10-09 22:50
Same problem on Ubuntu 16.04 LTS

Ionic version `2.1.0`.

```
Your system information:

Cordova CLI: You have been opted out of telemetry. To change this, run: cordova telemetry on.
6.3.1

Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS: Distributor ID:	Ubuntu Description:	Ubuntu 16.04.1 LTS 
Node Version: v4.2.6
```

**Comment by Boykar** [comment] 2016-10-11 09:01
I reinstall the latest node, after the installation configuration, after the success of the.

**Comment by jgw96** [comment] 2016-10-12 00:33
Hello all! I am going to close this issue as a duplicate of #1491. Thanks!

**Closed by jgw96** 2016-10-12 00:33 UTC
