### ISSUE TITLE
Error with start undefined

### ISSUE THREAD

**Issue by sharoni3d** [driftyco/ionic-cli#1144] opened 2016-07-03 02:49 UTC
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined

**Comment by jthoms1** [comment] 2016-07-06 20:48
Closing this as a duplicate of #1013.

**Closed by jthoms1** 2016-07-06 20:48 UTC
