### ISSUE TITLE
`ionic login` says: 'Error logging in'

### ISSUE THREAD

**Issue by eshansingh** [driftyco/ionic-cli#994] opened 2016-05-10 12:09 UTC
Seems to have been fixed in #505, but as many others have pointed out, this has once again become an issue in `ionic 2.00-beta.25`. And the only thing it presents is the vague error message "Error logging in".

**Comment by jgw96** [comment] 2016-05-11 21:58
Hello @eshansingh ! We are currently aware of this bug and it should be fixed in the next release. Thanks for using Ionic!

**Closed by jgw96** 2016-05-11 21:58 UTC

**Comment by eshansingh** [comment] 2016-05-24 14:31
Sorry for replying so late - thanks for this! Will do.

**Comment by devillex** [comment] 2016-05-26 07:43
Does this also affect 'ionic upload' ?

We're using Ionic 2.0.0-beta.7 and CLI 2.0.0-beta.25.

We are having issues with CI (on Shippable), where 'ionic upload' failes as follows:
```yml
ionic upload --email $IONIC_EMAIL --password '$IONIC_PASSWORD' 8s  
WARN: No 'upload:before' gulp task found!
If your app requires a build step, you may want to ensure it runs before upload.

No previous login existed. Attempting to log in now.
Error logging in

Email or Password incorrect. Please visit https://apps.ionic.io for help. (CLI v2.0.0-beta.25)

Your system information:

Cordova CLI: 6.2.0
Ionic Framework Version: 2.0.0-beta.7
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
OS: Distributor ID:	Ubuntu Description:	Ubuntu 14.04.3 LTS 
Node Version: v4.4.4
```

**Comment by eshansingh** [comment] 2016-05-26 07:45
@devillex Yes, it does (at least for me, so your thing _might_ be an unrelated issue, but considering how interconnected `ionic login` and `upload` are, it's a far more likely scenario). For now you'll have to wait for the update.

**Comment by jpemesquita** [comment] 2016-06-01 19:30
This is caused by Cloudfare Attention Required page on command line.

**Comment by Goldflow** [comment] 2016-06-07 14:43
so is there a solution for this? if we login in through another command line ?

**Comment by DreamitMauri** [comment] 2016-06-08 06:36
I was finally able to login and upload using a VPN, but still cannot login with the mobile app (Ionic View)
