### ISSUE TITLE
Error with start undefined

### ISSUE THREAD

**Issue by onzinsky** [driftyco/ionic-cli#1160] opened 2016-07-10 11:55 UTC
Just installed ionic v2 using ionic-cli with _npm install -g ionic@beta_ following the _Getting Started With Ionic_ page.

$ ionic start cutePuppyPics --v2
******************************************************
 Dependency warning - for the CLI to run correctly,      
 it is highly recommended to install/upgrade the following:     

 Please install your Cordova CLI to version  >=4.2.0 `npm install -g cordova`
 Install ios-sim to deploy iOS applications.`npm install -g ios-sim` (may require sudo)
 Install ios-deploy to deploy iOS applications to devices.  `npm install -g ios-deploy` (may require sudo)

******************************************************
Creating Ionic app in folder /Users/---/ionic2workspace/cutePuppyPics based on tabs project
Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic2-starter-tabs/archive/master.zip
[=============================]  100%  0.0s
Installing npm packages...
**Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined** 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

**Comment by jthoms1** [comment] 2016-07-11 13:56
Closing as a duplicate of #1013.  If you would like to follow progress please watch that issue.  Thanks!

**Closed by jthoms1** 2016-07-11 13:56 UTC
