### ISSUE TITLE
v3: Wrong path for generated providers

### ISSUE THREAD

**Issue by MTechDE** [driftyco/ionic-cli#2164] opened 2017-04-27 08:24 UTC
#### What version of the CLI are you using? Output of `ionic --version`
Beta 9

#### Short description of the problem:
When I create a new provider by running ionic generate provider MyApi the CLI generates it well but imports the wrong path in the app.module.ts. 
`
import { StorageProvider } from '..\providers\storage/storage';`

#### What behavior are you expecting?

The correct path should look like this:
`
import { StorageProvider } from '../providers/storage/storage';`

**Steps to reproduce:**
1. Create a new Ionic project
2. Run ionic generate provider MyApi
3. Check the app.module.ts

### Ionic info

```
npm (global):

    @ionic/cli-utils : 1.0.0-beta0
    cordova          : 6.5.0 
    ionic            : 3.0.0-beta9

npm (local):

    @ionic/app-scripts              : 1.3.4
    @ionic/cli-plugin-cordova       : 1.0.0-beta0
    @ionic/cli-plugin-ionic-angular : 1.0.0-beta0
    Ionic Framework                 : ionic-angular 3.1.0

System:

    Node       : v7.9.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002 
    ios-deploy : not installed
    ios-sim    : 5.0.13 
```

**Comment by dwieeb** [comment] 2017-04-27 14:41
Thanks for letting us know. This is a duplicate of https://github.com/driftyco/ionic-cli/issues/2150

The next version of app scripts will fix this issue.

**Closed by dwieeb** 2017-04-27 14:41 UTC
