### ISSUE TITLE
bug: ionic commands gives current working directory is not a Cordova-based project

### ISSUE THREAD

**Issue by perrygovier** [driftyco/ionic-cli#346] opened 2015-04-01 15:29 UTC
_From @aelx311 on March 31, 2015 22:36_

**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>browser</span>

<span ionic-description>Hi,

I updated ionicCLI to 1.3.18 and I am having issues building and running my app.

I tried ionic start myapp blank, a new directory was created but I got this:
![capture](https://cloud.githubusercontent.com/assets/3267257/6930774/dd9c36f2-d7cb-11e4-8463-d7eec6fa103a.PNG)
I am pretty sure that my Cordova is the latest version.

I did cordova create . as suggested in http://ionicframework.com/docs/ionic-cli-faq/#plugins but no luck.
![capture2](https://cloud.githubusercontent.com/assets/3267257/6930793/14dfc4c6-d7cc-11e4-9957-faa6640df79d.PNG)

As you can see, config.xml does exists in the directory.
![capture3](https://cloud.githubusercontent.com/assets/3267257/6930817/64eb7f1e-d7cc-11e4-8521-eafbab392c9c.PNG)

All are working fine until I updated ionicCLI to 1.3.18.

Any advice is very much appreciated.</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#3446_

**Comment by softBarbarian** [comment] 2015-04-02 00:00
@aelex311 what happens if you run your command line prompt as administrator?

**Comment by aelx311** [comment] 2015-04-02 13:59
@softBarbarian I tried it and it was giving me the same error saying my Cordova is too old.

**Comment by aelx311** [comment] 2015-04-02 14:15
I tried to do 'ionic setup sass' and I got the following error. I notice npm path is not in the correct directory.
![ionic1](https://cloud.githubusercontent.com/assets/3267257/6965474/4fcbefb4-d917-11e4-82c1-7fd869aa9a1d.PNG)

Also, I downloaded Git Bash. <b>ionic start myapp</b> is still throwing the same error but I am able to do <b>ionic platform add android</b>, <b>ionic build android</b> and <b>ionic run android</b>

**Comment by jbavari** [comment] 2015-05-14 21:31
Would you please try this again with latest (1.4.0) and verify it is still an issue?

**Comment by aelx311** [comment] 2015-05-18 15:13
@jbavari I updated to 1.4.3 and the issue is fixed.

**Comment by jbavari** [comment] 2015-05-18 15:18
@aelx311 thanks for the feedback. Closing the issue. Enjoy!

**Closed by jbavari** 2015-05-18 15:18 UTC
Labels: bug, Windows
