### ISSUE TITLE
ionic platform add - not allowing dashes in package name

### ISSUE THREAD

**Issue by wkande** [driftyco/ionic-cli#1159] opened 2016-07-09 12:17 UTC
Earlier versions allowed dashes in the package name but the latest version does not for Android.  IOS works with the dashes. If I remove the dash it works OK.

config.xml
```< widget id="com.wyomingsoftware.git-mobile" ... />```

```
### Ionic ###
Warrens-Mac-mini:git-mobile warren$ ionic platform add  android
Adding android project...

Error: Error validating package name. Package name must look like: com.company.Name

Caught exception:
 undefined 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues


### Cordova ###
Warrens-Mac-mini:git-mobile warren$ cordova platform add  android
Adding android project...
Error: Error validating package name. Package name must look like: com.company.Name
```

**Comment by jthoms1** [comment] 2016-07-11 13:57
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.

**Comment by wkande** [comment] 2016-07-11 14:19
```
Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: 1.8.5 
ios-sim version: 4.1.1 
OS: Mac OS X El Capitan
Node Version: v4.4.0
Xcode version: Xcode 7.3.1 Build version 7D1014 
```

I looked at this some more and it may be a cordova 6.x thing. For IOS it allows the dash but Android not. I worked around this by changing my config.

```
OLD: Fails because Android uses the ID with the dash
<widget id="com.wyomingsoftware.git-mobile" version="0.9.3" ios-CFBundleVersion="0.9.3" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">


NEW: Works because Android uses the android-packageName rather than ID
<widget id="com.wyomingsoftware.gitmobile" android-packageName="com.wyomingsoftware.git-mobile" ios-CFBundleIdentifier="com.wyomingsoftware.git-mobile" version="0.9.3" ios-CFBundleVersion="0.9.3" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
```

By declaring the android-packageName and removing the dash from the ID it works.  I read somewhere where older versions of "cordova platform add" replaced the dash silently with an underscore.

**Comment by jgw96** [comment] 2016-07-12 18:42
Hello! Since this seems to be an issue with cordova 6.x and not the ionic cli i will be closing this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-07-12 18:42 UTC

**Comment by Ricard** [comment] 2017-04-27 14:44
Although it is related to Cordova... I have to add:
package **names starting with numbers are not accepted** by Cordova 6.5, I.E.
<widget id="com.ricard.1name"

Reproduced in:
Cordova CLI: 6.5.0
Ionic Framework Version: 3.1.0
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.5
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v7.8.0

**Comment by 2bitcoders** [comment] 2017-09-08 17:08
Seconding the issue with not allowing for names not starting with numbers in the namespace.

using something like com.2bitcoders.package will create this issue...
