### ISSUE TITLE
Need --noresources for "ionic browser add crosswalk"

### ISSUE THREAD

**Issue by zarko-tg** [driftyco/ionic-cli#356] opened 2015-04-07 08:37 UTC
So, --noresources was recently added as an option for the **platform** command.
What if one wants to achieve the same i.e. prevent the default Ionic resources being added for a Crosswalk platform/browser?
Currently the Ionic resources are always added when running
ionic browser add crosswalk

___
System information:

OS: Mac OS X Yosemite
Node Version: v0.12.2
Cordova CLI: 4.3.0
Ionic Version: 1.0.0-beta.14
Ionic CLI Version: 1.3.19
Xcode version: Xcode 6.2 Build version 6C131e 
ios-sim version: 3.1.1 
ios-deploy version: 1.5.0

**Comment by lydell** [comment] 2015-04-08 12:00
Duplicate of #333.

**Comment by jbavari** [comment] 2015-05-08 21:34
This is updated i the latest beta.

Try it out - `npm install -g ionic@beta` - it should value the `--noresources` flag.

**Closed by jbavari** 2015-05-08 21:34 UTC
