### ISSUE TITLE
ionic 2 error when creating a new project

### ISSUE THREAD

**Issue by doctor-mostafa79** [driftyco/ionic-cli#1463] opened 2016-10-04 07:56 UTC
I installed the release candidate. I updated node.js and npm. 
When I start a new project, I get this error:

Installing npm packages...
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined

I uninstalled cordova and ionic and cleaned npm and then installed everything back, but no matter I did, I still get the same error every time I try to create a new project

Any help

![screenshot_1](https://cloud.githubusercontent.com/assets/15583026/19067340/e99ee7be-8a1d-11e6-9097-c245d2c3dbfe.png)

**Comment by jdat82** [comment] 2016-10-04 09:54
It may help them to have some info about your environment like the version of npm and ionic-cli plus the OS (name and version) too. Things like that… 

Nonetheless this is a good example of why the `ionic start` command should not make `npm install` itself. Its job should be to generate code, end of story, not install all dependencies. It would be more align with the single responsibility principle. 

This is a single line command that we can type next after generating the project. I say that because it makes the execution time very long especially on slow networks which can be very frustrating if you want to execute it several times for instance to see generated code for several templates or with different options. Just because you generate code doesn't mean you will execute it.

**Comment by HectorFGarcia** [comment] 2016-10-04 13:24
I'm having the same problem after remove beta and install RC0. 

I'm using npm 3.8.6 on Win7.

**Comment by jthoms1** [comment] 2016-10-04 13:59
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.

**Comment by HectorFGarcia** [comment] 2016-10-04 14:11
After read [https://github.com/driftyco/ionic-cli/issues/1424](url) I discovered, checking with --verbose, that I haven't installed "git for Windows'. Now it works.

**Comment by iammash** [comment] 2016-10-04 14:35
Similar problem here. npm version 3.10.3, Node.js 6.7.0, win 7 x64, ionic version 2.1.0. Problem came after i uninstalled previous ionic and installed the RC.

**Comment by klaus-kuplen** [comment] 2016-10-04 20:08
Exact same issue here
Windows 10, first-time ionic install just followed the directions to the letter and it failed.
Company PC with windows 7, also vanilla install, also failed.

Solution: install Git for windows.

Please update your dependencies.

As a first time user I was very annoyed.

**Comment by iammash** [comment] 2016-10-05 06:35
Installing Git resolved it for me too.

**Comment by firescout** [comment] 2016-10-05 07:43
`npm upgrade` solved this for me

**Comment by zuhairHussain** [comment] 2016-10-05 07:53
@jtoms1 
![err](https://cloud.githubusercontent.com/assets/15627521/19105297/b1f431c4-8afa-11e6-9c13-3edcec8afb65.png)

**Comment by doctor-mostafa79** [comment] 2016-10-08 10:29
Unfortunately, I formatted my computer and installed a fresh win 10 on it. I will try installing git for windows, may be it works for me. 
Thanks for the help.

**Comment by doctor-mostafa79** [comment] 2016-10-10 12:02
I installed Git for windows as recommended here from other members and everything works fine now. This info should be clear in ionic 2 RC0 documentations.

**Comment by jgw96** [comment] 2016-10-12 01:42
Hello all! Going to close this as a duplicate of https://github.com/driftyco/ionic-cli/issues/1491. Thanks!

**Closed by jgw96** 2016-10-12 01:42 UTC
Labels: npm install
