### ISSUE TITLE
Warning with Cordova 6.1

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic-cli#859] opened 2016-03-24 14:30 UTC
Cordova-cli 6.1 was released yesterday and causes warnings to appear in the CLI

```
ionic info
WARN: ionic.config.js has been deprecated, you can remove it.

Your system information:

Cordova CLI: 6.1.0 (cordova-lib@undefined)
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Version: 1.2.4
Ionic CLI Version: 2.0.0-beta.22
Ionic App Lib Version: 2.0.0-beta.12
ios-deploy version: 1.8.5
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v5.9.0
Xcode version: Xcode 7.3 Build version 7D175


******************************************************
 Dependency warning - for the CLI to run correctly,
 it is highly suggested to install/upgrade the following:

 Please install your Cordova CLI to version  >=4.2.0 `npm install -g cordova`

******************************************************
```

**Comment by nunoarruda** [comment] 2016-03-25 03:37
Yeah, same here. CLI throws a warning even if cordova 6.1.0 is already installed.
<img width="697" alt="screen shot 2016-03-25 at 11 33 57" src="https://cloud.githubusercontent.com/assets/1189149/14037354/aae9e9fc-f27d-11e5-83a5-d2e215992d02.png">

**Comment by richmoh** [comment] 2016-03-28 08:31
@mhartington @nunoarruda You've probably already done this but I found that downgrading fixed the issue for me...

`npm remove -g cordova`

`npm install -g cordova@6.0.x`

I was unable to add crosswalk before doing this.

**Comment by anupam42** [comment] 2016-03-28 10:47
me also facing the same issue sir @richmoh  by removing cordova and installing with cordova 6.0.x is it fix the issue ?

**Comment by richmoh** [comment] 2016-03-28 13:51
Yes

**Comment by cindymarie** [comment] 2016-03-30 06:49
Same issue here. T-T"

While downgrading cordova to 6.0.0, an `npm` warning came up:

`npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and now out of date with respect to npm.`

**Comment by lobo87** [comment] 2016-03-31 18:00
i had a look into it, seems like "cordova -v", which is being called to gather the needed info, is not returning "6.1.0" as expected. it's "6.1.0 (cordova-lib@undefined)".

semvar.satisfies() now cant validate that in a correct manner and is returning false, which is obviously wrong. ;)

However, as far as i know, since cordova cli 5.0 "ionic browser add crosswalk" is not needed in order to install crosswalk. For a temporary workaround you could also execute these commands:

cordova platform add android
cordova plugin add cordova-plugin-crosswalk-webview
cordova plugin add cordova-plugin-whitelist
cordova plugin add cordova-plugin-splashscreen

Please correct me if I'm wrong, but this is basically the same as the "ionic browser add crosswalk" command does in the script if cordova cli is >=5.0.0

**Comment by nunoarruda** [comment] 2016-04-03 10:02
This looks fixed now with the latest version(s)...
<img width="697" alt="screen shot 2016-04-03 at 19 00 31" src="https://cloud.githubusercontent.com/assets/1189149/14231868/7ba2fd84-f9ce-11e5-8a9f-3536b69ed858.png">

**Comment by lobo87** [comment] 2016-04-04 09:37
yes, this seems to be fixed with 6.1.1.

**Comment by jgw96** [comment] 2016-05-02 19:08
Hello all! As this seems to have been fixed in cordova 6.1.1 i will be closing this issue for now. Thanks for using Ionic!

**Closed by jgw96** 2016-05-02 19:08 UTC
Labels: platform:ios, v1

**Comment by jabas06** [comment] 2016-06-10 23:46
Hi, I'm facing the same issue but with the last cordova version 6.2 on Windows

![image](https://cloud.githubusercontent.com/assets/3453385/15981471/9b654472-2f3b-11e6-89d9-8b4ccd2c87cb.png)

**Comment by merolhack** [comment] 2016-06-27 20:37
You can disable telemetry to solve this issue:
```
$ cordova telemetry on
$ cordova telemetry off
$ cordova build --no-telemetry
```
And now:
```
$ cordova -v
6.2.0
```
The problem is fixed:
```
$ ionic info

Your system information:

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
OS: Windows 7 SP1
Node Version: v5.3.0
```
Source:
**You have been opted out of telemetry, what?**
https://medium.com/@appplumbr/you-are-encountering-this-issue-as-apache-cordova-in-their-latest-release-added-telemetry-to-d03732719dc1#.ur2bhalx0

**Comment by markmnl** [comment] 2016-10-06 05:27
Same here today with fresh install of cordova and ionic when start new project on Windows.

Presumably there isn't actually an issue apart from the warning?

**Comment by codermahesh** [comment] 2016-11-27 11:34
Hi guys, this problem persists on cordova 6.4.0 and Ionic Framework 2.0.0
Ionic CLI 2.1. on windows Node 6.7.0. Is there any possible workaround? 

@mhartington  I am curious if you guys have any plans towards Officially dockerizing
toolchain [not necessarily free :) ].

**Comment by jigs1212** [comment] 2016-12-06 05:46
Had the same issue.

Your system information:

Cordova CLI: 6.4.0 
Ionic CLI Version: 2.1.14
Ionic App Lib Version: 2.1.7
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.8
Node Version: v7.2.0
Xcode version: Not installed

Tried the commands suggested by @merolhack and it worked.
Maybe this helps to solve.
Thank you.

**Comment by ScreamZ** [comment] 2017-01-15 17:41
Same problem with cordova 6.4 ......

**Comment by jpickwell** [comment] 2017-01-24 15:03
Cordova when first installed asks for permission to send anonymous statistics. This question is causing the warning. Follow @merolhack's comment above.
