### ISSUE TITLE
erro in cli 

### ISSUE THREAD

**Issue by stanghelle** [driftyco/ionic-cli#1065] opened 2016-06-11 18:14 UTC
Creating Ionic app in folder /Users/tom/simplehours based on blank project
Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic2-starter-blank/archive/master.zip
Installing npm packages...
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined

**Comment by ihadeed** [comment] 2016-06-13 07:57
I just experienced the same issue.

![image](https://cloud.githubusercontent.com/assets/13794420/16000291/83c38ab0-3119-11e6-9152-709fa37f3f5a.png)

Seems like it failed in the process of installing node modules. So I went inside the directory `myapp`, deleted `node_modules` and ran the command `npm install` to install the dependencies from the beginning. Then this happened:
![image](https://cloud.githubusercontent.com/assets/13794420/16000540/f1407688-311a-11e6-9c3f-3ec9e5fa9977.png)


..

I'm only experiencing this issue on Ubuntu. No issue with my local Windows 10 machine.

**Comment by jthoms1** [comment] 2016-06-14 21:34
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.

**Comment by jthoms1** [comment] 2016-06-14 21:52
Could you try running the command with the verbose flag?  I have a feeling that everyone is receiving this same issue due to node-sass.

`ionic start cutePuppyPics --verbose`

**Comment by ihadeed** [comment] 2016-06-20 12:01
My problem seemed to be a RAM problem. I was trying to start my app on a server with only 512MB of RAM. The large amount of NPM installs requires more RAM to successfully install. Other option is to install packages manually in smaller batches. 

So I think to fix this issue, the build process has to install NPM modules in smaller chunks rather than installing everything at once.

**Comment by 3dd13** [comment] 2016-06-26 10:52
there are few things you need to do to upgrade / update

1. upgrade nodejs

        brew upgrade node

2. upgrade npm

        npm install -g npm

3. set new registry

        npm set registry http://registry.npmjs.org

**Comment by jthoms1** [comment] 2016-07-06 20:47
Closing this as a duplicate of #1013.

**Closed by jthoms1** 2016-07-06 20:47 UTC
Labels: npm install
