### ISSUE TITLE
app stuck on splashscreen when using livereload

### ISSUE THREAD

**Issue by sfabriece** [driftyco/ionic-cli#1032] opened 2016-06-02 21:12 UTC
When I use xcode to run my app, it works. But when i use the terminal for livereload, the app gets stuck on the splashscreen.

```
ionic run android  --address localhost -l -c
```
Is there anything that I should be doing when using livereload? Thanks

**Comment by jthoms1** [comment] 2016-06-08 14:08
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.

**Comment by jetbalagtas** [comment] 2016-06-24 18:35
hi @jthoms1, i'm experiencing the same thing for iOS
here is my system info from running `ionic info`:
```
Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.3.1
Ionic CLI Version: 1.7.16
Ionic App Lib Version: 0.7.3
ios-deploy version: 1.8.6
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v5.11.1
Xcode version: Xcode 7.3.1 Build version 7D1014
```

thanks in advance

**Comment by sfabriece** [comment] 2016-06-24 18:59
my info

```
Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.9
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v5.11.1
Xcode version: Xcode 7.3.1 Build version 7D1014 
```

**Comment by jetbalagtas** [comment] 2016-06-24 20:15
@sfabriece, not sure if this will work for you but it worked for me
1. ensure you have the `cordova-plugin-whitelist` installed with `cordova plugin add`
2. insert `<allow-navigation href="localhost*"/>` into your `config.xml` file
3. then `ionic emulate ios --target="iPhone-5" -l --address localhost` to be sure it looks for localhost
(you can add other flags like the "-l" before it)
found the solution here:
https://forum.ionicframework.com/t/solved-ionic-run-doesnt-work-but-xcode-run-works-live-reload-problem/49191/3

**Comment by sfabriece** [comment] 2016-06-25 14:20
Thanks @jetbalagtas I'll have a look.

**Comment by jgw96** [comment] 2016-07-12 19:59
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-07-12 19:59 UTC

**Comment by shamilovtim** [comment] 2018-05-19 14:31
Experiencing the same issue on iOS and Ionic 3 only when using cordova run with livereload. if i don't use livereload it doesn't hang.

**Comment by jugbeep** [comment] 2019-03-06 17:15
> I had a similar problem, the solution was very simple for me: I turned my smartphones' WIFI on. 🤪

This solution worked for me, but I'm wondering what the root of the cause is. Is there a way to prevent that from happening?
