### ISSUE TITLE
Ionic 2 Won't run in Android 5.0 or earlier

### ISSUE THREAD

**Issue by felsf** [driftyco/ionic-cli#958] opened 2016-04-25 17:08 UTC
A whitescreen is shown and nothing happens.
Debugged and I got it:

`Uncaught TypeError: Cannot call method 'bind' of undefined at file:///android_asset/www/build/js/app.bundle.js:61557`

So won't it work earlier than 5.0?

**Comment by tlancina** [comment] 2016-04-25 17:26
Do you have es6-shim? https://github.com/driftyco/ionic2-starter-tabs/blob/master/www/index.html#L22

**Comment by felsf** [comment] 2016-04-25 18:22
No, I don't.

**Comment by mehrad-rafigh** [comment] 2016-04-26 07:05
I have the es6-shim in my index.html but the ionic 2 app is not running on my Samsung Galaxy S3 with Android 4.3, albeit is it running on my Moto with Android 6. Any clues?

**Comment by jgw96** [comment] 2016-05-02 17:09
@mehrad-rafigh Hello! Thanks for opening an issue with us! Although we support Android all the way back to Android 4.2, we do recommend using Crosswalk if you plan on supporting Android devices older than 4.4.4. The webview that is in Android < 4.4.4 lacks good html5 support which causes issues with Ionic 2 and is also pretty slow by todays standard. By using Crosswalk you can guarantee that your app will have great performance and work even on versions of Android as old as 4.2.

**Comment by felsf** [comment] 2016-05-02 17:12
Hello @jgw96.
The problem is not performance, the problem is running the app. It doesn't even runs.
It show this error on logcat. Android 4.2.2 emulator and real device

`Uncaught TypeError: Cannot call method 'bind' of undefined at file:///android_asset/www/build/js/app.bundle.js:61557`

**Comment by jgw96** [comment] 2016-05-02 17:17
@felsf Hello! So as i stated above, before Android 4.4 android used a different webview which did not have good html5 support, this means that Ionic 2 apps have issues running on devices older than 4.4. This is why we recommend using Crosswalk if you plan on supporting versions of Android older than 4.4. With Crosswalk, Ionic 2 works great all the way back to Android 4.2 (: So to fix your issue i would recommend adding Crosswalk to your app, which you can learn to do here: http://ionicframework.com/docs/cli/browsers.html ! Thanks for using Ionic!

**Comment by felsf** [comment] 2016-05-02 17:20
@jgw96 Hello! It means I'll have to have two app version? A crosswalk one and a without crosswalk one? How would it work in google play store? 

Using crosswalk it compiles a armv7 and x86 version, both above 20mb. Which one is "crosswalked" ?

**Comment by jgw96** [comment] 2016-05-02 17:28
Sorry i should have been clearer. Crosswalk also works on brand new android devices, and since crosswalk is using a very up to date version of chromium, you do not lose any of the advantages of the new webviews in newer Android devices. This means that you still only have one apk that works across all Android devices. Also, both of the apk's that it compiles (the arm and x86 one) are using crosswalk, there just compiled for different CPU architectures. The one you would want to release on Google Play would be the armv7 one, as basically every Android device available is an arm device ( really almost every mobile device available, from ios to Android to Firefox OS to Ubuntu).

**Comment by felsf** [comment] 2016-05-02 17:46
@jgw96  I understood, very cool. Btw I get that running armv7 version

[img]http://i.imgur.com/vPRdnFB.png[/img]

**Comment by felsf** [comment] 2016-05-02 17:50
@jgw96 For the first time it ran, I think it wasn't installing correctly on "ionic run android", now I installed by double clicking on the apk file (andy emulator).

But everything is grey, look at this

The overlay is my sidemenu 

http://i.imgur.com/YmxWCwJ.png

**Comment by jgw96** [comment] 2016-05-02 20:41
@felsf Do you get the same results on an actual device?

**Comment by rosdi** [comment] 2016-05-12 04:29
Hi,

I am having similar problem... my app will only run on android API level 19 and up despite setting min sdk version to 16.

So I did this: 

`ionic plugin add cordova-plugin-crosswalk-webview`
`ionic build android`
and finally `ionic run android -l -c`

but I am getting the same error... I posted a question here: https://forum.ionicframework.com/t/what-is-the-minimum-android-api-level-for-ionic-2/51822

**Comment by jgw96** [comment] 2016-05-12 15:03
@rosdi Are you loading in es6-shim?

**Comment by rosdi** [comment] 2016-05-12 23:17
@jgw96 Yes, I do have es6-shim in index.html. It is a standard Ionic 2 project based on side menu template.

**Comment by jgw96** [comment] 2016-07-12 19:31
Hello all! Is this still an issue with the latest version of ionic? Thanks!

**Comment by rosdi** [comment] 2016-07-13 01:28
@jgw96 This has been fixed since Beta 7 (the last version I upgraded to). Haven't had the time to update to the latest beta though....

I consider this solved... I will update if there is regression in the latest Ionic.

Thanks.

**Comment by jgw96** [comment] 2016-07-13 15:55
Thanks @rosdi . I cant reproduce this issue with the latest release either so i will be closing this issue for now. Thanks for using ionic!

**Closed by jgw96** 2016-07-13 15:55 UTC
Labels: needs_reply

**Comment by jayzzz00** [comment] 2017-09-01 12:26
cli packages: (/home/jays/.nvm/versions/node/v7.1.0/lib/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1 
    Gulp CLI    : not installed globally

local packages:

    Cordova Platforms : android 6.2.3
    Ionic Framework   : ionic1 1.3.3

System:

    Node : v7.1.0
    npm  : 3.10.9 
    OS   : Linux 4.4

my system confiuration for ionic project when i run my project it can run in android api 20 to 25 but not launch in lower version in android please help me .....@rosdi @jgw96

**Comment by DennisMenjivar** [comment] 2018-06-15 20:55
I need to know what is the solution about this problem, because I'm confused, I need to run my ionic android aplication in version 4.2.2 Please help me..

**Comment by DennisMenjivar** [comment] 2018-06-15 20:55
<plugin name="cordova-plugin-whitelist" spec="1.3.3" />
    <plugin name="cordova-plugin-device" spec="2.0.2" />
    <plugin name="cordova-plugin-splashscreen" spec="5.0.2" />
    <plugin name="cordova-plugin-ionic-webview" spec="1.1.19" />
    <plugin name="cordova-plugin-ionic-keyboard" spec="2.0.5" />
    <plugin name="cordova-sqlite-storage" spec="^2.3.2" />
    <plugin name="cordova-plugin-x-socialsharing" spec="^5.4.0" />
    <plugin name="cordova-clipboard" spec="^1.2.1" />
    <engine name="ios" spec="4.5.4" />
    <engine name="android" spec="7.0.0" />

**Comment by DennisMenjivar** [comment] 2018-06-15 20:56
<plugin name="cordova-plugin-whitelist" spec="1.3.3" />
    <plugin name="cordova-plugin-device" spec="2.0.2" />
    <plugin name="cordova-plugin-splashscreen" spec="5.0.2" />
    <plugin name="cordova-plugin-ionic-webview" spec="1.1.19" />
    <plugin name="cordova-plugin-ionic-keyboard" spec="2.0.5" />
    <plugin name="cordova-sqlite-storage" spec="^2.3.2" />
    <plugin name="cordova-plugin-x-socialsharing" spec="^5.4.0" />
    <plugin name="cordova-clipboard" spec="^1.2.1" />
    <engine name="ios" spec="4.5.4" />
    <engine name="android" spec="7.0.0" />

**Comment by DennisMenjivar** [comment] 2018-06-15 20:56
'<plugin name="cordova-plugin-whitelist" spec="1.3.3" />
    <plugin name="cordova-plugin-device" spec="2.0.2" />
    <plugin name="cordova-plugin-splashscreen" spec="5.0.2" />
    <plugin name="cordova-plugin-ionic-webview" spec="1.1.19" />
    <plugin name="cordova-plugin-ionic-keyboard" spec="2.0.5" />
    <plugin name="cordova-sqlite-storage" spec="^2.3.2" />
    <plugin name="cordova-plugin-x-socialsharing" spec="^5.4.0" />
    <plugin name="cordova-clipboard" spec="^1.2.1" />
    <engine name="ios" spec="4.5.4" />
    <engine name="android" spec="7.0.0" />'

**Comment by DennisMenjivar** [comment] 2018-06-15 20:57
--<plugin name="cordova-plugin-whitelist" spec="1.3.3" />
    --<plugin name="cordova-plugin-device" spec="2.0.2" />
    --<plugin name="cordova-plugin-splashscreen" spec="5.0.2" />
    --<plugin name="cordova-plugin-ionic-webview" spec="1.1.19" />
    --<plugin name="cordova-plugin-ionic-keyboard" spec="2.0.5" />
    --<plugin name="cordova-sqlite-storage" spec="^2.3.2" />
    --<plugin name="cordova-plugin-x-socialsharing" spec="^5.4.0" />
    --<plugin name="cordova-clipboard" spec="^1.2.1" />
    --<engine name="ios" spec="4.5.4" />
    --<engine name="android" spec="7.0.0" /
