### ISSUE TITLE
execute ionic start MyProject sidemenu --v2 failure

### ISSUE THREAD

**Issue by C0160** [driftyco/ionic-cli#1195] opened 2016-07-21 06:15 UTC
execute ionic start MyProject sidemenu --v2 failure

Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic2-starter-sidemenu/archive/master.zip
[=============================]  100%  0.0s
Installing npm packages...
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined

**Comment by jthoms1** [comment] 2016-07-25 20:53
This is a duplicate of #1013.

I am closing this issue. It has been kind of a catch all for npm install issues from ionic start. If you are having issues please try running with the verbose flag.

sudo ionic start cutePuppyPics --v2 --verbose

This should provide more insight into what is happening. In most cases it will report issues with network connectivity or permissions issues. If this is not the case please open an issue with your ionic info output.

**Closed by jthoms1** 2016-07-25 20:53 UTC

**Comment by amitsarma** [comment] 2016-09-28 11:51
when i write
ionic start cutePuppyPics --v2 --verbose
we got error in cmd
npm ERR!
 Windows_NT 10.0.10240
npm ERR! argv "D:\\NodeFolder\\node.exe" "C:\\Users\\hp\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.6.0
npm ERR! npm  v3.10.8
npm ERR! code ENOGIT



npm ERR! not found: git
npm ERR!
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.



npm ERR! Please include the following file with any support request:
npm ERR!     E:\SocialLoginDemo\helloworl13\npm-debug.log

**Comment by amitsarma** [comment] 2016-09-28 11:53
Spawn command completed
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined

**Comment by amitsarma** [comment] 2016-09-28 11:53
my ionic version
You have been opted out of telemetry. To change this, run: cordova telemetry on.
6.3.1

Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS:
Node Version: v4.6.0
