### ISSUE TITLE
Caught exception:  Error: No whitespace between attributes Line: 5

### ISSUE THREAD

**Issue by mohammadmoussa** [driftyco/ionic-cli#1140] opened 2016-07-01 07:48 UTC
Hi, every time im trying to build my ionic 2 application android or ios im getting this error:

Caught exception:
 Error: No whitespace between attributes
Line: 5
Column: 17
Char: i
    at error (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/xml2js/node_modules/sax/lib/sax.js:667:10)
    at strictFail (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/xml2js/node_modules/sax/lib/sax.js:693:7)
    at Object.write (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/xml2js/node_modules/sax/lib/sax.js:1408:13)
    at Parser.exports.Parser.Parser.parseString (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/xml2js/lib/xml2js.js:503:31)
    at Parser.parseString (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/xml2js/lib/xml2js.js:7:59)
    at Object.exports.parseString (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/xml2js/lib/xml2js.js:535:19)
    at /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/config-xml.js:21:12
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3) 

Any help please!

**Comment by jgw96** [comment] 2016-07-12 18:53
Hello! Thanks for opening an issue with us! Could you post the output of `ionic info` here please? Thanks for using Ionic !

**Comment by jgw96** [comment] 2016-07-19 14:21
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-07-19 14:21 UTC
Labels: needs reply

**Comment by mperroul** [comment] 2016-09-28 20:34
It's closed, but I had the same problem and correct the parsing problem by checking my config.xml file, I had a bad " in it dues to changing the file with textedit which change the " to a  »

Hope this help

**Comment by sunilrawat123** [comment] 2018-04-30 06:54
They are simply closing the issue, without fixing them

**Comment by dwieeb** [comment] 2018-04-30 14:57
@sunilrawat123 Keep the comments constructive, please. Review our code of conduct: https://github.com/ionic-team/ionic/blob/master/CODE_OF_CONDUCT.md

This isn't something we can "fix" because it's not a bug. This error occurs when the `config.xml` file cannot be parsed due to a syntax error. The error message explains at which line and column number the syntax mistake was found. It must be fixed manually.
