### ISSUE TITLE
bug: TypeScript files (.ts ext) not in compile context

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic-cli#741] opened 2016-02-11 15:36 UTC
_From @danbucholtz on February 10, 2016 20:33_

**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When I create a new .ts file, for example, "Todo.ts" that exports a class called Todo, VSCode and Atom are giving me errors about how "Todo.ts" is not included in the TypeScript compilation context.  The tsconfig.json file glob is not set-up correctly.</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#5397_

**Comment by adamdbradley** [comment] 2016-02-11 15:36
_From @danbucholtz on February 11, 2016 0:2_

in app/Todo.ts
`export class Todo{
}`

**Comment by tlancina** [comment] 2016-02-11 17:29
The TypeScript compiler is only aware of the files in the `files` array in `tsconfig.json` and those files' dependencies. The Ionic starters by default only include `app/app.ts`, whose dependencies include all of the `.ts` files in the starters.  So because `todo.ts` is not imported anywhere and therefore not a part of the app's dependency tree, it isn't visible to the TypeScript compiler used by the IDE.

One solution I believe is to make the `files` array empty, since the default behavior for the TypeScript compiler is to include all `.ts` and `.d.ts` files.  The reason we specify `app/app.ts` explicitly is for the webpack typescript loader, which we want to only compile the files that webpack feeds it as webpack does its own crawl of the dependency tree, starting from the app entry point ([app/app.ts](https://github.com/driftyco/ionic-conference-app/blob/2ed59e6fd275c4616792c7b2e5aa9da4a20fb188/webpack.config.js#L9)), since any extraneous files being compiled that are not a part of the dependency tree would slow down the build unnecessarily.

This is somewhat confusing because the TypeScript compiler is being used by both the IDE for typechecking and also the webpack loader when bundling your app, and both refer to the same `tsconfig.json` for guidance. 

There are 3 possible solutions to making that error in the IDE go away:

1) `import {Todo} from 'todo';` somewhere in your project, it will be part of the dependency tree and visible to the TypeScript compiler and the error will go away.

2) Add `app/todo.ts` to your `files` array in `tsconfig.json`, or make the array empty.

3) If you are using Atom, you could use the non-standard `filesGlob` property: `filesGlob: [ '**/*.ts']` to indicate to Atom which files should be part of the compilation context of the editor.  Awesome-typescript-loader, the webpack typescript loader used by the starters, also supports this property, so if you don't want it to include files that match the glob pattern in addition to the files in the dependency tree, you'll need to [set `resolveGlobs` to false](https://github.com/s-panferov/awesome-typescript-loader#resolveglobs-string-defaulttrue)

I'm going to close this as intended behavior, but please comment if you have any issues or feel this is incorrect.

**Comment by danbucholtz** [comment] 2016-02-11 17:32
Yep - this was really more of a "bring to the team's attention" issue.  Would be great if the glob approach was enabled by default because otherwise I can see where users will be displeased when they create new Typescript files and are immediately getting compile errors.  I don't think too many users will have a flow of importing a class that doesn't yet exist then creating it.  Just my $0.02.  Kind of a bummer than VSCode does not support the glob.

**Comment by tlancina** [comment] 2016-02-11 17:44
Ah thanks, and yeah I don't think it's unreasonable to have filesGlob in there by default.

Re-opening, I'll close when I've updated the starters.

**Comment by donniefitz2** [comment] 2016-02-17 05:22
This has been a big problem for me as well in starting with TS. Many Google searches lead me here. Now I know the fix, though. Thanks.

**Comment by tlancina** [comment] 2016-02-19 17:21
Moved to `exclude` in tsconfig, so all new files should be in the compilation context from now on.

**Comment by danbucholtz** [comment] 2016-02-19 17:21
That seems like a solid approach.  Thanks!

**Closed by tlancina** 2016-02-19 17:21 UTC
Labels: build, v2

**Comment by tlancina** [comment] 2016-02-19 17:22
@danbucholtz although I realize that was only the conference app starter, so closing was a little premature. Updating the other starters now!
