### ISSUE TITLE
before_serve and after_serve hooks do not get called

### ISSUE THREAD

**Issue by jaufgang** [driftyco/ionic-cli#1963] opened 2017-03-08 16:22 UTC
`before_serve` and `after_serve` hooks do not get run at all when calling `ionic serve`.

This was already discussed in #676, which was closed, but I am experiencing the same problem with the most recent version of the cli. 

> Cordova CLI: 6.5.0 
> Ionic Framework Version: 2.1.0
> Ionic CLI Version: 2.2.1
> Ionic App Lib Version: 2.2.0
> Ionic App Scripts Version: 1.1.3
> ios-deploy version: 1.8.3 
> ios-sim version: 5.0.13 
> OS: macOS Sierra
> Node Version: v6.10.0
> Xcode version: Xcode 8.2.1 Build version 8C1002

**Comment by jaufgang** [comment] 2017-03-08 16:34
Actually, the problem seems to be that no hooks at all get called by `ionic serve`.  Running `cordova serve`  in the same app folder runs hooks for `before_serve`, `before_prepare`, `after_serve` and `after_prepare`, but none of them get called by `ionic serve`.    

Not sure which additional hooks do get run by `cordova serve` because I don't have them all set up, but I think the expectation should be that the same hooks get run by the cordova and ionic commands.

**Comment by jthoms1** [comment] 2017-03-08 16:38
Closing as a duplicate of #676. Please add comments there.

**Closed by jthoms1** 2017-03-08 16:38 UTC
Labels: v2
