### ISSUE TITLE
generate page bug

### ISSUE THREAD

**Issue by obermoserkitz** [driftyco/ionic-cli#2049] opened 2017-03-30 08:19 UTC
#### What version of the CLI are you using? Output of `ionic --version`
3.0.0-beta.5

#### Short description of the problem:

Ionic generate page seems to do nothing.

PS C:\Users\Obermoser\Desktop\traffix> ionic generate page alert-create
Error: The generate command is only available for projects that use ionic-angular >= 3.
0.0
    at Object.<anonymous> (C:\Users\Obermoser\Desktop\traffix\node_modules\@ionic\cli-b
uild-ionic-angular\dist\index.js:25371:19)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Obermoser\Desktop\traffix\node_modules\@ionic\cli-build-ioni
c-angular\dist\index.js:25353:58)

#### What behavior are you expecting?
I expect the generator to generate a new page with the name of  alert-create in an seperate folder

**Steps to reproduce:**
1. type ionic generate page alert-create
2. do nothing
3. wonder why it isn't working

```
ionic generate page alert-create
```

**Post the output of `ionic info` below please**
```
 Your system information:

   Cordova CLI: 6.5.0
   Ionic CLI Version: 3.0.0-beta.5
   ios-deploy version: Not installed
   ios-sim version: Not installed
   OS: Windows 10
   Node Version: v7.7.3
   Xcode version: Not installed

**Comment by jthoms1** [comment] 2017-03-30 14:42
Can you execute the `ionic info` command from within your project folder? This should provide me with the Framework version that you currently are using.

**Comment by obermoserkitz** [comment] 2017-03-30 15:50
@jthoms1 
Well, the only Output i get is
Cordova CLI: 6.5.0
Ionic Framework Version: 2.3.0
Ionic CLI Version: 3.0.0-beta.
ios-deploy version: Not instal
ios-sim version: Not installed
OS: Windows 10
Node Version: v7.7.3
Xcode version: Not installed

i have noticed that different users also get appscripts Version in the Output...but me not :-(

**Comment by jthoms1** [comment] 2017-03-30 15:57
The issue is that generators have changed.  They are now only available for Ionic the framework v3.  This will be released next week. So the message throws an error mentioning `ionic-angular` which is how we reference the JS framework.

**Closed by jthoms1** 2017-03-30 15:57 UTC
Labels: v3
