### ISSUE TITLE
error when creating an ionic 2 projects

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-cli#1076] opened 2016-06-14 20:38 UTC
_From @Bandito11 on June 14, 2016 20:27_

#### Short description of the problem:
When creating a project it says that start is undefined and there was error running npminstall. It written together without spaces so I think it was a typo on  your part. 

#### What behavior are you expecting?
to npm install everything when creating a project. 

**Steps to reproduce:**
1. ionic start  nameOfProject --v2 --ts

```
insert any relevant code between the above and below backticks
https://1drv.ms/i/s!Al0ly62YCZx3lsIZ-QMrGV1WVXpSFA
```

**Which Ionic Version?** 
2-beta 8

#### Plunker that shows an example of your issue

**For Ionic 2 issues** - http://plnkr.co/edit/me3Uk0GKWVRhZWU0usad?p=preview

_Copied from original issue: driftyco/ionic#6910_

**Comment by jgw96** [comment] 2016-06-14 20:38
Hello, thanks for opening an issue with us! Since this is an issue with the ionic-cli and not the framework i will be moving this issue to the ionic-cli repo. Thanks for using Ionic!

**Comment by jthoms1** [comment] 2016-06-14 21:31
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.

**Comment by Bandito11** [comment] 2016-06-14 22:52
https://1drv.ms/i/s!Al0ly62YCZx3lsIZ-QMrGV1WVXpSFA

another thing, that happened when creating a blank project. 


I had to create another one because I just npm install everything manually.

**Comment by Bandito11** [comment] 2016-06-14 23:01
Just tried it again and it ran without problems. I think it was my internet connection. I forgot it was giving me hiccups in the afternoon, Sorry for the trouble.

**Comment by kalmenchia** [comment] 2016-06-15 00:48
Hi , i had the same issues as

**Short description of the problem**:When creating a project it says that start is undefined and there was error running npminstall. 

```
Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic2-starter-tabs/archive/master.zip
[=============================]  100%  0.0s
Installing npm packages...
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined
```

and i am using **ionic@2.0.0-beta.30**
```
but i do notice that during installation ,i had a lot of unmet dependency , will this caused problem ?
npm WARN unmet dependency /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm requires glob@'~7.0.3' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/glob,
npm WARN unmet dependency which is version 5.0.15
npm WARN unmet dependency /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm requires request@'~2.72.0' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/request,
npm WARN unmet dependency which is version 2.47.0
npm WARN unmet dependency /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm requires semver@'~5.1.0' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/semver,
npm WARN unmet dependency which is version 4.3.6
npm WARN unmet dependency /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm requires tar@'~2.2.1' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/tar,
npm WARN unmet dependency which is version 1.0.2
npm WARN unmet dependency /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/cordova-fetch/node_modules/shelljs requires glob@'^7.0.0' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/glob,
npm WARN unmet dependency which is version 5.0.15
npm WARN unmet dependency /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/cordova-serve/node_modules/express/node_modules/serve-static requires send@'0.13.2' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/cordova-serve/node_modules/express/node_modules/send,
npm WARN unmet dependency which is version 0.13.1
```

then i tried to start a blank project with tutorial template , it also had error and cannot proceed ,
i tried : **ionic start MyIonic2Project tutorisl --v2**

and the error is as follow
```

Creating Ionic app in folder /Users/admin/angularjs-projects/MyIonic2Project based on tutorisl project
Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
[=============================]  100%  0.0s
Error with start Error: No starter template named "tutorisl"
    at Object.Start.fetchIonicStarter (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/start.js:499:13)
    at Object.Start.fetchSeed (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/start.js:255:16)
    at /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/start.js:106:18
    at _fulfilled (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/ionic/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:108:17)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
Error Initializing app: Error: No starter template named "tutorisl"
 Error: No starter template named "tutorisl"
    at Object.Start.fetchIonicStarter (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/start.js:499:13)
    at Object.Start.fetchSeed (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/start.js:255:16)
    at /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/start.js:106:18
    at _fulfilled (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/ionic/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:108:17)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
Caught exception:
 Error: No starter template named "tutorisl"
    at Object.Start.fetchIonicStarter (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/start.js:499:13)
    at Object.Start.fetchSeed (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/start.js:255:16)
    at /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/start.js:106:18
    at _fulfilled (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/ionic/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:108:17)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
```

appreciate any advice to get me to start trying this awesome framework ! 
thanks.
Kalmen

**Comment by jthoms1** [comment] 2016-06-15 01:21
Could you try running the command with the verbose flag? Thanks!

`ionic start cutePuppyPics --v2 --verbose`

**Comment by kalmenchia** [comment] 2016-06-15 03:09
Hi , 

when i tried running with verbose flag , here is the message i captured ,

```
Task: title=start, name=start, summary=Starts a new Ionic project in the specified PATH, [options]=any flags for the command, <PATH>=directory for the new project, [template]=Starter templates can either come from a named template,
(ex: tabs, sidemenu, blank),
a Github repo, a Codepen url, or a local directory.
Codepen url, ex: http://codepen.io/ionic/pen/odqCz
Defaults to Ionic "tabs" starter template, --appname|-a=Human readable name for the app (Use quotes around the name), --id|-i=Package name for <widget id> config, ex: com.mycompany.myapp, title=Skip npm package installation, boolean=true, title=Create a basic structure without Cordova requirements, boolean=true, title=Setup the project to use Sass CSS precompiling, boolean=true, title=List starter templates available, boolean=true, --io-app-id=The Ionic.io app ID to use, --template|-t=Project starter template, boolean=true, title=Start a Ionic v2 project, boolean=true, title=(with --v2 only) Use TypeScript in starter, --zip-file|-z=URL to download zipfile for starter template, isProjectTask=false, run=function run(ionic, argv) {
  if (argv.list || argv.l) {
    return templateUtils.listTemplates();
  }

  // If we are starting a version 2 project then typescript should be set by default
  if ((argv.v2 || argv.v) && !argv.hasOwnProperty('ts') && !argv.hasOwnProperty('typescript')) {
    argv.ts = true;
  }

  if (argv._.length < 2) {
    return appLibUtils.fail('Invalid command', 'start');
  }

  if (argv._[1] === '.') {
    return log.error('Please name your Ionic project something meaningful other than \'.\''.red);
  }

  var promptPromise;
  var options = appLibUtils.preprocessCliOptions(argv);
  var startingApp = true;

  // Grab the app's relative directory name
  if (fs.existsSync(options.targetPath)) {
    promptPromise = Start.promptForOverwrite(options.targetPath);
  } else {
    promptPromise = Q(true);
  }

  return promptPromise
  .then(function(promptToContinue) {
    if (!promptToContinue) {
      startingApp = false;
      log.info('\nIonic start cancelled by user.');
      return;
    }
    return Start.startApp(options);
  })
  .then(function() {
    if (startingApp) {
      return Start.printQuickHelp(options);
    }
  })
  .then(function() {
    if (startingApp) {
      return Start.promptLogin(options);
    }
  })
  .then(function() {
    if (options.v2 && startingApp) {
      log.info('\nNew to Ionic? Get started here: http://ionicframework.com/docs/v2/getting-started\n');
    }
  })
  .catch(function(error) {
    log.error(error);
    throw error;
  });
}
Utils.preprocessCliOptions _=[start, cutePuppyPics], skip-npm=false, no-cordova=false, w=false, sass=false, s=false, list=false, l=false, v2=true, v=false, typescript=false, ts=false, verbose=true, $0=ionic
Creating Ionic app in folder /Users/admin/angularjs-projects/cutePuppyPics based on tabs project
Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic2-starter-tabs/archive/master.zip
[=============================]  100%  0.0s
Installing npm packages...
Running exec command: npminstall
npm

WARN
 package.json @ No description

npm
 WARN package.json @ No repository field.

npm
WARN package.json @ No license field.

npm
 WARN
 deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

npm

WARN deprecated
 lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.

npm

WARN
deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

npm
 WARN deprecated
 cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!


> node-sass@3.7.0 install /Users/admin/angularjs-projects/cutePuppyPics/node_modules/ionic-gulp-sass-build/node_modules/gulp-sass/node_modules/node-sass
> node scripts/install.js


Binary downloaded and installed at /Users/admin/angularjs-projects/cutePuppyPics/node_modules/ionic-gulp-sass-build/node_modules/gulp-sass/node_modules/node-sass/vendor/darwin-x64-46/binding.node


> fsevents@1.0.12 install /Users/admin/angularjs-projects/cutePuppyPics/node_modules/gulp-watch/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build


[fsevents] Success: "/Users/admin/angularjs-projects/cutePuppyPics/node_modules/gulp-watch/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v46-darwin-x64/fse.node" is installed via remote


> fsevents@1.0.12 install /Users/admin/angularjs-projects/cutePuppyPics/node_modules/ionic-gulp-browserify-es2015/node_modules/watchify/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build


[fsevents] Success: "/Users/admin/angularjs-projects/cutePuppyPics/node_modules/ionic-gulp-browserify-es2015/node_modules/watchify/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v46-darwin-x64/fse.node" is installed via remote


> node-sass@3.7.0 postinstall /Users/admin/angularjs-projects/cutePuppyPics/node_modules/ionic-gulp-sass-build/node_modules/gulp-sass/node_modules/node-sass
> node scripts/build.js


"/Users/admin/angularjs-projects/cutePuppyPics/node_modules/ionic-gulp-sass-build/node_modules/gulp-sass/node_modules/node-sass/vendor/darwin-x64-46/binding.node" exists.
 testing binary.

Binary is fine; exiting.

ionic-gulp-fonts-copy@1.0.0 node_modules/ionic-gulp-fonts-copy

ionic-gulp-html-copy@1.0.0 node_modules/ionic-gulp-html-copy

ionic-gulp-scripts-copy@2.0.0 node_modules/ionic-gulp-scripts-copy

zone.js@0.6.12 node_modules/zone.js

es6-shim@0.35.1 node_modules/es6-shim

reflect-metadata@0.1.3 node_modules/reflect-metadata

@angular/platform-browser-dynamic@2.0.0-rc.1 node_modules/@angular/platform-browser-dynamic

del@2.2.0 node_modules/del
├── is-path-cwd@1.0.0
├── object-assign@4.1.0
├── pify@2.3.0
├── pinkie-promise@2.0.1 (pinkie@2.0.4)
├── is-path-in-cwd@1.0.0 (is-path-inside@1.0.0)
├── globby@4.1.0 (arrify@1.0.1, array-union@1.0.1, glob@6.0.4)
└── rimraf@2.5.2 (glob@7.0.3)

@angular/http@2.0.0-rc.1 node_modules/@angular/http

@angular/router@2.0.0-rc.1 node_modules/@angular/router

ionic-native@1.2.4 node_modules/ionic-native

run-sequence@1.1.5 node_modules/run-sequence
├── chalk@1.1.3 (escape-string-regexp@1.0.5, supports-color@2.0.0, ansi-styles@2.2.1, has-ansi@2.0.0, strip-ansi@3.0.1)
└── gulp-util@3.0.7 (array-differ@1.0.0, array-uniq@1.0.2, lodash._reevaluate@3.0.0, lodash._reescape@3.0.0, beeper@1.1.0, lodash._reinterpolate@3.0.0, object-assign@3.0.0, replace-ext@0.0.1, minimist@1.2.0, has-gulplog@0.1.0, fancy-log@1.2.0, vinyl@0.5.3, gulplog@1.0.0, lodash.template@3.6.2, through2@2.0.1, multipipe@0.1.2, dateformat@1.0.12)

gulp@3.9.1 node_modules/gulp
├── interpret@1.0.1
├── pretty-hrtime@1.0.2
├── deprecated@0.0.1
├── archy@1.0.0
├── minimist@1.2.0
├── semver@4.3.6
├── tildify@1.2.0 (os-homedir@1.0.1)
├── chalk@1.1.3 (escape-string-regexp@1.0.5, ansi-styles@2.2.1, supports-color@2.0.0, has-ansi@2.0.0, strip-ansi@3.0.1)
├── v8flags@2.0.11 (user-home@1.1.1)
├── orchestrator@0.3.7 (sequencify@0.0.7, stream-consume@0.1.0, end-of-stream@0.1.5)
├── liftoff@2.2.1 (extend@2.0.1, rechoir@0.6.2, flagged-respawn@0.3.2, findup-sync@0.3.0, resolve@1.1.7)
├── vinyl-fs@0.3.14 (graceful-fs@3.0.8, strip-bom@1.0.0, defaults@1.0.3, vinyl@0.4.6, through2@0.6.5, mkdirp@0.5.1, glob-stream@3.1.18, glob-watcher@0.0.6)
└── gulp-util@3.0.7 (array-differ@1.0.0, array-uniq@1.0.2, lodash._reescape@3.0.0, lodash._reinterpolate@3.0.0, object-assign@3.0.0, beeper@1.1.0, lodash._reevaluate@3.0.0, replace-ext@0.0.1, has-gulplog@0.1.0, fancy-log@1.2.0, vinyl@0.5.3, gulplog@1.0.0, lodash.template@3.6.2, through2@2.0.1, multipipe@0.1.2, dateformat@1.0.12)

@angular/platform-browser@2.0.0-rc.1 node_modules/@angular/platform-browser

@angular/common@2.0.0-rc.1 node_modules/@angular/common

@angular/compiler@2.0.0-rc.1 node_modules/@angular/compiler

@angular/core@2.0.0-rc.1 node_modules/@angular/core

ionicons@3.0.0 node_modules/ionicons

ionic-angular@2.0.0-beta.8 node_modules/ionic-angular
├── q@1.4.1
├── colors@1.1.2
├── mkdirp-no-bin@0.5.1
├── inquirer@0.11.0 (strip-ansi@3.0.1, ansi-regex@2.0.0, ansi-escapes@1.4.0, through@2.3.8, rx-lite@3.1.2, cli-width@1.1.1, chalk@1.1.3, figures@1.7.0, readline2@1.0.1, run-async@0.1.0, cli-cursor@1.0.2)
└── lodash@3.10.1

rxjs@5.0.0-beta.6 node_modules/rxjs

gulp-watch@4.3.5 node_modules/gulp-watch
├── path-is-absolute@1.0.0
├── glob2base@0.0.12 (find-index@0.1.1)
├── vinyl@0.5.3 (clone-stats@0.0.1, replace-ext@0.0.1, clone@1.0.2)
├── vinyl-file@1.3.0 (graceful-fs@4.1.4, vinyl@1.1.1, strip-bom-stream@1.0.0, strip-bom@2.0.0)
├── readable-stream@2.1.4 (buffer-shims@1.0.0, string_decoder@0.10.31, process-nextick-args@1.0.7, inherits@2.0.1, util-deprecate@1.0.2, core-util-is@1.0.2, isarray@1.0.0)
├── glob@5.0.15 (inherits@2.0.1, once@1.3.3, inflight@1.0.5, minimatch@3.0.0)
├── anymatch@1.3.0 (arrify@1.0.1, micromatch@2.3.8)
├── gulp-util@3.0.7 (array-differ@1.0.0, array-uniq@1.0.2, object-assign@3.0.0, lodash._reinterpolate@3.0.0, lodash._reevaluate@3.0.0, lodash._reescape@3.0.0, beeper@1.1.0, replace-ext@0.0.1, minimist@1.2.0, has-gulplog@0.1.0, fancy-log@1.2.0, chalk@1.1.3, gulplog@1.0.0, lodash.template@3.6.2, through2@2.0.1, multipipe@0.1.2, dateformat@1.0.12)
└── chokidar@1.5.2 (inherits@2.0.1, glob-parent@2.0.0, async-each@1.0.0, is-glob@2.0.1, is-binary-path@1.0.1, readdirp@2.0.0, fsevents@1.0.12)

ionic-gulp-browserify-es2015@1.1.0 node_modules/ionic-gulp-browserify-es2015
├── prettysize@0.0.3
├── lodash.merge@4.4.0 (lodash.rest@4.0.3, lodash._root@3.0.1, lodash.keysin@4.1.4, lodash.isplainobject@4.0.4, lodash._baseclone@4.5.7)
├── vinyl-source-stream@1.1.0 (vinyl@0.4.6, through2@0.6.5)
├── vinyl-buffer@1.0.0 (through2@0.6.5, bl@0.9.5)
├── gulp-sourcemaps@1.6.0 (graceful-fs@4.1.4, convert-source-map@1.2.0, strip-bom@2.0.0, vinyl@1.1.1, through2@2.0.1)
├── gulp-uglify@1.5.3 (uglify-save-license@0.4.1, deap@1.0.0, isobject@2.1.0, vinyl-sourcemaps-apply@0.2.1, fancy-log@1.2.0, through2@2.0.1, gulp-util@3.0.7, uglify-js@2.6.2)
├── browserify@13.0.1 (browser-resolve@1.11.2, string_decoder@0.10.31, https-browserify@0.0.1, tty-browserify@0.0.0, path-browserify@0.0.0, punycode@1.4.1, inherits@2.0.1, duplexer2@0.1.4, constants-browserify@1.0.0, os-browserify@0.1.2, process@0.11.5, htmlescape@1.1.1, defined@1.0.0, stream-browserify@2.0.1, xtend@4.0.1, assert@1.3.0, domain-browser@1.1.7, read-only-stream@2.0.0, querystring-es3@0.2.1, timers-browserify@1.4.2, util@0.10.3, deps-sort@2.0.0, events@1.1.0, parents@1.0.1, vm-browserify@0.0.4, shell-quote@1.6.0, has@1.0.1, readable-stream@2.1.4, console-browserify@1.1.0, subarg@1.0.0, url@0.11.0, labeled-stream-splicer@2.0.0, through2@2.0.1, shasum@1.0.2, concat-stream@1.5.1, glob@5.0.15, stream-http@2.3.0, JSONStream@1.1.2, buffer@4.6.0, resolve@1.1.7, syntax-error@1.1.6, browserify-zlib@0.1.4, browser-pack@6.0.1, crypto-browserify@3.11.0, insert-module-globals@7.0.1, module-deps@4.0.7)
├── babel-plugin-transform-decorators-legacy@1.3.4 (babel-plugin-syntax-decorators@6.8.0, babel-template@6.9.0, babel-runtime@6.9.2)
├── babel-
Adding initial native plugins
Initializing cordova project without CLI
preset-es2015@6.9.0 (babel-plugin-transform-es2015-arrow-functions@6.8.0, babel-plugin-check-es2015-constants@6.8.0, babel-plugin-transform-es2015-template-literals@6.8.0, babel-plugin-transform-es2015-destructuring@6.9.0, babel-plugin-transform-es2015-typeof-symbol@6.8.0, babel-plugin-transform-es2015-for-of@6.8.0, babel-plugin-transform-es2015-literals@6.8.0, babel-plugin-transform-es2015-block-scoped-functions@6.8.0, babel-plugin-transform-es2015-spread@6.8.0, babel-plugin-transform-es2015-computed-properties@6.8.0, babel-plugin-transform-es2015-shorthand-properties@6.8.0, babel-plugin-transform-es2015-duplicate-keys@6.8.0, babel-plugin-transform-es2015-object-super@6.8.0, babel-plugin-transform-es2015-function-name@6.9.0, babel-plugin-transform-es2015-sticky-regex@6.8.0, babel-plugin-transform-es2015-unicode-regex@6.8.0, babel-plugin-transform-es2015-parameters@6.9.0, babel-plugin-transform-es2015-modules-commonjs@6.8.0, babel-plugin-transform-es2015-classes@6.9.0, babel-plugin-transform-es2015-block-scoping@6.10.1, babel-plugin-transform-regenerator@6.9.0)
├── babelify@7.3.0 (object-assign@4.1.0, babel-core@6.9.1)
└── watchify@3.7.0 (xtend@4.0.1, defined@1.0.0, through2@2.0.1, outpipe@1.1.1, anymatch@1.3.0, chokidar@1.5.2)

ionic-gulp-sass-build@1.0.0 node_modules/ionic-gulp-sass-build
├── lodash.assign@4.0.9 (lodash.keys@4.0.7, lodash.rest@4.0.3)
├── gulp-autoprefixer@3.1.0 (through2@2.0.1, vinyl-sourcemaps-apply@0.2.1, postcss@5.0.21, gulp-util@3.0.7, autoprefixer@6.3.6)
└── gulp-sass@2.3.1 (object-assign@4.1.0, vinyl-sourcemaps-apply@0.2.1, through2@2.0.1, gulp-util@3.0.7, node-sass@3.7.0)

Spawn command completed
Updated the hooks directory to have execute permissions
Cordova.addPlugin: projectRoot /Users/admin/angularjs-projects/cutePuppyPics pluginId cordova-plugin-device pluginVariables null savePlugin true
Cordova.addPlugin: projectRoot /Users/admin/angularjs-projects/cutePuppyPics pluginId cordova-plugin-console pluginVariables null savePlugin true
Cordova.addPlugin: projectRoot /Users/admin/angularjs-projects/cutePuppyPics pluginId cordova-plugin-whitelist pluginVariables null savePlugin true
Cordova.addPlugin: projectRoot /Users/admin/angularjs-projects/cutePuppyPics pluginId cordova-plugin-splashscreen pluginVariables null savePlugin true
Cordova.addPlugin: projectRoot /Users/admin/angularjs-projects/cutePuppyPics pluginId cordova-plugin-statusbar pluginVariables null savePlugin true
Cordova.addPlugin: projectRoot /Users/admin/angularjs-projects/cutePuppyPics pluginId ionic-plugin-keyboard pluginVariables null savePlugin true
Error occurred while adding plugin:  Error: Cannot find module 'detective'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/cordova-lib/node_modules/cordova-js/node_modules/browserify/node_modules/module-deps/index.js:6:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
Error with start Error: Cannot find module 'detective'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/cordova-lib/node_modules/cordova-js/node_modules/browserify/node_modules/module-deps/index.js:6:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
Error Initializing app: Error: Cannot find module 'detective'
 Error: Cannot find module 'detective'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/cordova-lib/node_modules/cordova-js/node_modules/browserify/node_modules/module-deps/index.js:6:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
Caught exception:
 Error: Cannot find module 'detective'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/cordova-lib/node_modules/cordova-js/node_modules/browserify/node_modules/module-deps/index.js:6:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

Error occurred while adding plugin:  Error: Cannot find module 'detective'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/cordova-lib/node_modules/cordova-js/node_modules/browserify/node_modules/module-deps/index.js:6:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
Error occurred while adding plugin:  Error: Cannot find module 'detective'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/cordova-lib/node_modules/cordova-js/node_modules/browserify/node_modules/module-deps/index.js:6:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
Error occurred while adding plugin:  Error: Cannot find module 'detective'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/cordova-lib/node_modules/cordova-js/node_modules/browserify/node_modules/module-deps/index.js:6:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
Error occurred while adding plugin:  Error: Cannot find module 'detective'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/cordova-lib/node_modules/cordova-js/node_modules/browserify/node_modules/module-deps/index.js:6:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
Error occurred while adding plugin:  Error: Cannot find module 'detective'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/cordova-lib/node_modules/cordova-js/node_modules/browserify/node_modules/module-deps/index.js:6:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

```

Hope this help you to trace the error.
Thanks,
Kalmen

**Comment by saurabhvyas** [comment] 2016-06-21 16:20
I got the same error :(
Ionic Framework Version: 2.0.0-beta.9
Ionic CLI Version: 2.0.0-beta.31
Ionic App Lib Version: 2.0.0-beta.17
OS:
Node Version: v5.11.1

**Comment by jlsuarezs** [comment] 2016-06-23 03:27
Yes, the same: 
Your system information:
 
Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.9
Ionic CLI Version: 2.0.0-beta.31
Ionic App Lib Version: 2.0.0-beta.17
ios-deploy version: 1.8.6
ios-sim version: 5.0.8

OS: Mac OS X El Capitan
Node Version: v6.2.0
Xcode version: Xcode 7.3 Build version 7D175

**Comment by 3dd13** [comment] 2016-06-26 10:55
there are few things you need to do to upgrade / update

1. upgrade nodejs

        brew upgrade node

2. upgrade npm

        npm install -g npm

3. set new registry

        npm set registry http://registry.npmjs.org

**Comment by jthoms1** [comment] 2016-07-06 20:48
Closing this as a duplicate of #1013.

**Closed by jthoms1** 2016-07-06 20:48 UTC
Labels: npm install, v2

**Comment by AyaMaher7** [comment] 2016-11-13 19:21
i have the same issue 

Your system information:

 ordova CLI: 6.4.0
Ionic CLI Version: 2.1.8
Ionic App Lib Version: 2.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 8.1
Node Version: v7.1.0
Xcode version: Not installed

**Comment by rangholiyanikunj** [comment] 2016-12-27 11:16
G:\workpsace_nikunj>ionic start chatApp

Dependency warning - for the CLI to run correctly,
it is highly recommended to install/upgrade the following:

Please install your Cordova CLI to version >=4.2.0 npm install -g cordova

Error: Cannot find module 'cordova-common'
at Function.Module._resolveFilename (module.js:440:15)
at Function.Module._load (module.js:388:25)
at Module.require (module.js:468:17)
at require (internal/module.js:20:19)
at Object. (C:\Users\TULSI INFOTECH-2\AppData\Roaming\npm\node_mo
dules\ionic\node_modules\cordova-lib\src\plugman\plugman.js:22:14)
at Module._compile (module.js:541:32)
at Object.Module._extensions..js (module.js:550:10)
at Module.load (module.js:458:32)
at tryModuleLoad (module.js:417:12)
at Function.Module._load (module.js:409:3)

Cannot find module 'cordova-common' (CLI v2.1.17)

Your system information:

You have been opted out of telemetry. To change this, run: cordova telemetry on
.
6.4.0

Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v6.2.2
Xcode version: Not installed

G:\workpsace_nikunj>
