### ISSUE TITLE
ionic build android: ngc failed:  NGC encountered an error

### ISSUE THREAD

**Issue by mahkali** [driftyco/ionic-cli#1484] opened 2016-10-06 21:07 UTC
I encounter an error when executing the following command:
`ionic build android`

This is the debug log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/6.7.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.10.7
3 info using node@v6.7.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle eveenergysales@~prebuild: eveenergysales@
6 silly lifecycle eveenergysales@~prebuild: no script for prebuild, continuing
7 info lifecycle eveenergysales@~build: eveenergysales@
8 verbose lifecycle eveenergysales@~build: unsafe-perm in lifecycle true
9 verbose lifecycle eveenergysales@~build: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/maarten/eveEnergy/eve-energy-app2/EveEnergySales/node_modules/.bin:/usr/local/Cellar/node/6.7.0/bin:/usr/local/Cellar/android-sdk/24.4.1_1/tools:/usr/local/Cellar/android-sdk/24.4.1_1/platform-tools:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
10 verbose lifecycle eveenergysales@~build: CWD: /Users/maarten/eveEnergy/eve-energy-app2/EveEnergySales
11 silly lifecycle eveenergysales@~build: Args: [ '-c', 'ionic-app-scripts build' ]
12 silly lifecycle eveenergysales@~build: Returned: code: 1  signal: null
13 info lifecycle eveenergysales@~build: Failed to exec build script
14 verbose stack Error: eveenergysales@ build: `ionic-app-scripts build`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid eveenergysales@
16 verbose cwd /Users/maarten/eveEnergy/eve-energy-app2/EveEnergySales
17 error Darwin 15.6.0
18 error argv "/usr/local/Cellar/node/6.7.0/bin/node" "/usr/local/bin/npm" "run" "build"
19 error node v6.7.0
20 error npm  v3.10.7
21 error code ELIFECYCLE
22 error eveenergysales@ build: `ionic-app-scripts build`
22 error Exit status 1
23 error Failed at the eveenergysales@ build script 'ionic-app-scripts build'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the eveenergysales package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     ionic-app-scripts build
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs eveenergysales
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls eveenergysales
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by lauraemilyjacobsen** [comment] 2016-10-08 22:25
I have the same problem. The app runs in the browser with `ionic serve`, but `ionic run android` fails with the following output.

`C:\Users\Laura\IonicProjects\githubIonic>ionic run android

Running 'run:before' npm script before run
> ionic-hello-world@ build C:\Users\Laura\IonicProjects\githubIonic
> ionic-app-scripts build
[15:20:29]  ionic-app-scripts 0.0.30
[15:20:29]  build prod started ...
[15:20:29]  clean started ...
[15:20:29]  clean finished in 16 ms
[15:20:29]  copy started ...
[15:20:29]  ngc started ...
[15:20:29]  lint started ...
[15:20:29]  copy finished in 181 ms
[15:20:30]  tslint: C:/Users/Laura/IonicProjects/githubIonic/src/pages/user-details/user-details.d.ts[6, 13]: Unused property: 'navParams'
C:/Users/Laura/IonicProjects/githubIonic/src/pages/user-details/user-details.d.ts[7, 13]: Unused property: 'githubUsers'


[15:20:30]  tslint: C:/Users/Laura/IonicProjects/githubIonic/src/pages/users/users.d.ts[6, 13]: Unused property: 'githubUsers'


[15:20:30]  lint finished in 1.12 s
[15:20:31]  ngc: Error: Error Cannot write file 'C:/Users/Laura/IonicProjects/githubIonic/.tmp/app/app.component.d.ts' because it would overwrite input file.
Error Cannot write file 'C:/Users/Laura/IonicProjects/githubIonic/.tmp/models/user.d.ts' because it would overwrite input file.
Error Cannot write file 'C:/Users/Laura/IonicProjects/githubIonic/.tmp/pages/organizations/organizations.d.ts' because it would overwrite input file.
Error Cannot write file 'C:/Users/Laura/IonicProjects/githubIonic/.tmp/pages/repos/repos.d.ts' because it would overwrite input file.
Error Cannot write file 'C:/Users/Laura/IonicProjects/githubIonic/.tmp/pages/user-details/user-details.d.ts' because it would overwrite input file.
Error Cannot write file 'C:/Users/Laura/IonicProjects/githubIonic/.tmp/pages/users/users.d.ts' because it would overwrite input file.
Error Cannot write file 'C:/Users/Laura/IonicProjects/githubIonic/.tmp/providers/github-users.d.ts' because it would overwrite input file.
    at Object.check (C:\Users\Laura\IonicProjects\githubIonic\node_modules\@angular\tsc-wrapped\src\tsc.js:31:15)
    at Object.main (C:\Users\Laura\IonicProjects\githubIonic\node_modules\@angular\tsc-wrapped\src\main.js:26:15)
    at Object.<anonymous> (C:\Users\Laura\IonicProjects\githubIonic\node_modules\@angular\compiler-cli\src\main.js:14:9)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)


[15:20:31]  ngc: Compilation failed


[15:20:31]  ngc failed:  NGC encountered an error

[15:20:31]  Error: NGC encountered an error
    at ChildProcess.<anonymous> (C:\Users\Laura\IonicProjects\githubIonic\node_modules\@ionic\app-scripts\dist\ngc.js:62:24)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at ChildProcess.cp.emit (C:\Users\Laura\IonicProjects\githubIonic\node_modules\cross-spawn\lib\enoent.js:40:29)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

Error running ionic app script "build": Error: NGC encountered an error



npm
 ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm
ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! ionic-hello-world@ build: `ionic-app-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ionic-hello-world@ build script 'ionic-app-scripts build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic-hello-world package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts build

npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ionic-hello-world
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ionic-hello-world
npm ERR! There is likely additional logging output above.



npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Laura\IonicProjects\githubIonic\npm-debug.log

Caught exception:
 undefined`

**Comment by dmastag** [comment] 2016-10-09 01:06
@lauraemilyjacobsen might it be that you also have ionic serve open on another terminal at the same time ?

**Comment by lauraemilyjacobsen** [comment] 2016-10-09 02:09
@dmastag no, I don't have any other terminals open.

**Comment by mahkali** [comment] 2016-10-10 21:25
> $: npm run build

Then it will explicitly show any remaining errors. 

In my case I had to declare my Promise as :

>  .then((address : any)  =>  { }

instead of 

> .then((address)  =>  {

And declare used variables like 

>   lead : any = {};

I guess you could be more explicit in declarations, any works too.

I also noted that any warnings in serve can be errors in build.

**Comment by jgw96** [comment] 2016-10-12 01:34
Hello, thanks for using Ionic! So this is caused by legit errors (usually type errors) in your code. NGC does type checking on methods and variables that are bound to your templates and will throw errors when it is ran (when `ionic build` or `ionic emulate` is run). `ionic serve` does not run NGC (as it causes slow build times, and AoT is not needed while devving) which is why you are not getting these errors when running `ionic serve`. Also the Angular team is working hard on making NGC errors better. Since this is not an Ionic issue i am going to close this issue for now. Thanks!

**Closed by jgw96** 2016-10-12 01:34 UTC

**Comment by gkiran1** [comment] 2017-04-20 10:38
Same issue with me:

tsconfig.json

{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "dom",
      "es2015"
    ],
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "target": "es5"
  },
  "include": [
    "src/**/*.ts"
  ],
  "exclude": [
    "node_modules"
  ],
  "compileOnSave": false,
  "atom": {
    "rewriteTsconfig": false
  }
}

Error:

[16:05:41]  ionic-app-scripts 1.3.4
[16:05:41]  build prod started ...
[16:05:41]  clean started ...
[16:05:41]  clean finished in less than 1 ms
[16:05:41]  copy started ...
[16:05:41]  ngc started ...
[16:05:43]  ionic-app-script task: "build"
[16:05:43]  TypeError: Cannot read property 'codeGen' of undefined
TypeError: Cannot read property 'codeGen' of undefined
    at Object.doCodegen (F:\Councils-Code\node_modules\@ionic\app-scripts\dist\a
ot\codegen.js:6:50)
    at F:\Councils-Code\node_modules\@ionic\app-scripts\dist\aot\aot-compiler.js
:42:30

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "run" "ionic:build" "--" "--prod"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! councils@ ionic:build: `ionic-app-scripts build "--prod"`
npm ERR! Exit status 1
