### ISSUE TITLE
"ionic start cutePuppyPics --v2" stop after downing

### ISSUE THREAD

**Issue by JackZhang1988** [driftyco/ionic-cli#1505] opened 2016-10-10 10:08 UTC
i'm using ionic-cli generate new project, when i run 'ionic start cutePuppyPics --v2', it stops after downling zip files, like the picture show blow.
![image](https://cloud.githubusercontent.com/assets/1697710/19232809/6fe1b1c6-8f14-11e6-98ae-ec53dbe7d1f2.png)
 
My ionic info is: 
![image](https://cloud.githubusercontent.com/assets/1697710/19232824/8881b6e0-8f14-11e6-9d54-06a840d09ca1.png)

what's wrong about this?

**Comment by bhatvisu1000** [comment] 2016-10-11 01:22
Hi I am also facing same issue.
bash-3.2$ ionic start cutePuppyPics --v2
Creating Ionic app in folder /Users/bhatvisu1000/Downloads/cutePuppyPics based on tabs project
Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic2-starter-tabs/archive/master.zip
[=============================]  100%  0.0s
Installing npm packages...
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

**Comment by bhatvisu1000** [comment] 2016-10-11 01:22
Any solution. Please help

**Comment by jgw96** [comment] 2016-10-12 00:33
Hello all! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic-cli/issues/1491. Thanks!

**Closed by jgw96** 2016-10-12 00:33 UTC
