### ISSUE TITLE
Failed at the ionic-hello-world@ ionic:build script 'ionic-app-scripts build "--prod"'.

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-cli#2119] opened 2017-04-19 14:12 UTC
_From @sunilkconsultant on April 19, 2017 12:50_

**Ionic version:**  
[x] **3.x**

**I'm submitting a ...** 
[x] bug report

**Current behavior:**
node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! ionic-hello-world@ ionic:build: `ionic-app-scripts build "--prod"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ionic-hello-world@ ionic:build script 'ionic-app-scripts build "--prod"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic-hello-world package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts build "--prod"

**Expected behavior:**
Build must not fail 

**Steps to reproduce:**
Download a ionic v2 blank template,
Run platform add android,
Run ionic run android --prod

**Ionic info:** :

```
Your system information:

Cordova CLI: 6.5.0 
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: macOS Sierra
Node Version: v6.10.1
Xcode version: Xcode 8.2.1 Build version 8C1002
```

_Copied from original issue: driftyco/ionic#11271_

**Comment by sunilkconsultant** [comment] 2017-04-21 05:02
thanks for resolving this cheers!

**Comment by dwieeb** [comment] 2017-04-21 21:53
👍

**Closed by dwieeb** 2017-04-21 21:53 UTC
Labels: v2

**Comment by rahul-canbrand** [comment] 2017-04-22 06:29
I am sorry - what was the solution here - I am still getting this error and unsure on how to solve it.

**Comment by matheusjov** [comment] 2017-04-24 17:23
I'm with the same problem, I did not understand the solution @ jgw96

**Comment by Anujmoglix** [comment] 2017-04-26 07:03
Move  your code in other folder then it will work

**Comment by rahul-canbrand** [comment] 2017-04-26 07:09
I uninstalled ionic completely, setup the code again and it worked.

**Comment by mahmoudtokura** [comment] 2017-05-09 17:52
The problem is with the "page-name.component.ts" file that is created when you use the "ionic generate page" command.
Create your pages manually and run it (ionic run android --prod) or (ionic run android --prod) again.
it worked for me.
Home they fix it soon.
