### ISSUE TITLE
bug: ionic g page should use IonicPageModule

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic-cli#2070] opened 2017-04-06 21:46 UTC
_From @geykel on April 5, 2017 19:22_

**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>3.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When using the Ionic cli generate command for generating pages, the page module tempate is using IonicModule instead of IonicPageModule.

Reproduce:

ionic g page login

This is my current dev environment:

cordova CLI: 6.5.0
Ionic Framework Version: 3.0.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.5
Xcode version: Not installed</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#11076_

**Comment by jgw96** [comment] 2017-04-10 14:27
This was fixed by a community member in the framework.

**Closed by jgw96** 2017-04-10 14:27 UTC

**Comment by santiph** [comment] 2017-04-10 14:35
@jgw96  So I think I've been affected by this issue by trying to create a new page and seeing a new module also being created.
What should be done to get the create page command working again? (Update/reinstall/download anything?)

**Comment by chikehenderson** [comment] 2017-04-13 23:56
nice one

**Comment by sofqi** [comment] 2017-04-14 20:50
Even though this is closed, I just updated everything today, created a new project using
`ionic start ion3 sidemenu --v2`
created a new component using 
`ionic g component testcomponent`
then
`ionic emulate ios --target="iPhone-6s";date`
and quickly got the error
` Property 'forChild' does not exist on type 'typeof IonicModule'.`

**Comment by Eraldo** [comment] 2017-04-15 18:31
I can confirm this. :)

I also want to say that the reason this error is there is great!
Thanks a lot for working on the new modularised page loading mechanism. ;)

**Comment by jdell64** [comment] 2017-04-17 19:00
Unless I'm doing something terribly wrong, this is not fixed yet. A work around has been identified, but the root cause has not been fixed, right?

**Comment by p1ll0wf0rtress** [comment] 2017-04-18 06:35
I'm also very interested in this.

**Comment by jawad-aziz-farhad** [comment] 2017-04-18 12:06
In the new Created Page,There is a Typescript File having name like this:
"PageName.module.ts" , In this file, Change **IonicModule** to **IonicPageModule.**
and you are done.

**Comment by jdell64** [comment] 2017-04-18 14:08
@jawad-aziz-farhad that isn't a fix, it's a workaround.

**Comment by surajrao** [comment] 2017-04-18 14:22
@jdell64 check this https://github.com/driftyco/ionic/pull/11077 it will probably be in the next version

**Comment by jdell64** [comment] 2017-04-18 14:25
Thanks!

**Comment by judsonmusic** [comment] 2017-09-27 12:54
Did this ever get resolved? If so what do I need to update to see the change?
