### ISSUE TITLE
Problem to run ionic command line

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic-cli#817] opened 2016-03-05 18:27 UTC
_From @zhouhao27 on March 5, 2016 9:25_

Got the following error message:

> Error: Cannot read property 'indexOf' of null

When I was trying to run:

> ionic emulate ios
> cordova prepare
> ionic build

But **ionic server** is fine.

Tried both ionic-cli 1.7.14 and 2.0.0.beta19. Both the same problem.

_Copied from original issue: driftyco/ionic#5728_

**Comment by tlancina** [comment] 2016-03-06 13:56
Closing as a duplicate of https://github.com/driftyco/ionic-cli/issues/815, please track it there, thanks!

**Closed by tlancina** 2016-03-06 13:56 UTC
Labels: platform:ios
