### ISSUE TITLE
Missing updates to CHANGELOG.md

### ISSUE THREAD

**Issue by DOFandersolsen** [driftyco/ionic-cli#727] opened 2016-01-25 09:39 UTC
I was just notified that a new Ionic CLI was available:

```
------------------------------------
Ionic CLI is out of date:
 * Locally installed version: 1.7.12
 * Latest version: 1.7.13
 * https://github.com/driftyco/ionic-cli/blob/master/CHANGELOG.md
 * Run npm install -g ionic to update
------------------------------------
```

However, the CHANGELOG.md file have not been updated since version 1.7.7
This makes it very hard to see what potential change might have caused a break in mine or others code that is based on Ionic.

Kind regards
Anders

**Comment by jimmyhax** [comment] 2016-01-25 14:34
Agreed. I'm sure we all would like to know what changes have been made before we update. 
Thanks in advance.

**Comment by s200920014** [comment] 2016-01-25 15:47
+1

**Comment by mcintosh101** [comment] 2016-01-27 15:26
+1

**Comment by andRyanMiller** [comment] 2016-02-02 17:11
+1

**Comment by GC-Mark** [comment] 2016-02-03 15:26
+1

**Comment by malek-bessaies** [comment] 2016-02-05 08:49
+1

**Comment by calebfaruki** [comment] 2016-02-08 14:56
+1

We're now on v1.7.14. Changelog remains at 1.7.7

**Comment by TheMattRay** [comment] 2016-02-09 15:04
Duplicate of #679

**Comment by jgw96** [comment] 2016-05-02 19:59
Hello all, as this is a dupe of #679 i will be closing this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-05-02 19:59 UTC
