### ISSUE TITLE
error

### ISSUE THREAD

**Issue by sunoto** [driftyco/ionic-cli#1495] opened 2016-10-08 05:42 UTC
ionic start myapp sidemenu --v2
Creating Ionic app in folder D:\myapp based on sidemenu project
Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic2-starter-sidemenu/archive/master.zip
[=============================]  100%  0.0s
Installing npm packages...
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

Cordova CLI: 6.3.1
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.0.0-beta.20
OS: Windows 7 SP1
Node Version: v6.7.0

**Comment by jviana** [comment] 2016-10-08 11:59
I got the same issue
With Ionic CLI Version: 2.1.0 try:
ionic start myapp sidemenu
and let me know the result (it worked for me)

**Comment by perdjurner** [comment] 2016-10-08 12:15
Try installing Git, that fixed it for me:
https://git-scm.com/download

**Comment by jgw96** [comment] 2016-10-12 00:33
Hello all! I am going to close this issue as a duplicate of #1491. Thanks!

**Closed by jgw96** 2016-10-12 00:33 UTC
