### ISSUE TITLE
"out of bounds" error

### ISSUE THREAD

**Issue by klh** [driftyco/ionic-cli#828] opened 2016-03-10 13:53 UTC
Please see:
you've wrongly closed this issue: https://github.com/driftyco/ionic-cli/issues/575

this is not fixed,
its not a plugin issue - but a dependency issue - the ZIP library you're using doesn't support large files or many files well... you should change that dependency.

**Full error is:**
```
buffer.js:716
    throw new TypeError('value is out of bounds');
    ^
TypeError: value is out of bounds
    at checkInt (buffer.js:716:11)
    at Buffer.writeUInt16LE (buffer.js:770:5)
    at /Users/kk/.nvm/versions/node/v0.12.6/lib/node_modules/ionic/node_modules/zip-stream/lib/headers.js:41:32
    at Array.forEach (native)
    at ZipHeaderCentralFooter.ZipHeader.toBuffer (/Users/kk/.nvm/versions/node/v0.12.6/lib/node_modules/ionic/node_modules/zip-stream/lib/headers.js:28:15)
    at Object.exports.encode (/Users/kk/.nvm/versions/node/v0.12.6/lib/node_modules/ionic/node_modules/zip-stream/lib/headers.js:198:24)
    at ZipStream._writeCentralDirectory (/Users/kk/.nvm/versions/node/v0.12.6/lib/node_modules/ionic/node_modules/zip-stream/lib/zip-stream.js:220:22)
    at ZipStream.finalize (/Users/kk/.nvm/versions/node/v0.12.6/lib/node_modules/ionic/node_modules/zip-stream/lib/zip-stream.js:270:8)
    at Zip.finalize (/Users/kk/.nvm/versions/node/v0.12.6/lib/node_modules/ionic/node_modules/archiver/lib/modules/zip/index.js:39:15)
    at Archiver._onQueueEnd (/Users/kk/.nvm/versions/node/v0.12.6/lib/node_modules/ionic/node_modules/archiver/lib/modules/core/index.js:91:26)
```

**related issues:**

- https://github.com/archiverjs/node-archiver/issues/61
- https://github.com/archiverjs/node-zip-stream/issues/5
- https://github.com/archiverjs/node-archiver/issues/64

@archiverjs

**Comment by klh** [comment] 2016-04-06 19:25
Please give this some love.

**Comment by klh** [comment] 2016-04-06 19:37
fixed in latest versions do a npm update in node_modules/ionic/node_modules/ionic-app-lib to fix the issue

**Comment by tlancina** [comment] 2016-04-06 23:29
Hey @klh I believe the reason we're using a fixed version of `archiver` is that newer versions cause issues with the Android zip library.

**Comment by klh** [comment] 2016-04-07 20:36
so you're okay with package, build and upload not working due to this?, my app is not particularly big - and i'm allready hitting the limits of what can be zipped.... how bout you just use g  instead or some other archiver that works?

https://www.npmjs.com/package/tar.gz

**Comment by klh** [comment] 2016-04-07 20:43
I just upgraded all components of the ionic-app-lib to latests versions, and updated the packages.json file.
I'm not seeing any problems with Android or with the cli itself - (on mac) perhaps you should do the same and have QA test it.

**Comment by tlancina** [comment] 2016-04-08 15:45
@klh not saying it's okay, and I agree it needs to be looked into, but it's lower priority at the moment.

@dwieeb can you weigh in on what the issues were and ideas on a way to upgrade without breaking package?

**Comment by dwieeb** [comment] 2016-04-12 04:43
@tlancina It's _Uploads_ that need to change. Package utilizes uploads just as deploy does. The root cause is that uploads are zips. 

@klh So you tested an updated archiver version and Ionic Deploy on android and it worked? Can I have specifics? Android version, etc? This is a confirmed issue here: https://github.com/archiverjs/node-compress-commons/issues/16 It would be great if it was magically fixed. I will revisit it again this week.

Right now it's a choice between not being able to support larger apps in the immediate future and breaking everybody's apps on Android devices when they use deploy. We are trying to do a lot with the CLI, but there is a surprising amount of server code tied to uploads working the way that they do today. It can't be switched over to tar.gz in the blink of an eye.

**Comment by jthoms1** [comment] 2016-10-28 02:00
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.

**Closed by jthoms1** 2016-10-28 02:00 UTC
